[build]
  base = "/"
  command = "if [ ! -d flutter ]; then git clone https://github.com/flutter/flutter.git -b stable; fi && export PATH=\"$PATH:`pwd`/flutter/bin\" && flutter doctor && flutter config --enable-web && flutter build web --release"
  publish = "build/web"

[build.environment]
  NODE_VERSION = "16"  # 必要に応じてNode.jsのバージョンを指定
  REVIEW_ID = "12345"  # 必要に応じて環境変数を追加
