[build]
  publish = "build/web"
  command = """
    if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter channel master
    flutter version 3.28.0
    flutter config --enable-web
    flutter build web --release
  """

[build.environment]
  PUB_CACHE = "/opt/build/cache/.pub-cache"
