import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> uploadWordsToFirestore() async {
  final firestore = FirebaseFirestore.instance;
  final collectionPath = 'English_Skills/TOEIC/up_to_500/Words/Word';

  // 登録するデータ
  final List<Map<String, dynamic>> wordsData = [
    {
        'word': 'analyze',
        'explanation': '分析のために調査や評価を行うこと',
        'exampleSentence': 'Scientists a______ data to find patterns.',
        'japaneseTranslation': '科学者たちはパターンを見つけるためにデータを分析します。',
        'meaningVerb': '分析する',
        'phoneticSymbols': '/əˈnælaɪz/',
        'wordNoun': 'analysis',
        'wordAdjective': 'analytical',
        'wordAdverb': 'analytically',
        'wordSynonyms': 'study, evaluate, assess',
        'wordAntonym': 'synthesize',
        'ENG_to_JPN_Answer':'分析する',
        'ENG_to_JPN_Answer_A':'分析する',
        'ENG_to_JPN_Answer_B':'解剖する',
        'ENG_to_JPN_Answer_C':'統合する',
        'ENG_to_JPN_Answer_D':'要約する',
    },
    {
        'word': 'synthesize',
        'explanation': '異なる情報をまとめて新しいものを生み出すこと',
        'exampleSentence': 'The researcher s_________d findings from multiple studies.',
        'japaneseTranslation': '研究者は複数の研究結果をまとめた。',
        'meaningVerb': '統合する',
        'phoneticSymbols': '/ˈsɪnθəˌsaɪz/',
        'wordNoun': 'synthesis',
        'wordAdjective': 'synthetic',
        'wordAdverb': 'synthetically',
        'wordSynonyms': 'combine, integrate',
        'wordAntonym': 'analyze',
        'ENG_to_JPN_Answer':'統合する',
        'ENG_to_JPN_Answer_A':'分割する',
        'ENG_to_JPN_Answer_B':'統計をとる',
        'ENG_to_JPN_Answer_C':'統合する',
        'ENG_to_JPN_Answer_D':'総括する',
    },
    {
        'word': 'achievement',
        'explanation': '努力の結果としての成果または業績',
        'exampleSentence': 'Winning the championship was a great a__________.',
        'japaneseTranslation': '優勝することは大きな成果でした。',
        'meaningNoun': '成果',
        'phoneticSymbols': '/əˈtʃiːvmənt/',
        'wordAdjective': 'achievable',
        'wordSynonyms': 'success, accomplishment',
        'wordAntonym': 'failure',
        'ENG_to_JPN_Answer':'成果',
        'ENG_to_JPN_Answer_A':'成果',
        'ENG_to_JPN_Answer_B':'添加物',
        'ENG_to_JPN_Answer_C':'改良',
        'ENG_to_JPN_Answer_D':'道のり',
    },
    {
        'word': 'quickly',
        'explanation': '短い時間内に、速く',
        'exampleSentence': 'He q______ finished his homework.',
        'japaneseTranslation': '彼はすぐに宿題を終えました。',
        'meaningAdverb': '速く',
        'phoneticSymbols': '/ˈkwɪkli/',
        'wordSynonyms': 'rapidly, swiftly',
        'wordAntonym': 'slowly',
        'ENG_to_JPN_Answer':'速く',
        'ENG_to_JPN_Answer_A':'速く',
        'ENG_to_JPN_Answer_B':'静かに',
        'ENG_to_JPN_Answer_C':'かなり',
        'ENG_to_JPN_Answer_D':'急いで',
    },
    {
        'word': 'decision',
        'explanation': '何かを決定する行為または過程',
        'exampleSentence': 'The manager made a difficult d_______.',
        'japaneseTranslation': 'マネージャーは難しい決定を下しました。',
        'meaningNoun': '決定',
        'phoneticSymbols': '/dɪˈsɪʒən/',
        'wordVerb': 'decide',
        'wordSynonyms': 'choice, resolution',
        'wordAntonym': 'indecision',
        'ENG_to_JPN_Answer':'決定',
        'ENG_to_JPN_Answer_A':'決定',
        'ENG_to_JPN_Answer_B':'分割',
        'ENG_to_JPN_Answer_C':'除外',
        'ENG_to_JPN_Answer_D':'分配',
    },
    {
        'word': 'carefully',
        'explanation': '注意深く、慎重に',
        'exampleSentence': 'She c________ reviewed the contract before signing.',
        'japaneseTranslation': '彼女は署名する前に契約を慎重に確認しました。',
        'meaningAdverb': '慎重に',
        'phoneticSymbols': '/ˈkeəfəli/',
        'wordSynonyms': 'cautiously, attentively',
        'wordAntonym': 'carelessly',
        'ENG_to_JPN_Answer':'注意深く',
        'ENG_to_JPN_Answer_A':'注意深く',
        'ENG_to_JPN_Answer_B':'無頓着に',
        'ENG_to_JPN_Answer_C':'軽く',
        'ENG_to_JPN_Answer_D':'親切に',
    },
    {
        'word': 'happiness',
        'explanation': '喜びや満足感の状態',
        'exampleSentence': 'H________ is more important than wealth.',
        'japaneseTranslation': '幸福は富よりも大切です。',
        'meaningNoun': '幸福',
        'phoneticSymbols': '/ˈhæpɪnəs/',
        'wordAdjective': 'happy',
        'wordSynonyms': 'joy, contentment',
        'wordAntonym': 'sadness',
        'ENG_to_JPN_Answer':'幸福',
        'ENG_to_JPN_Answer_A':'幸福',
        'ENG_to_JPN_Answer_B':'幸福に',
        'ENG_to_JPN_Answer_C':'幸福な',
        'ENG_to_JPN_Answer_D':'偶然',
    },
    {
        'word': 'accomplishment',
        'explanation': '何かを成し遂げた結果、または達成された成果',
        'exampleSentence': 'Completing the project on time was a huge a_____________.',
        'japaneseTranslation': 'プロジェクトを時間通りに完了することは大きな達成でした。',
        'meaningNoun': '達成',
        'phoneticSymbols': '/əˈkɒmplɪʃmənt/',
        'wordAdjective': 'accomplished',
        'wordSynonyms': 'achievement, success',
        'wordAntonym': 'failure',
        'ENG_to_JPN_Answer':'達成',
        'ENG_to_JPN_Answer_A':'実行',
        'ENG_to_JPN_Answer_B':'成果',
        'ENG_to_JPN_Answer_C':'達成',
        'ENG_to_JPN_Answer_D':'複雑さ',
    },
    {
        'word': 'failure',
        'explanation': '期待された結果を達成できないこと、またはその状態',
        'exampleSentence': 'His f______ to submit the report on time caused problems.',
        'japaneseTranslation': '報告書を時間通りに提出できなかったことが問題を引き起こした。',
        'meaningNoun': '失敗',
        'phoneticSymbols': '/ˈfeɪljər/',
        'wordAdjective': 'failed',
        'wordSynonyms': 'defeat, setback',
        'wordAntonym': 'achievement, accomplishment',
        'ENG_to_JPN_Answer':'失敗',
        'ENG_to_JPN_Answer_A':'失敗',
        'ENG_to_JPN_Answer_B':'欠陥',
        'ENG_to_JPN_Answer_C':'落下',
        'ENG_to_JPN_Answer_D':'正解',
    },
    {
        'word': 'contentment',
        'explanation': '満足感や安らぎの状態',
        'exampleSentence': 'She found c__________ in the simple pleasures of life.',
        'japaneseTranslation': '彼女は人生のささやかな喜びに満足感を見つけた。',
        'meaningNoun': '満足感',
        'phoneticSymbols': '/kənˈtɛntmənt/',
        'wordAdjective': 'content',
        'wordSynonyms': 'satisfaction, happiness',
        'wordAntonym': 'discontent',
        'ENG_to_JPN_Answer':'満足感',
        'ENG_to_JPN_Answer_A':'満足感',
        'ENG_to_JPN_Answer_B':'含有',
        'ENG_to_JPN_Answer_C':'中身',
        'ENG_to_JPN_Answer_D':'競争',
    },
    {
        'word': 'anyway',
        'explanation': '文や発言を締めくくるときに使う副詞、または会話の流れを変えるときに使う表現',
        'exampleSentence': 'It might rain, but we are going hiking a_____.',
        'japaneseTranslation': '雨が降るかもしれないが、私たちはとにかくハイキングに行きます。',
        'meaningAdverb': 'とにかく',
        'phoneticSymbols': '/ˈɛnɪweɪ/',
        'wordSynonyms': 'nonetheless, regardless',
        'ENG_to_JPN_Answer':'とにかく',
        'ENG_to_JPN_Answer_A':'とにかく',
        'ENG_to_JPN_Answer_B':'どちらにしても',
        'ENG_to_JPN_Answer_C':'何か方法があれば',
        'ENG_to_JPN_Answer_D':'どうして',
    },
    {
        'word': 'following',
        'explanation': 'すぐ後に続くものや人、または次に続くもの',
        'exampleSentence': 'Please read the f________ instructions carefully.',
        'japaneseTranslation': '以下の指示をよく読んでください。',
        'meaningAdjective': '次の',
        'meaningNoun': '次のもの',
        'phoneticSymbols': '/ˈfɒloʊɪŋ/',
        'wordVerb': 'follow',
        'wordSynonyms': 'next, subsequent',
        'wordAntonym': 'preceding',
        'ENG_to_JPN_Answer':'次の',
        'ENG_to_JPN_Answer_A':'追随する',
        'ENG_to_JPN_Answer_B':'次第に',
        'ENG_to_JPN_Answer_C':'追跡',
        'ENG_to_JPN_Answer_D':'次の',
    },
    {
        'word': 'refer',
        'explanation': '特定の情報や資料に言及すること、または参照すること',
        'exampleSentence': 'Please r____ to the user manual for more details.',
        'japaneseTranslation': '詳細は取扱説明書を参照してください。',
        'meaningVerb': '参照する',
        'phoneticSymbols': '/rɪˈfɜːr/',
        'wordNoun': 'reference',
        'wordAdjective': 'referable',
        'wordSynonyms': 'mention, cite',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'参照する',
        'ENG_to_JPN_Answer_A':'参照する',
        'ENG_to_JPN_Answer_B':'推奨する',
        'ENG_to_JPN_Answer_C':'記録する',
        'ENG_to_JPN_Answer_D':'転送する',
    },
    {
        'word': 'available',
        'explanation': '利用可能な、または手に入れることができる',
        'exampleSentence': 'The product is a________ in all stores.',
        'japaneseTranslation': 'その製品はすべての店舗で入手可能です。',
        'meaningAdjective': '利用可能な',
        'phoneticSymbols': '/əˈveɪləbəl/',
        'wordNoun': 'availability',
        'wordSynonyms': 'accessible, obtainable',
        'wordAntonym': 'unavailable',
        'ENG_to_JPN_Answer':'利用可能な',
        'ENG_to_JPN_Answer_A':'利用可能な',
        'ENG_to_JPN_Answer_B':'有効な',
        'ENG_to_JPN_Answer_C':'価値のある',
        'ENG_to_JPN_Answer_D':'到達可能な',
    },
    {
        'word': 'department',
        'explanation': '組織内で特定の業務や機能を担当する部門',
        'exampleSentence': 'She works in the sales d_________.',
        'japaneseTranslation': '彼女は営業部で働いています。',
        'meaningNoun': '部門',
        'phoneticSymbols': '/dɪˈpɑːrtmənt/',
        'wordSynonyms': 'division, section',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'部門',
        'ENG_to_JPN_Answer_A':'部署',
        'ENG_to_JPN_Answer_B':'依存',
        'ENG_to_JPN_Answer_C':'出発',
        'ENG_to_JPN_Answer_D':'部門',
    },
    {
        'word': 'conference',
        'explanation': '特定のテーマについて話し合うために集まる公式の会議',
        'exampleSentence': 'The annual c_________ will be held in New York.',
        'japaneseTranslation': '年次会議はニューヨークで開催されます。',
        'meaningNoun': '会議',
        'phoneticSymbols': '/ˈkɒn.fər.əns/',
        'wordSynonyms': 'meeting, convention',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'会議',
        'ENG_to_JPN_Answer_A':'会議',
        'ENG_to_JPN_Answer_B':'告白する',
        'ENG_to_JPN_Answer_C':'参照',
        'ENG_to_JPN_Answer_D':'自信',
    },
    {
        'word': 'according to',
        'explanation': '情報源を示すために使う表現、～によれば',
        'exampleSentence': 'A________ to the report, sales have increased by 10%.',
        'japaneseTranslation': 'その報告書によれば、売上は10%増加しました。',
        'meaningPreposition': '～によると',
        'phoneticSymbols': '/əˈkɔːrdɪŋ tuː/',
        'wordSynonyms': 'as per, based on',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'〜によると',
        'ENG_to_JPN_Answer_A':'〜に応じて',
        'ENG_to_JPN_Answer_B':'一致する',
        'ENG_to_JPN_Answer_C':'正確に',
        'ENG_to_JPN_Answer_D':'〜なので',
    },
    {
        'word': 'likely',
        'explanation': '何かが起こる可能性が高いことを示す形容詞',
        'exampleSentence': 'It is likely to rain tomorrow.',
        'japaneseTranslation': '明日は雨が降る可能性が高いです。',
        'meaningAdjective': '〜しそうだ',
        'meaningAdverb': 'おそらく',
        'phoneticSymbols': '/ˈlaɪk.li/',
        'wordAdverb': 'likelihood',
        'wordSynonyms': 'probable, expected',
        'wordAntonym': 'unlikely',
        'ENG_to_JPN_Answer':'〜しそうだ',
        'ENG_to_JPN_Answer_A':'〜しそうだ',
        'ENG_to_JPN_Answer_B':'好きである',
        'ENG_to_JPN_Answer_C':'可能性がない',
        'ENG_to_JPN_Answer_D':'好意的な',
    },
    {
        'word': 'offer',
        'explanation': '何かを提供する、提案する、または申し出ること',
        'exampleSentence': 'They o____ed him a job at the company.',
        'japaneseTranslation': '彼らは彼に会社での仕事を提案しました。',
        'meaningVerb': '提供する',
        'meaningNoun': '申し出',
        'phoneticSymbols': '/ˈɔː.fər/',
        'wordNoun': 'offering',
        'wordAdjective': 'offered',
        'wordSynonyms': 'propose',
        'wordAntonym': 'withhold',
        'ENG_to_JPN_Answer':'提供する',
        'ENG_to_JPN_Answer_A':'提供する',
        'ENG_to_JPN_Answer_B':'主張する',
        'ENG_to_JPN_Answer_C':'提案する',
        'ENG_to_JPN_Answer_D':'申し出る',
    },
    {
        'word': 'equipment',
        'explanation': '特定の活動や目的に使用される器具や装置',
        'exampleSentence': 'The gym has new exercise e________.',
        'japaneseTranslation': 'そのジムには新しい運動器具があります。',
        'meaningNoun': '装置、器具',
        'phoneticSymbols': '/ɪˈkwɪp.mənt/',
        'wordVerb': 'equip',
        'wordAdjective': 'equipped',
        'wordSynonyms': 'gear, apparatus',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'器具',
        'ENG_to_JPN_Answer_A':'用意',
        'ENG_to_JPN_Answer_B':'器具',
        'ENG_to_JPN_Answer_C':'訓練',
        'ENG_to_JPN_Answer_D':'家具',
    },
    {
        'word': 'display',
        'explanation': '情報や物を視覚的に見せる、または示すこと',
        'exampleSentence': 'The store d______s its latest products in the front window.',
        'japaneseTranslation': 'その店は最新の商品を店の前のウィンドウに展示しています。',
        'meaningVerb': '表示する',
        'meaningNoun': '展示',
        'phoneticSymbols': '/dɪˈspleɪ/',
        'wordAdjective': 'displayed',
        'wordSynonyms': 'show, exhibit',
        'wordAntonym': 'hide',
        'ENG_to_JPN_Answer':'表示する',
        'ENG_to_JPN_Answer_A':'表示する',
        'ENG_to_JPN_Answer_B':'供給する',
        'ENG_to_JPN_Answer_C':'説明する',
        'ENG_to_JPN_Answer_D':'置く',
    },
    {
        'word': 'process',
        'explanation': '一連の行動や手順を通じて何かを処理すること',
        'exampleSentence': 'We need to p______ the data before making any decisions.',
        'japaneseTranslation': '私たちは決定を下す前にデータを処理する必要があります。',
        'meaningVerb': '処理する',
        'meaningNoun': '過程',
        'phoneticSymbols': '/ˈprɑː.ses/',
        'wordAdjective': 'processed',
        'wordSynonyms': 'handle, deal with',
        'wordAntonym': 'neglect',
        'ENG_to_JPN_Answer':'過程',
        'ENG_to_JPN_Answer_A':'過程',
        'ENG_to_JPN_Answer_B':'進行',
        'ENG_to_JPN_Answer_C':'処理',
        'ENG_to_JPN_Answer_D':'方法',
    },
    {
        'word': 'provide',
        'explanation': '必要なものやサービスを供給する',
        'exampleSentence': 'We p______ excellent customer service.',
        'japaneseTranslation': '私たちは優れた顧客サービスを提供します。',
        'meaningVerb': '提供する',
        'phoneticSymbols': '/prəˈvaɪd/',
        'wordNoun': 'provision',
        'wordAdjective': 'providable',
        'wordSynonyms': 'supply, furnish',
        'wordAntonym': 'withhold',
        'ENG_to_JPN_Answer':'提供する',
        'ENG_to_JPN_Answer_A':'供給する',
        'ENG_to_JPN_Answer_B':'証明する',
        'ENG_to_JPN_Answer_C':'伏せず',
        'ENG_to_JPN_Answer_D':'提供する',
    },
    {
        'word': 'indicate',
        'explanation': '情報を指し示す、または明らかにする',
        'exampleSentence': 'The report i_______s that sales have increased.',
        'japaneseTranslation': 'その報告書は売上が増加したことを示しています。',
        'meaningVerb': '示す',
        'phoneticSymbols': '/ˈɪn.dɪ.keɪt/',
        'wordNoun': 'indication',
        'wordAdjective': 'indicative',
        'wordSynonyms': 'show, point out',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'示す',
        'ENG_to_JPN_Answer_A':'示す',
        'ENG_to_JPN_Answer_B':'指導する',
        'ENG_to_JPN_Answer_C':'強調する',
        'ENG_to_JPN_Answer_D':'暗示する',
    },
    {
        'word': 'submit',
        'explanation': '公式に何かを提出する',
        'exampleSentence': 'Please s_____ your application by next Friday.',
        'japaneseTranslation': '来週の金曜日までに申請書を提出してください。',
        'meaningVerb': '提出する',
        'phoneticSymbols': '/səbˈmɪt/',
        'wordNoun': 'submission',
        'wordAdjective': 'submitted',
        'wordSynonyms': 'present, hand in',
        'wordAntonym': 'withhold',
        'ENG_to_JPN_Answer':'提出する',
        'ENG_to_JPN_Answer_A':'従う',
        'ENG_to_JPN_Answer_B':'受け取る',
        'ENG_to_JPN_Answer_C':'許可する',
        'ENG_to_JPN_Answer_D':'提出する',
    },
    {
        'word': 'expense',
        'explanation': '特定の目的に使われたお金、費用',
        'exampleSentence': 'The travel e______s will be reimbursed.',
        'japaneseTranslation': '旅行費用は払い戻されます。',
        'meaningNoun': '費用',
        'phoneticSymbols': '/ɪkˈspɛns/',
        'wordAdjective': 'expensive',
        'wordSynonyms': 'cost, expenditure',
        'wordAntonym': 'income',
        'ENG_to_JPN_Answer':'費用',
        'ENG_to_JPN_Answer_A':'支出',
        'ENG_to_JPN_Answer_B':'経験',
        'ENG_to_JPN_Answer_C':'費用',
        'ENG_to_JPN_Answer_D':'拡張',
    },
    {
        'word': 'outcome',
        'explanation': 'ある行動や出来事の結果',
        'exampleSentence': 'The o______ of the meeting was positive.',
        'japaneseTranslation': '会議の結果は良好でした。',
        'meaningNoun': '結果',
        'phoneticSymbols': '/ˈaʊt.kʌm/',
        'wordSynonyms': 'result, consequence',
        'wordAntonym': 'cause',
        'ENG_to_JPN_Answer':'結果',
        'ENG_to_JPN_Answer_A':'結果',
        'ENG_to_JPN_Answer_B':'外出',
        'ENG_to_JPN_Answer_C':'出口',
        'ENG_to_JPN_Answer_D':'収入',
    },
    {
        'word': 'workload',
        'explanation': '特定の期間に割り当てられた仕事量',
        'exampleSentence': 'Her w_______ has increased significantly.',
        'japaneseTranslation': '彼女の仕事量は大幅に増えました。',
        'meaningNoun': '仕事量',
        'phoneticSymbols': '/ˈwɜːrk.loʊd/',
        'wordSynonyms': 'task load, amount of work',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'仕事量',
        'ENG_to_JPN_Answer_A':'職場環境',
        'ENG_to_JPN_Answer_B':'作業方法',
        'ENG_to_JPN_Answer_C':'仕事量',
        'ENG_to_JPN_Answer_D':'重労働',
    },
    {
        'word': 'transfer',
        'explanation': '何かを別の場所や状況に移動させること',
        'exampleSentence': 'She was t_______red to the New York office.',
        'japaneseTranslation': '彼女はニューヨーク支社に転勤しました。',
        'meaningVerb': '移す',
        'meaningNoun': '移転',
        'phoneticSymbols': '/ˈtræns.fɜːr/',
        'wordAdjective': 'transferable',
        'wordSynonyms': 'move, shift',
        'wordAntonym': 'retain',
        'ENG_to_JPN_Answer':'移す',
        'ENG_to_JPN_Answer_A':'移す',
        'ENG_to_JPN_Answer_B':'輸送する',
        'ENG_to_JPN_Answer_C':'翻訳する',
        'ENG_to_JPN_Answer_D':'変形する',
    },
    {
        'word': 'stress',
        'explanation': '精神的な緊張や圧力の状態',
        'exampleSentence': 'He is under a lot of s_____ at work.',
        'japaneseTranslation': '彼は仕事で大きなストレスを抱えています。',
        'meaningNoun': 'ストレス',
        'meaningVerb': '強調する',
        'phoneticSymbols': '/strɛs/',
        'wordAdjective': 'stressful',
        'wordSynonyms': 'tension, pressure',
        'wordAntonym': 'relaxation',
        'ENG_to_JPN_Answer':'ストレス',
        'ENG_to_JPN_Answer_A':'ストレス',
        'ENG_to_JPN_Answer_B':'強調',
        'ENG_to_JPN_Answer_C':'圧力',
        'ENG_to_JPN_Answer_D':'負荷',
    },
    {
        'word': 'despite',
        'explanation': 'ある状況に関わらず',
        'exampleSentence': 'D______ the rain, we went for a hike.',
        'japaneseTranslation': '雨にもかかわらず、私たちはハイキングに行きました。',
        'meaningPreposition': 'にもかかわらず',
        'phoneticSymbols': '/dɪˈspaɪt/',
        'wordSynonyms': 'in spite of, regardless of',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'にもかかわらず',
        'ENG_to_JPN_Answer_A':'にもかかわらず',
        'ENG_to_JPN_Answer_B':'絶望',
        'ENG_to_JPN_Answer_C':'軽蔑する',
        'ENG_to_JPN_Answer_D':'論争',
    },
    {
        'word': 'specialize',
        'explanation': '特定の分野で専門知識を持つ',
        'exampleSentence': 'He s_________s in digital marketing.',
        'japaneseTranslation': '彼はデジタルマーケティングを専門としています。',
        'meaningVerb': '専門とする',
        'phoneticSymbols': '/ˈspɛʃəlaɪz/',
        'wordNoun': 'specialization',
        'wordAdjective': 'specialized',
        'wordSynonyms': 'focus on, concentrate on',
        'wordAntonym': 'generalize',
        'ENG_to_JPN_Answer':'専門とする',
        'ENG_to_JPN_Answer_A':'特別な',
        'ENG_to_JPN_Answer_B':'特定の',
        'ENG_to_JPN_Answer_C':'特殊化する',
        'ENG_to_JPN_Answer_D':'専門とする',
    },
    {
        'word': 'cashier',
        'explanation': 'お金のやり取りをする店員',
        'exampleSentence': 'The c______ gave me the correct change.',
        'japaneseTranslation': 'レジ係は私に正しいお釣りを渡してくれました。',
        'meaningNoun': 'レジ係',
        'phoneticSymbols': '/kæˈʃɪər/',
        'wordSynonyms': 'clerk, teller',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'レジ係',
        'ENG_to_JPN_Answer_A':'レジ係',
        'ENG_to_JPN_Answer_B':'現金',
        'ENG_to_JPN_Answer_C':'会計士',
        'ENG_to_JPN_Answer_D':'キャッシュカード',
    },
    {
        'word': 'construction',
        'explanation': '建物や構造物を建設すること',
        'exampleSentence': 'The c___________ of the new bridge is almost complete.',
        'japaneseTranslation': '新しい橋の建設はほぼ完了しています。',
        'meaningNoun': '建設',
        'phoneticSymbols': '/kənˈstrʌk.ʃən/',
        'wordVerb': 'construct',
        'wordAdjective': 'constructed',
        'wordSynonyms': 'building, creation',
        'wordAntonym': 'destruction',
        'ENG_to_JPN_Answer':'建設',
        'ENG_to_JPN_Answer_A':'構築',
        'ENG_to_JPN_Answer_B':'支持',
        'ENG_to_JPN_Answer_C':'建設',
        'ENG_to_JPN_Answer_D':'解釈',
    },
    {
        'word': 'sign',
        'explanation': '署名する、または標識や合図',
        'exampleSentence': 'Please s___ your name at the bottom of the form.',
        'japaneseTranslation': 'フォームの下部に名前を署名してください。',
        'meaningVerb': '署名する',
        'meaningNoun': '標識',
        'phoneticSymbols': '/saɪn/',
        'wordAdjective': 'signed',
        'wordSynonyms': 'mark, signal',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'署名する',
        'ENG_to_JPN_Answer_A':'合図',
        'ENG_to_JPN_Answer_B':'署名する',
        'ENG_to_JPN_Answer_C':'視力',
        'ENG_to_JPN_Answer_D':'示す',
    },
    {
        'word': 'previous',
        'explanation': '時間的に先行する、前の',
        'exampleSentence': 'I have no memory of the p_______ day.',
        'japaneseTranslation': '私は前の日の記憶がありません。',
        'meaningAdjective': '以前の',
        'phoneticSymbols': '/ˈpriː.vi.əs/',
        'wordAdverb': 'previously',
        'wordSynonyms': 'earlier, former',
        'wordAntonym': 'next',
        'ENG_to_JPN_Answer':'以前の',
        'ENG_to_JPN_Answer_A':'以前の',
        'ENG_to_JPN_Answer_B':'明確な',
        'ENG_to_JPN_Answer_C':'予防する',
        'ENG_to_JPN_Answer_D':'先入観のある',
    },
    {
        'word': 'aware',
        'explanation': '何かを意識している、または気付いている',
        'exampleSentence': 'She is a____ of the problems we are facing.',
        'japaneseTranslation': '彼女は私たちが直面している問題に気付いています。',
        'meaningAdjective': '気付いている',
        'phoneticSymbols': '/əˈwɛr/',
        'wordAdverb': 'awarely',
        'wordSynonyms': 'conscious, informed',
        'wordAntonym': 'unaware',
        'ENG_to_JPN_Answer':'気づいている',
        'ENG_to_JPN_Answer_A':'注意深い',
        'ENG_to_JPN_Answer_B':'知識のある',
        'ENG_to_JPN_Answer_C':'気づいている',
        'ENG_to_JPN_Answer_D':'興味のある',
    },
    {
        'word': 'profit',
        'explanation': '事業や取引から得られる収益や利益',
        'exampleSentence': 'The company made a significant p_____ this year.',
        'japaneseTranslation': 'その会社は今年大きな利益を上げました。',
        'meaningNoun': '利益',
        'meaningVerb': '利益を得る',
        'phoneticSymbols': '/ˈprɑː.fɪt/',
        'wordAdjective': 'profitable',
        'wordSynonyms': 'gain, earnings',
        'wordAntonym': 'loss',
        'ENG_to_JPN_Answer':'利益',
        'ENG_to_JPN_Answer_A':'利益',
        'ENG_to_JPN_Answer_B':'利子',
        'ENG_to_JPN_Answer_C':'収益',
        'ENG_to_JPN_Answer_D':'進歩',
    },
    {
        'word': 'expert',
        'explanation': '特定の分野で非常に熟練した人',
        'exampleSentence': 'He is an e_____ in computer programming.',
        'japaneseTranslation': '彼はコンピュータプログラミングの専門家です。',
        'meaningNoun': '専門家',
        'meaningAdjective': '熟練した',
        'phoneticSymbols': '/ˈɛk.spɜːrt/',
        'wordAdjective': 'expertly',
        'wordSynonyms': 'specialist',
        'wordAntonym': 'novice',
        'ENG_to_JPN_Answer':'熟達した',
        'ENG_to_JPN_Answer_A':'輸入する',
        'ENG_to_JPN_Answer_B':'期限が切れる',
        'ENG_to_JPN_Answer_C':'引用',
        'ENG_to_JPN_Answer_D':'熟達した',
    },
    {
        'word': 'insurance',
        'explanation': '保険契約、事故や損失に備えるための保障',
        'exampleSentence': 'I need to renew my car i________.',
        'japaneseTranslation': '私は車の保険を更新する必要があります。',
        'meaningNoun': '保険',
        'phoneticSymbols': '/ɪnˈʃʊr.əns/',
        'wordSynonyms': 'protection, coverage',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'保険',
        'ENG_to_JPN_Answer_A':'自信',
        'ENG_to_JPN_Answer_B':'確実にする',
        'ENG_to_JPN_Answer_C':'保険',
        'ENG_to_JPN_Answer_D':'例',
    },
    {
        'word': 'performance',
        'explanation': '仕事や活動の成果や質',
        'exampleSentence': 'Her p__________ in the play was outstanding.',
        'japaneseTranslation': '彼女の劇での演技は素晴らしかった。',
        'meaningNoun': 'パフォーマンス、演技、成果',
        'phoneticSymbols': '/pərˈfɔːr.məns/',
        'wordAdjective': 'performant',
        'wordSynonyms': 'execution',
        'wordAntonym': 'failure',
        'ENG_to_JPN_Answer':'演技',
        'ENG_to_JPN_Answer_A':'実施',
        'ENG_to_JPN_Answer_B':'行動',
        'ENG_to_JPN_Answer_C':'公園',
        'ENG_to_JPN_Answer_D':'演技',
    },
    {
        'word': 'initial',
        'explanation': '最初の、または初期の',
        'exampleSentence': 'The i______ plan was changed due to unforeseen circumstances.',
        'japaneseTranslation': '予期しない事情により最初の計画が変更されました。',
        'meaningAdjective': '初期の',
        'phoneticSymbols': '/ɪˈnɪʃ.əl/',
        'wordNoun': 'initialization',
        'wordAdverb': 'initially',
        'wordSynonyms': 'first, primary',
        'wordAntonym': 'final',
        'ENG_to_JPN_Answer':'初期の',
        'ENG_to_JPN_Answer_A':'初期の',
        'ENG_to_JPN_Answer_B':'主導権',
        'ENG_to_JPN_Answer_C':'固有の',
        'ENG_to_JPN_Answer_D':'開始',
    },
    {
        'word': 'correspond',
        'explanation': '一致する、または通信する',
        'exampleSentence': 'The data c_________s with our findings.',
        'japaneseTranslation': 'そのデータは私たちの発見と一致しています。',
        'meaningVerb': '一致する',
        'phoneticSymbols': '/ˌkɔːr.əˈspɑːnd/',
        'wordNoun': 'correspondence',
        'wordAdjective': 'corresponding',
        'wordSynonyms': 'match, communicate',
        'wordAntonym': 'differ',
        'ENG_to_JPN_Answer':'一致する',
        'ENG_to_JPN_Answer_A':'一致する',
        'ENG_to_JPN_Answer_B':'修復する',
        'ENG_to_JPN_Answer_C':'集める',
        'ENG_to_JPN_Answer_D':'応答する',
    },
    {
        'word': 'assign',
        'explanation': '特定の人に仕事やタスクを割り当てる',
        'exampleSentence': 'The manager a_____ed the project to her team.',
        'japaneseTranslation': 'マネージャーはプロジェクトを彼女のチームに割り当てました。',
        'meaningVerb': '割り当てる',
        'phoneticSymbols': '/əˈsaɪn/',
        'wordNoun': 'assignment',
        'wordAdjective': 'assigned',
        'wordSynonyms': 'allocate, designate',
        'wordAntonym': 'remove',
        'ENG_to_JPN_Answer':'割り当てる',
        'ENG_to_JPN_Answer_A':'割り当てる',
        'ENG_to_JPN_Answer_B':'署名する',
        'ENG_to_JPN_Answer_C':'同意する',
        'ENG_to_JPN_Answer_D':'仮定する',
    },
    {
        'word': 'exclusive',
        'explanation': '限られた人だけに与えられる、または特別な',
        'exampleSentence': 'This offer is e________ to our premium members.',
        'japaneseTranslation': 'このオファーはプレミアム会員限定です。',
        'meaningAdjective': '排他的な',
        'phoneticSymbols': '/ɪkˈskluː.sɪv/',
        'wordAdverb': 'exclusively',
        'wordNoun': 'exclusivity',
        'wordSynonyms': 'limited, restricted',
        'wordAntonym': 'inclusive',
        'ENG_to_JPN_Answer':'排他的な',
        'ENG_to_JPN_Answer_A':'排他的な',
        'ENG_to_JPN_Answer_B':'包括的な',
        'ENG_to_JPN_Answer_C':'外部の',
        'ENG_to_JPN_Answer_D':'閉じ込める',
    },
    {
        'word': 'make sense',
        'explanation': '理解できる、または意味をなす',
        'exampleSentence': "His explanation didn't m___ s_____ to me.",
        'japaneseTranslation': '彼の説明は私には理解できませんでした。',
        'meaningVerb': '理解できる、意味をなす',
        'phoneticSymbols': '/meɪk sɛns/',
        'wordSynonyms': 'be logical, be clear',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'理解できる',
        'ENG_to_JPN_Answer_A':'理解できる',
        'ENG_to_JPN_Answer_B':'感じる',
        'ENG_to_JPN_Answer_C':'感動させる',
        'ENG_to_JPN_Answer_D':'整理する',
    },
    {
        'word': 'professional',
        'explanation': '特定の職業で熟練した、または専門的な人',
        'exampleSentence': 'She is a p___________ photographer.',
        'japaneseTranslation': '彼女はプロの写真家です。',
        'meaningNoun': '専門家',
        'meaningAdjective': '専門的な',
        'phoneticSymbols': '/prəˈfɛʃənəl/',
        'wordAdverb': 'professionally',
        'wordSynonyms': 'skilled',
        'wordAntonym': 'amateur',
        'ENG_to_JPN_Answer':'専門的な',
        'ENG_to_JPN_Answer_A':'教授の',
        'ENG_to_JPN_Answer_B':'熟練の',
        'ENG_to_JPN_Answer_C':'専門的な',
        'ENG_to_JPN_Answer_D':'職業の',
    },
    {
        'word': 'concern',
        'explanation': '心配や不安、または関心',
        'exampleSentence': 'Her main c______ is the safety of her children.',
        'japaneseTranslation': '彼女の主な関心事は子供たちの安全です。',
        'meaningNoun': '懸念',
        'meaningVerb': '心配する',
        'phoneticSymbols': '/kənˈsɜːrn/',
        'wordAdjective': 'concerned',
        'wordSynonyms': 'worry, anxiety',
        'wordAntonym': 'indifference',
        'ENG_to_JPN_Answer':'懸念',
        'ENG_to_JPN_Answer_A':'観察',
        'ENG_to_JPN_Answer_B':'同意',
        'ENG_to_JPN_Answer_C':'概念',
        'ENG_to_JPN_Answer_D':'演説',
    },
    {
        'word': 'range',
        'explanation': '範囲や広がり、または限界',
        'exampleSentence': 'The store offers a wide r____ of products.',
        'japaneseTranslation': 'その店は幅広い製品を提供しています。',
        'meaningNoun': '範囲',
        'meaningVerb': '及ぶ',
        'phoneticSymbols': '/reɪndʒ/',
        'wordAdjective': 'ranging',
        'wordSynonyms': 'scope, extent',
        'wordAntonym': 'limit',
        'ENG_to_JPN_Answer':'範囲',
        'ENG_to_JPN_Answer_A':'範囲',
        'ENG_to_JPN_Answer_B':'速度',
        'ENG_to_JPN_Answer_C':'領域',
        'ENG_to_JPN_Answer_D':'怒り',
    },
    {
        'word': 'period',
        'explanation': 'ある特定の時間の長さ',
        'exampleSentence': 'The project must be completed within a set p_____.',
        'japaneseTranslation': 'プロジェクトは設定された期間内に完了しなければなりません。',
        'meaningNoun': '期間',
        'phoneticSymbols': '/ˈpɪr.i.əd/',
        'wordSynonyms': 'duration, interval',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'期間',
        'ENG_to_JPN_Answer_A':'期間',
        'ENG_to_JPN_Answer_B':'終わり',
        'ENG_to_JPN_Answer_C':'方法',
        'ENG_to_JPN_Answer_D':'段落',
    },
    {
        'word': 'ability',
        'explanation': '何かを行う力やスキル',
        'exampleSentence': 'He has the a______ to solve complex problems.',
        'japaneseTranslation': '彼には複雑な問題を解決する能力があります。',
        'meaningNoun': '能力',
        'phoneticSymbols': '/əˈbɪl.ə.ti/',
        'wordAdjective': 'able',
        'wordSynonyms': 'capability, skill',
        'wordAntonym': 'inability',
        'ENG_to_JPN_Answer':'能力',
        'ENG_to_JPN_Answer_A':'可能性',
        'ENG_to_JPN_Answer_B':'責任',
        'ENG_to_JPN_Answer_C':'能力',
        'ENG_to_JPN_Answer_D':'能力のある',
    },
    {
        'word': 'succeed',
        'explanation': '目標を達成する、または成功する',
        'exampleSentence': 'She worked hard to s______ in her career.',
        'japaneseTranslation': '彼女はキャリアで成功するために一生懸命働きました。',
        'meaningVerb': '成功する',
        'phoneticSymbols': '/səkˈsiːd/',
        'wordNoun': 'success',
        'wordAdjective': 'successful',
        'wordSynonyms': 'achieve, triumph',
        'wordAntonym': 'fail',
        'ENG_to_JPN_Answer':'成功する',
        'ENG_to_JPN_Answer_A':'成功する',
        'ENG_to_JPN_Answer_B':'提案する',
        'ENG_to_JPN_Answer_C':'追い抜く',
        'ENG_to_JPN_Answer_D':'進行する',
    },
    {
        'word': 'respond',
        'explanation': '何かに返答する、または反応する',
        'exampleSentence': "He didn't r______ to my email.",
        'japaneseTranslation': '彼は私のメールに返事をしませんでした。',
        'meaningVerb': '応答する',
        'phoneticSymbols': '/rɪˈspɒnd/',
        'wordNoun': 'response',
        'wordAdjective': 'responsive',
        'wordSynonyms': 'reply, react',
        'wordAntonym': 'ignore',
        'ENG_to_JPN_Answer':'応答する',
        'ENG_to_JPN_Answer_A':'応答する',
        'ENG_to_JPN_Answer_B':'責任を負う',
        'ENG_to_JPN_Answer_C':'再発する',
        'ENG_to_JPN_Answer_D':'広がる',
    },
    {
        'word': 'rent',
        'explanation': '家や部屋などをお金を払って借りること',
        'exampleSentence': 'We decided to r___ a car for our trip.',
        'japaneseTranslation': '私たちは旅行のために車を借りることにしました。',
        'meaningVerb': '借りる',
        'meaningNoun': '賃貸',
        'phoneticSymbols': '/rɛnt/',
        'wordNoun': 'rental',
        'wordAdjective': 'rented',
        'wordSynonyms': 'lease, hire',
        'wordAntonym': 'own',
        'ENG_to_JPN_Answer':'借りる',
        'ENG_to_JPN_Answer_A':'借りる',
        'ENG_to_JPN_Answer_B':'所有する',
        'ENG_to_JPN_Answer_C':'賃貸する',
        'ENG_to_JPN_Answer_D':'供給する',
    },
    {
        'word': 'proposal',
        'explanation': '提案や計画を提示すること',
        'exampleSentence': 'The p_______ was approved by the committee.',
        'japaneseTranslation': 'その提案は委員会によって承認されました。',
        'meaningNoun': '提案',
        'phoneticSymbols': '/prəˈpoʊ.zəl/',
        'wordVerb': 'propose',
        'wordSynonyms': 'suggestion, plan',
        'wordAntonym': '提案',
        'ENG_to_JPN_Answer':'提案',
        'ENG_to_JPN_Answer_A':'支持',
        'ENG_to_JPN_Answer_B':'申込',
        'ENG_to_JPN_Answer_C':'処置',
        'ENG_to_JPN_Answer_D':'計画',
    },
    {
        'word': 'prevent',
        'explanation': '何かが起こるのを防ぐ',
        'exampleSentence': 'We need to take steps to p______ accidents.',
        'japaneseTranslation': '事故を防ぐための措置を講じる必要があります。',
        'meaningVerb': '防ぐ',
        'phoneticSymbols': '/prɪˈvɛnt/',
        'wordNoun': 'prevention',
        'wordAdjective': 'preventive',
        'wordSynonyms': 'stop, hinder',
        'wordAntonym': 'allow',
        'ENG_to_JPN_Answer':'防ぐ',
        'ENG_to_JPN_Answer_A':'防ぐ',
        'ENG_to_JPN_Answer_B':'提供する',
        'ENG_to_JPN_Answer_C':'促進する',
        'ENG_to_JPN_Answer_D':'防御する',
    },
    {
        'word': 'accompany',
        'explanation': '誰かと一緒に行く、または付き添う',
        'exampleSentence': 'She will a________ her friend to the event.',
        'japaneseTranslation': '彼女は友人に付き添ってイベントに行く予定です。',
        'meaningVerb': '付き添う',
        'phoneticSymbols': '/əˈkʌm.pə.ni/',
        'wordNoun': 'accompaniment',
        'wordAdjective': 'accompanied',
        'wordSynonyms': 'escort, attend',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'付き添う',
        'ENG_to_JPN_Answer_A':'付き添う',
        'ENG_to_JPN_Answer_B':'達成する',
        'ENG_to_JPN_Answer_C':'蓄積する',
        'ENG_to_JPN_Answer_D':'構成する',
    },
    {
        'word': 'qualified',
        'explanation': '特定の職務や活動に適した資格を持つ',
        'exampleSentence': 'He is highly q________ for the job.',
        'japaneseTranslation': '彼はその仕事に非常に適任です。',
        'meaningAdjective': '資格のある',
        'phoneticSymbols': '/ˈkwɒl.ɪ.faɪd/',
        'wordVerb': 'qualify',
        'wordNoun': 'qualification',
        'wordSynonyms': 'certified, competent',
        'wordAntonym': 'unqualified',
        'ENG_to_JPN_Answer':'資格のある',
        'ENG_to_JPN_Answer_A':'資格のある',
        'ENG_to_JPN_Answer_B':'数量化された',
        'ENG_to_JPN_Answer_C':'認定された',
        'ENG_to_JPN_Answer_D':'怯えた',
    },
    {
        'word': 'ordinary',
        'explanation': '特別ではなく、一般的な',
        'exampleSentence': 'It was just an o_______ day at work.',
        'japaneseTranslation': 'それはただの平凡な仕事の日でした。',
        'meaningAdjective': '普通の',
        'phoneticSymbols': '/ˈɔːr.dən.er.i/',
        'wordNoun': 'ordinariness',
        'wordSynonyms': 'common, usual',
        'wordAntonym': 'extraordinary',
        'ENG_to_JPN_Answer':'普通の',
        'ENG_to_JPN_Answer_A':'規則的な',
        'ENG_to_JPN_Answer_B':'並外れた',
        'ENG_to_JPN_Answer_C':'普通の',
        'ENG_to_JPN_Answer_D':'秩序ある',
    },
    {
        'word': 'element',
        'explanation': '一部を構成する基本的な部分',
        'exampleSentence': 'Water is made up of two e______s: hydrogen and oxygen.',
        'japaneseTranslation': '水は水素と酸素の2つの元素から成っています。',
        'meaningNoun': '要素',
        'phoneticSymbols': '/ˈɛl.ɪ.mənt/',
        'wordAdjective': 'elemental',
        'wordSynonyms': 'component, part',
        'wordAntonym': 'whole',
        'ENG_to_JPN_Answer':'要素',
        'ENG_to_JPN_Answer_A':'適合',
        'ENG_to_JPN_Answer_B':'装飾',
        'ENG_to_JPN_Answer_C':'環境',
        'ENG_to_JPN_Answer_D':'要素',
    },
    {
        'word': 'investigate',
        'explanation': '何かを詳細に調査する',
        'exampleSentence': 'The police i__________s the　important case.',
        'japaneseTranslation': '警察は重要な事件を調査する。',
        'meaningVerb': '調査する',
        'phoneticSymbols': '/ɪnˈvɛs.tɪ.ɡeɪt/',
        'wordNoun': 'investigation',
        'wordAdjective': 'investigative',
        'wordSynonyms': 'examine, look into',
        'wordAntonym': '',
        'ENG_to_JPN_Answer':'調査する',
        'ENG_to_JPN_Answer_A':'投資する',
        'ENG_to_JPN_Answer_B':'調査する',
        'ENG_to_JPN_Answer_C':'検討する',
        'ENG_to_JPN_Answer_D':'研究する',
    },
    {
        'word': 'assume',
        'explanation': '何かが真実であると仮定する',
        'exampleSentence': 'I a_____d he knew what he was doing.',
        'japaneseTranslation': '私は彼が自分のしていることを知っていると思った。',
        'meaningVerb': '仮定する',
        'phoneticSymbols': '/əˈsuːm/',
        'wordNoun': 'assumption',
        'wordAdjective': 'assumed',
        'wordSynonyms': 'suppose, presume',
        'wordAntonym': 'doubt',
        'ENG_to_JPN_Answer':'仮定する',
        'ENG_to_JPN_Answer_A':'保証する',
        'ENG_to_JPN_Answer_B':'消費する',
        'ENG_to_JPN_Answer_C':'仮定する',
        'ENG_to_JPN_Answer_D':'再開する',
    },
    {
        'word': 'participate',
        'explanation': '活動やイベントに参加する',
        'exampleSentence': 'He will p__________ in the marathon.',
        'japaneseTranslation': '彼はマラソンに参加します。',
        'meaningVerb': '参加する',
        'phoneticSymbols': '/pɑːrˈtɪs.ɪ.peɪt/',
        'wordNoun': 'participation',
        'wordAdjective': 'participatory',
        'wordSynonyms': 'join, take part',
        'wordAntonym': 'withdraw',
        'ENG_to_JPN_Answer':'参加する',
        'ENG_to_JPN_Answer_A':'部分的に',
        'ENG_to_JPN_Answer_B':'分配する',
        'ENG_to_JPN_Answer_C':'参加する',
        'ENG_to_JPN_Answer_D':'分け与える',
    },
    {
        'word': 'promote',
        'explanation': '何かを奨励する、または昇進させる',
        'exampleSentence': 'The company plans to p______ her to manager.',
        'japaneseTranslation': '会社は彼女をマネージャーに昇進させる予定です。',
        'meaningVerb': '促進させる、昇進させる',
        'phoneticSymbols': '/prəˈmoʊt/',
        'wordNoun': 'promotion',
        'wordAdjective': 'promoted',
        'wordSynonyms': 'advance, elevate',
        'wordAntonym': 'demote',
        'ENG_to_JPN_Answer':'促進させる',
        'ENG_to_JPN_Answer_A':'阻止する',
        'ENG_to_JPN_Answer_B':'提案する',
        'ENG_to_JPN_Answer_C':'促進させる',
        'ENG_to_JPN_Answer_D':'挑発する',
    },
    {
        'word': 'reward',
        'explanation': '努力や成果に対する報酬',
        'exampleSentence': 'She received a r_____ for her hard work.',
        'japaneseTranslation': '彼女は努力に対する報酬を受け取りました。',
        'meaningNoun': '報酬',
        'meaningVerb': '報いる',
        'phoneticSymbols': '/rɪˈwɔːrd/',
        'wordAdjective': 'rewarding',
        'wordSynonyms': 'prize, compensation',
        'wordAntonym': 'penalty',
        'ENG_to_JPN_Answer':'報酬',
        'ENG_to_JPN_Answer_A':'報酬',
        'ENG_to_JPN_Answer_B':'書き直す',
        'ENG_to_JPN_Answer_C':'賞金',
        'ENG_to_JPN_Answer_D':'後ろへ',
    },
    {
        'word': 'postpone',
        'explanation': '何かを後の時間や日に延期する',
        'exampleSentence': 'The meeting has been p_______ed until next week.',
        'japaneseTranslation': '会議は来週まで延期されました。',
        'meaningVerb': '延期する',
        'phoneticSymbols': '/poʊstˈpoʊn/',
        'wordNoun': 'postponement',
        'wordAdjective': 'postponed',
        'wordSynonyms': 'delay, defer',
        'wordAntonym': 'advance',
        'ENG_to_JPN_Answer':'延期する',
        'ENG_to_JPN_Answer_A':'過去',
        'ENG_to_JPN_Answer_B':'延期する',
        'ENG_to_JPN_Answer_C':'さかのぼる',
        'ENG_to_JPN_Answer_D':'昔の',
    },
];

  for (var wordData in wordsData) {
    try {
      // コレクション内のドキュメント数を取得し、新しい Word_id を設定
      final snapshot = await firestore.collection(collectionPath).get();
      final newWordId = snapshot.docs.length + 1;

      // データをFirebaseに保存
      await firestore.collection(collectionPath).add({
        'Word_id': newWordId,
        'ENG_to_JPN_Answer': wordData['ENG_to_JPN_Answer'],
        'ENG_to_JPN_Answer_A': wordData['ENG_to_JPN_Answer_A'],
        'ENG_to_JPN_Answer_B': wordData['ENG_to_JPN_Answer_B'],
        'ENG_to_JPN_Answer_C': wordData['ENG_to_JPN_Answer_C'],
        'ENG_to_JPN_Answer_D': wordData['ENG_to_JPN_Answer_D'],
        'Word': wordData['word'] ?? '',
        'explanation': wordData['explanation'] ?? '',
        'JPN_to_ENG_Answer': wordData['word'] ?? '',
        'JPN_to_ENG_Question_ENG': wordData['exampleSentence'] ?? '',
        'JPN_to_ENG_Question_JPN': wordData['japaneseTranslation'] ?? '',
        'Meaning_Adjective': wordData['meaningAdjective'] ?? '',
        'Meaning_Adverb': wordData['meaningAdverb'] ?? '',
        'Meaning_Noun': wordData['meaningNoun'] ?? '',
        'Meaning_Preposition': wordData['meaningPreposition'] ?? '',
        'Meaning_Verb': wordData['meaningVerb'] ?? '',
        'Phonetic_Symbols': wordData['phoneticSymbols'] ?? '',
        'Word_Preposition': wordData['wordPreposition'] ?? '',
        'Word_Related': wordData['wordRelated'] ?? '',
        'Word_Verb': wordData['wordVerb'] ?? '',
        'Word_Noun': wordData['wordNoun'] ?? '',
        'Word_Adjective': wordData['wordAdjective'] ?? '',
        'Word_Adverb': wordData['wordAdverb'] ?? '',
        'Word_Synonyms': wordData['wordSynonyms'] ?? '',
        'Word_Antonym': wordData['wordAntonym'] ?? '',
      });

      print('単語 "${wordData['word']}" を登録しました (Word_id: $newWordId)');
    } catch (e) {
      print('単語 "${wordData['word']}" の登録中にエラーが発生しました: $e');
    }
  }
}


