import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> uploadWordsToFirestore() async {
  final firestore = FirebaseFirestore.instance;
  const collectionPath = 'English_Skills/TOEIC/up_to_900/Words/Word';

  // 登録するデータ
  final List<Map<String, dynamic>> wordsData = [
    {
  "word": "lumber",
  "explanation": "「lumber」は名詞としては製材された木材を指し、建築や家具作りなどに用いられます。また、動詞としては「重々しく動く」という意味を持ちますが、日常会話では主に木材の意味で使われます。北米を中心に材木産業で頻繁に登場する単語です。",
  "exampleSentence": "We need more l______ to finish building the cabin.",
  "japaneseTranslation": "キャビンの建築を終えるにはもっと材木が必要です。",
  "meaningNoun": "製材、木材",
  "phoneticSymbols": "/ˈlʌm.bər/",
  "wordSynonyms": "timber, wood, logs",
  "ENG_to_JPN_Answer": "木材",
  "ENG_to_JPN_Answer_A": "木材",
  "ENG_to_JPN_Answer_B": "石材",
  "ENG_to_JPN_Answer_C": "布地",
  "ENG_to_JPN_Answer_D": "装飾品"
},
{
  "word": "reverse",
  "explanation": "「reverse」は動詞として「逆にする」「反対にする」、名詞や形容詞として「逆」「反対」を表す単語です。状況の好転や逆転劇などビジネスや日常会話で幅広く用いられ、車のバックギアなど物理的な動きにも適用されます。",
  "exampleSentence": "He decided to r______ the decision after reconsidering the data.",
  "japaneseTranslation": "データを再検討した後、彼はその決定を覆すことにしました。",
  "meaningVerb": "逆にする、覆す",
  "meaningNoun": "逆、反対",
  "phoneticSymbols": "/rɪˈvɜːrs/",
  "wordSynonyms": "invert, overturn, opposite",
  "ENG_to_JPN_Answer": "逆にする",
  "ENG_to_JPN_Answer_A": "逆にする",
  "ENG_to_JPN_Answer_B": "連携する",
  "ENG_to_JPN_Answer_C": "認可する",
  "ENG_to_JPN_Answer_D": "訴訟する"
},
{
  "word": "voluntary",
  "explanation": "「voluntary」は「自主的な」「任意の」という意味を持つ形容詞で、強制されずに自らの意思で行う行為を表します。ボランティア活動や自主参加型のプログラムなど、相手の好意や意思に基づく場面で頻繁に使われます。",
  "exampleSentence": "Participation in the workshop is v________, not mandatory.",
  "japaneseTranslation": "ワークショップへの参加は任意であり、強制ではありません。",
  "meaningAdjective": "自主的な、任意の",
  "phoneticSymbols": "/ˈvɑːlən.ter.i/",
  "wordSynonyms": "optional, noncompulsory, discretionary",
  "wordAntonym": "mandatory",
  "ENG_to_JPN_Answer": "自主的な",
  "ENG_to_JPN_Answer_A": "自主的な",
  "ENG_to_JPN_Answer_B": "無関係な",
  "ENG_to_JPN_Answer_C": "継続的な",
  "ENG_to_JPN_Answer_D": "懐疑的な"
},
{
  "word": "contractor",
  "explanation": "「contractor」は「請負業者」や「契約業者」を意味する名詞です。建築現場の工事請負やITプロジェクトの外部委託など、契約ベースで仕事を請け負う個人または企業を指します。自社内にはない専門知識や人材を活用する際に重宝される存在です。",
  "exampleSentence": "We hired a c________ to renovate the office space.",
  "japaneseTranslation": "私たちはオフィススペースを改装するために請負業者を雇いました。",
  "meaningNoun": "請負業者",
  "phoneticSymbols": "/ˈkɒn.træk.tər/ (AmE: /ˈkɑːn-/)",
  "wordSynonyms": "subcontractor, freelance worker, provider",
  "ENG_to_JPN_Answer": "請負業者",
  "ENG_to_JPN_Answer_A": "請負業者",
  "ENG_to_JPN_Answer_B": "顧客",
  "ENG_to_JPN_Answer_C": "出資者",
  "ENG_to_JPN_Answer_D": "取締役"
},
{
  "word": "on-site",
  "explanation": "「on-site」は形容詞・副詞として使われ、「現地での」「社内で行われる」という意味を持ちます。会場や職場など、特定の物理的な場所に直接足を運んで行われる活動を表し、オンラインやリモートとは対になる概念です。",
  "exampleSentence": "We provide o_____-s___ technical support for our clients.",
  "japaneseTranslation": "私たちは顧客に対して現地での技術サポートを提供しています。",
  "meaningAdjective": "現地での",
  "phoneticSymbols": "/ˈɒn.saɪt/ (AmE: /ˈɑːn-/)",
  "ENG_to_JPN_Answer": "現地での",
  "ENG_to_JPN_Answer_A": "現地での",
  "ENG_to_JPN_Answer_B": "仮想的な",
  "ENG_to_JPN_Answer_C": "連日の",
  "ENG_to_JPN_Answer_D": "国際的な"
},
{
  "word": "comprehensive",
  "explanation": "「comprehensive」は「包括的な」「総合的な」という意味の形容詞で、あらゆる要素や範囲を広くカバーしている状態を指します。レポートやマニュアル、プランニングなど、内容が細部までしっかり網羅されている場合によく使われる便利な表現です。",
  "exampleSentence": "We conducted a c____________ study on market trends.",
  "japaneseTranslation": "私たちは市場動向に関する包括的な調査を実施しました。",
  "meaningAdjective": "包括的な、広範囲にわたる",
  "phoneticSymbols": "/ˌkɒm.prɪˈhɛn.sɪv/ (AmE: /ˌkɑːm-/)",
  "wordSynonyms": "thorough, complete, extensive",
  "wordAntonym": "partial",
  "ENG_to_JPN_Answer": "包括的な",
  "ENG_to_JPN_Answer_A": "包括的な",
  "ENG_to_JPN_Answer_B": "限定的な",
  "ENG_to_JPN_Answer_C": "幼稚な",
  "ENG_to_JPN_Answer_D": "抽象的な"
},
{
  "word": "confidential",
  "explanation": "「confidential」は「機密の」「秘密の」という意味を持つ形容詞で、情報や文書などの取り扱いにおいて高い秘匿性が求められる場合に用いられます。ビジネスシーンでは契約書や個人情報など、外部へ漏れないよう保護が必要な場面で頻繁に登場します。",
  "exampleSentence": "All c____________ documents must be stored securely.",
  "japaneseTranslation": "すべての機密書類は安全に保管しなければなりません。",
  "meaningAdjective": "機密の、秘密の",
  "phoneticSymbols": "/ˌkɒn.fɪˈden.ʃəl/ (AmE: /ˌkɑːn-/)",
  "wordSynonyms": "secret, private, classified",
  "wordAntonym": "public",
  "ENG_to_JPN_Answer": "機密の",
  "ENG_to_JPN_Answer_A": "機密の",
  "ENG_to_JPN_Answer_B": "曖昧な",
  "ENG_to_JPN_Answer_C": "時間外の",
  "ENG_to_JPN_Answer_D": "不正確な"
},
{
  "word": "expertise",
  "explanation": "「expertise」は「専門知識」「熟練技術」を意味する名詞で、特定の領域で高度なスキルや知識を持つ人が備えている能力を指します。ビジネスや研究の場で信頼を得るための重要な要素であり、チーム編成やアドバイザー選任の際にも重視されます。",
  "exampleSentence": "Her e________ in data analysis helped solve the complex problem.",
  "japaneseTranslation": "データ分析における彼女の専門知識が複雑な問題解決に役立ちました。",
  "meaningNoun": "専門知識、熟練技術",
  "phoneticSymbols": "/ˌek.spɜːˈtiːz/ (AmE: /-spɝː-/)",
  "wordSynonyms": "skill, proficiency, mastery",
  "ENG_to_JPN_Answer": "専門知識",
  "ENG_to_JPN_Answer_A": "専門知識",
  "ENG_to_JPN_Answer_B": "自由時間",
  "ENG_to_JPN_Answer_C": "好奇心",
  "ENG_to_JPN_Answer_D": "消耗品"
},
{
  "word": "souvenir",
  "explanation": "「souvenir」は旅行やイベントなどの記念として持ち帰るおみやげや記念品を指す名詞です。訪れた場所や体験を思い出として残すために購入されることが多く、観光地では多種多様な種類の土産物が販売される重要な収入源となっています。",
  "exampleSentence": "She bought a s________ from the museum gift shop.",
  "japaneseTranslation": "彼女は博物館のギフトショップで記念品を購入しました。",
  "meaningNoun": "おみやげ、記念品",
  "phoneticSymbols": "/ˌsuː.vənˈɪər/ (AmE: /-ˈɪr/)",
  "wordSynonyms": "keepsake, memento, token",
  "ENG_to_JPN_Answer": "おみやげ",
  "ENG_to_JPN_Answer_A": "おみやげ",
  "ENG_to_JPN_Answer_B": "包装紙",
  "ENG_to_JPN_Answer_C": "請求書",
  "ENG_to_JPN_Answer_D": "保証書"
},
{
  "word": "rafting",
  "explanation": "「rafting」は川や急流などで行うラフティングを指す名詞で、ゴムボートなどを用いて下る冒険的なアクティビティとして人気があります。自然やスリルを楽しむスポーツであり、観光地やアウトドアアドベンチャーとして提供されることが多いです。",
  "exampleSentence": "We went r_______ down the river during our vacation.",
  "japaneseTranslation": "休暇中に川でラフティングを楽しみました。",
  "meaningNoun": "ラフティング（川下り）",
  "phoneticSymbols": "/ˈræftɪŋ/",
  "ENG_to_JPN_Answer": "ラフティング",
  "ENG_to_JPN_Answer_A": "ラフティング",
  "ENG_to_JPN_Answer_B": "登山",
  "ENG_to_JPN_Answer_C": "海水浴",
  "ENG_to_JPN_Answer_D": "サイクリング"
},
{
  "word": "compartment",
  "explanation": "「compartment」は仕切られたスペースや区画を指す名詞で、電車の客室、バッグのポケット、収納スペースなど多様な文脈で使われます。整理整頓や機能的な収納を行う際に重要な概念として登場し、セキュリティ面でも注目されます。",
  "exampleSentence": "Keep your valuables in a separate c________ to avoid damage.",
  "japaneseTranslation": "貴重品は別の区画に保管して破損を避けてください。",
  "meaningNoun": "区画、仕切り",
  "phoneticSymbols": "/kəmˈpɑːrt.mənt/",
  "wordSynonyms": "section, division, chamber",
  "ENG_to_JPN_Answer": "区画",
  "ENG_to_JPN_Answer_A": "区画",
  "ENG_to_JPN_Answer_B": "排水口",
  "ENG_to_JPN_Answer_C": "緊急出口",
  "ENG_to_JPN_Answer_D": "予備部品"
},
{
  "word": "fabric",
  "explanation": "「fabric」は衣服やカーテンなどの織物、生地を指す名詞です。綿や麻、合成繊維など、多種多様な素材や柄があり、裁縫やインテリアコーディネートなど幅広い分野で利用されます。耐久性や質感、通気性など、選択時に考慮すべき要素が多い単語です。",
  "exampleSentence": "This f______ is perfect for making summer dresses.",
  "japaneseTranslation": "この生地は夏のドレスを作るのにぴったりです。",
  "meaningNoun": "生地、織物",
  "phoneticSymbols": "/ˈfæb.rɪk/",
  "wordSynonyms": "cloth, textile, material",
  "ENG_to_JPN_Answer": "生地",
  "ENG_to_JPN_Answer_A": "生地",
  "ENG_to_JPN_Answer_B": "設計図",
  "ENG_to_JPN_Answer_C": "染料",
  "ENG_to_JPN_Answer_D": "研磨剤"
},
{
  "word": "spacious",
  "explanation": "「spacious」は「広々とした」「ゆったりとした」という意味の形容詞で、部屋や建物、敷地などが十分な空間を持ち、開放感のある状態を表します。快適さや高級感を演出する要素として、不動産やホテルの広告などでよく使われます。",
  "exampleSentence": "We chose an apartment with a s_______ living room.",
  "japaneseTranslation": "私たちは広々としたリビングルームのあるアパートを選びました。",
  "meaningAdjective": "広々とした",
  "phoneticSymbols": "/ˈspeɪ.ʃəs/",
  "wordSynonyms": "roomy, large, expansive",
  "wordAntonym": "cramped",
  "ENG_to_JPN_Answer": "広々とした",
  "ENG_to_JPN_Answer_A": "広々とした",
  "ENG_to_JPN_Answer_B": "閉鎖的な",
  "ENG_to_JPN_Answer_C": "堅苦しい",
  "ENG_to_JPN_Answer_D": "派手な"
},
{
  "word": "upgrade",
  "explanation": "「upgrade」は動詞として「性能や品質を向上させる」、名詞として「アップグレード版」や「改良」を意味します。ソフトウェアやハードウェアの更新、サービスの上位プランへの変更など、より高いレベルの状態へ移行する際に使われる用語です。",
  "exampleSentence": "We plan to u______ all our computers next quarter.",
  "japaneseTranslation": "来期にはすべてのコンピューターをアップグレードする予定です。",
  "meaningVerb": "アップグレードする、改良する",
  "phoneticSymbols": "/ʌpˈɡreɪd/",
  "wordSynonyms": "improve, update, enhance",
  "wordAntonym": "downgrade",
  "ENG_to_JPN_Answer": "アップグレードする",
  "ENG_to_JPN_Answer_A": "アップグレードする",
  "ENG_to_JPN_Answer_B": "削除する",
  "ENG_to_JPN_Answer_C": "区別する",
  "ENG_to_JPN_Answer_D": "保持する"
},
{
  "word": "showcase",
  "explanation": "「showcase」は名詞として「陳列棚」や「見せ場」を、動詞としては「展示する」「披露する」という意味を持ちます。新製品や才能など、優れた点を多くの人に見せるための機会や場としてビジネスやエンターテインメントの分野で頻繁に使われます。",
  "exampleSentence": "The event aims to s________ local artists and their work.",
  "japaneseTranslation": "そのイベントは地元のアーティストとその作品を披露することを目的としています。",
  "meaningVerb": "披露する、展示する",
  "meaningNoun": "陳列棚、見せ場",
  "phoneticSymbols": "/ˈʃoʊ.keɪs/",
  "wordSynonyms": "display, exhibit, feature",
  "ENG_to_JPN_Answer": "披露する",
  "ENG_to_JPN_Answer_A": "披露する",
  "ENG_to_JPN_Answer_B": "梱包する",
  "ENG_to_JPN_Answer_C": "隠蔽する",
  "ENG_to_JPN_Answer_D": "省略する"
},
{
  "word": "commuter",
  "explanation": "「commuter」は通勤者、特に公共交通機関や自家用車を使って定期的に職場や学校へ通う人を指す名詞です。大都市圏ではラッシュアワーや通勤時間帯と関連して深刻な交通混雑が起きるため、公共政策や都市計画においても重要なキーワードとなっています。",
  "exampleSentence": "Many c________ face long travel times on crowded trains.",
  "japaneseTranslation": "多くの通勤者は混雑した電車で長い移動時間を過ごします。",
  "meaningNoun": "通勤者",
  "phoneticSymbols": "/kəˈmjuː.tər/ (AmE: /-tɚ/)",
  "wordSynonyms": "traveler, daily passenger, suburbanite",
  "ENG_to_JPN_Answer": "通勤者",
  "ENG_to_JPN_Answer_A": "通勤者",
  "ENG_to_JPN_Answer_B": "配達員",
  "ENG_to_JPN_Answer_C": "観光客",
  "ENG_to_JPN_Answer_D": "役員"
},
{
  "word": "enhance",
  "explanation": "「enhance」は「高める」「強化する」という意味を持つ動詞で、品質や機能を向上させたり、印象をより良くする際に用いられます。製品の付加価値を高めたり、スキルを磨くなど、多様な場面で重宝される表現です。",
  "exampleSentence": "We hope to e______ customer satisfaction through better service.",
  "japaneseTranslation": "より良いサービスを通じて顧客満足度を高めたいと考えています。",
  "meaningVerb": "高める、強化する",
  "phoneticSymbols": "/ɪnˈhɑːns/ (AmE: /-ˈhæns/)",
  "wordSynonyms": "improve, boost, augment",
  "wordAntonym": "diminish",
  "ENG_to_JPN_Answer": "高める",
  "ENG_to_JPN_Answer_A": "高める",
  "ENG_to_JPN_Answer_B": "評価する",
  "ENG_to_JPN_Answer_C": "剥奪する",
  "ENG_to_JPN_Answer_D": "遮断する"
},
{
  "word": "freight",
  "explanation": "「freight」は貨物や運送料を指す名詞で、鉄道・船舶・トラックなどを利用して大量の物品を輸送する場合に使われます。物流や輸送業界では欠かせない用語で、国際貿易やサプライチェーンマネジメントにおける重要な要素の一つです。",
  "exampleSentence": "The f______ cost has increased due to rising fuel prices.",
  "japaneseTranslation": "燃料価格の上昇により貨物輸送コストが増加しています。",
  "meaningNoun": "貨物、運送料",
  "phoneticSymbols": "/freɪt/",
  "wordSynonyms": "cargo, shipment, goods",
  "ENG_to_JPN_Answer": "貨物",
  "ENG_to_JPN_Answer_A": "貨物",
  "ENG_to_JPN_Answer_B": "在庫",
  "ENG_to_JPN_Answer_C": "売掛金",
  "ENG_to_JPN_Answer_D": "広告費"
},
{
  "word": "nominate",
  "explanation": "「nominate」は「指名する」「推薦する」という意味の動詞で、役職や賞の候補者として選ぶ際に用いられます。政治やビジネス、エンターテインメントなどさまざまな場面で登場し、正式な選考プロセスの第一段階として重要です。",
  "exampleSentence": "She was n________ for the Employee of the Year award.",
  "japaneseTranslation": "彼女は年間最優秀社員賞にノミネートされました。",
  "meaningVerb": "指名する、推薦する",
  "phoneticSymbols": "/ˈnɒm.ɪ.neɪt/ (AmE: /ˈnɑː.mə-/)",
  "wordSynonyms": "appoint, propose, suggest",
  "ENG_to_JPN_Answer": "指名する",
  "ENG_to_JPN_Answer_A": "指名する",
  "ENG_to_JPN_Answer_B": "辞退する",
  "ENG_to_JPN_Answer_C": "降格する",
  "ENG_to_JPN_Answer_D": "分析する"
},
{
  "word": "discontinued",
  "explanation": "「discontinued」は「生産終了した」「販売中止の」という意味を持つ形容詞で、市場から製品やサービスが撤退、または提供停止となった状態を表します。買い替え時期の目安やサポート期限にも影響が出るため、ユーザーや消費者にとって重要な情報です。",
  "exampleSentence": "This model is d____________, so parts may be hard to find.",
  "japaneseTranslation": "このモデルは生産終了しているため、部品の入手が難しいかもしれません。",
  "meaningAdjective": "生産終了の、販売中止の",
  "phoneticSymbols": "/ˌdɪs.kənˈtɪn.juːd/",
  "wordAntonym": "available",
  "ENG_to_JPN_Answer": "生産終了の",
  "ENG_to_JPN_Answer_A": "生産終了の",
  "ENG_to_JPN_Answer_B": "割引中の",
  "ENG_to_JPN_Answer_C": "革新的な",
  "ENG_to_JPN_Answer_D": "作動中の"
},
{
  "word": "mentoring",
  "explanation": "「mentoring」は「指導」「助言を行うこと」を指す名詞で、経験豊富なメンター（指導者）が後進の人材にアドバイスを与え、スキルや知識を伸ばす取り組みを表します。キャリア形成やリーダーシップ育成の一環として多くの組織で実施されています。",
  "exampleSentence": "The company introduced a m________ program to support new employees.",
  "japaneseTranslation": "その会社は新入社員を支援するためにメンタリングプログラムを導入しました。",
  "meaningNoun": "指導（メンタリング）",
  "phoneticSymbols": "/ˈmen.tɔːr.ɪŋ/",
  "ENG_to_JPN_Answer": "指導",
  "ENG_to_JPN_Answer_A": "指導",
  "ENG_to_JPN_Answer_B": "監視",
  "ENG_to_JPN_Answer_C": "競争",
  "ENG_to_JPN_Answer_D": "遠隔作業"
},
{
  "word": "personalized",
  "explanation": "「personalized」は「個人に合わせた」「カスタマイズされた」という意味の形容詞で、ユーザーごとに異なるニーズや嗜好に対応した商品・サービスを指します。マーケティングやIT分野で特に重要とされ、顧客満足度向上のカギとなる概念です。",
  "exampleSentence": "We offer p________ recommendations based on your purchase history.",
  "japaneseTranslation": "購入履歴に基づいて個人に合わせたおすすめ商品をご提案します。",
  "meaningAdjective": "個別化された、カスタマイズされた",
  "phoneticSymbols": "/ˈpɜː.sən.əl.aɪzd/ (AmE: /ˈpɝː-/)",
  "wordSynonyms": "customized, tailored, individualized",
  "ENG_to_JPN_Answer": "個別化された",
  "ENG_to_JPN_Answer_A": "個別化された",
  "ENG_to_JPN_Answer_B": "普遍的な",
  "ENG_to_JPN_Answer_C": "低品質な",
  "ENG_to_JPN_Answer_D": "過度に高価な"
},
{
  "word": "pharmacy",
  "explanation": "「pharmacy」は薬局や調剤を行う場所を意味する名詞です。薬剤師が処方箋に従って医薬品を提供するほか、市販薬や医療用品を扱う店舗としても機能します。健康管理の一環として、地域住民や患者にとって欠かせないサービスを担います。",
  "exampleSentence": "You can pick up your prescription at the nearest p_______.",
  "japaneseTranslation": "最寄りの薬局で処方箋を受け取れます。",
  "meaningNoun": "薬局、調剤",
  "phoneticSymbols": "/ˈfɑː.mə.si/ (AmE: /ˈfɑːr-/)",
  "wordSynonyms": "drugstore, chemist's (BrE), dispensary",
  "ENG_to_JPN_Answer": "薬局",
  "ENG_to_JPN_Answer_A": "薬局",
  "ENG_to_JPN_Answer_B": "事務所",
  "ENG_to_JPN_Answer_C": "ギャラリー",
  "ENG_to_JPN_Answer_D": "試着室"
},
{
  "word": "excerpt",
  "explanation": "「excerpt」は書物や記事、音楽などから抜粋した一部分を指す名詞、または「抜粋する」という動詞です。要点や重要箇所を引用して紹介する際に使われ、学術的な引用や書評、メディアのプレビューなど、さまざまなシーンで活用されます。",
  "exampleSentence": "The article included an e______ from her latest book.",
  "japaneseTranslation": "その記事には彼女の最新著書からの抜粋が含まれていました。",
  "meaningNoun": "抜粋、引用",
  "phoneticSymbols": "/ˈek.sɜːpt/ (AmE: /-sɝːpt/)",
  "wordSynonyms": "passage, extract, quotation",
  "ENG_to_JPN_Answer": "抜粋",
  "ENG_to_JPN_Answer_A": "抜粋",
  "ENG_to_JPN_Answer_B": "推測",
  "ENG_to_JPN_Answer_C": "未定稿",
  "ENG_to_JPN_Answer_D": "複写"
},
{
  "word": "publicize",
  "explanation": "「publicize」は「宣伝する」「公表する」という意味を持つ動詞で、製品やサービス、情報などを広く世間に伝える際に使われます。広報活動やマーケティング戦略の一環として、多様なメディアを通じて認知度を高めるために用いられる表現です。",
  "exampleSentence": "We plan to p________ our new product via social media and press releases.",
  "japaneseTranslation": "新製品をSNSやプレスリリースを通じて宣伝する予定です。",
  "meaningVerb": "宣伝する、公表する",
  "phoneticSymbols": "/ˈpʌb.lɪ.saɪz/ (AmE: /-lɪ.sɑɪz/)",
  "wordSynonyms": "promote, advertise, make known",
  "ENG_to_JPN_Answer": "宣伝する",
  "ENG_to_JPN_Answer_A": "宣伝する",
  "ENG_to_JPN_Answer_B": "躊躇する",
  "ENG_to_JPN_Answer_C": "破棄する",
  "ENG_to_JPN_Answer_D": "密閉する"
},
{
  "word": "tuition",
  "explanation": "「tuition」は大学や専門学校などでの「授業料」、または個人的な「指導・教授」を指す名詞です。教育費としての意味が一般的ですが、家庭教師などのマンツーマンレッスンに対しても用いられます。学費負担が大きい国では社会問題にもなります。",
  "exampleSentence": "The t_______ fees at this university are quite high.",
  "japaneseTranslation": "この大学の授業料はかなり高額です。",
  "meaningNoun": "授業料、指導",
  "phoneticSymbols": "/tʃuːˈɪʃ.ən/",
  "ENG_to_JPN_Answer": "授業料",
  "ENG_to_JPN_Answer_A": "授業料",
  "ENG_to_JPN_Answer_B": "寄付金",
  "ENG_to_JPN_Answer_C": "交換留学",
  "ENG_to_JPN_Answer_D": "奨学金"
},
{
  "word": "compliance",
  "explanation": "「compliance」は「順守」「従うこと」を意味する名詞で、法律や規制、社内規定などに違反せず、正しく従う状態を指します。企業のコンプライアンスはリスク管理や企業倫理の観点から非常に重視される領域です。",
  "exampleSentence": "The company invests heavily in c________ training for employees.",
  "japaneseTranslation": "その会社は従業員向けのコンプライアンス研修に多額の投資を行っています。",
  "meaningNoun": "遵守、従うこと",
  "phoneticSymbols": "/kəmˈplaɪ.əns/",
  "ENG_to_JPN_Answer": "遵守",
  "ENG_to_JPN_Answer_A": "遵守",
  "ENG_to_JPN_Answer_B": "抵抗",
  "ENG_to_JPN_Answer_C": "大量生産",
  "ENG_to_JPN_Answer_D": "誤情報"
},
{
  "word": "clarify",
  "explanation": "「clarify」は「明確にする」「はっきりさせる」という意味の動詞です。疑問点や混乱を解消するために情報を整理し、分かりやすい形にする際によく使われます。ビジネスや学術分野でもコミュニケーションを円滑に進めるために重要なプロセスです。",
  "exampleSentence": "Could you c______ the terms of the agreement, please?",
  "japaneseTranslation": "契約条件をはっきりさせていただけますか？",
  "meaningVerb": "明確にする、解明する",
  "phoneticSymbols": "/ˈklær.ɪ.faɪ/",
  "wordSynonyms": "explain, elucidate, simplify",
  "wordAntonym": "obscure",
  "ENG_to_JPN_Answer": "明確にする",
  "ENG_to_JPN_Answer_A": "明確にする",
  "ENG_to_JPN_Answer_B": "無視する",
  "ENG_to_JPN_Answer_C": "反証する",
  "ENG_to_JPN_Answer_D": "除去する"
},
{
  "word": "municipal",
  "explanation": "「municipal」は「市の」「地方自治の」という意味を持つ形容詞で、市区町村など地方自治体が関与する業務や施設などを表します。公園や図書館、公共事業など、地域住民の生活を支える多様なサービスに関係し、政治や行政の文脈で頻繁に使われます。",
  "exampleSentence": "The m________ government announced a new recycling program.",
  "japaneseTranslation": "市政府は新しいリサイクルプログラムを発表しました。",
  "meaningAdjective": "市の、地方自治の",
  "phoneticSymbols": "/mjuːˈnɪs.ɪ.pəl/",
  "ENG_to_JPN_Answer": "市の",
  "ENG_to_JPN_Answer_A": "市の",
  "ENG_to_JPN_Answer_B": "国際的な",
  "ENG_to_JPN_Answer_C": "私営の",
  "ENG_to_JPN_Answer_D": "違法な"
},
{
  "word": "respectively",
  "explanation": "「respectively」は「それぞれ」「順番に」という意味の副詞で、前述の複数の対象に対応する結果や属性を順序通りに示す際に用いられます。学術論文やビジネスレポートなど、データや統計を整理して提示する場合に重宝される表現です。",
  "exampleSentence": "The sales of product A and B grew by 10% and 15%, r_________.",
  "japaneseTranslation": "製品AとBの売上はそれぞれ10%と15%増加しました。",
  "meaningAdverb": "それぞれ、順番に",
  "phoneticSymbols": "/rɪˈspek.tɪv.li/",
  "ENG_to_JPN_Answer": "それぞれ",
  "ENG_to_JPN_Answer_A": "それぞれ",
  "ENG_to_JPN_Answer_B": "同時に",
  "ENG_to_JPN_Answer_C": "対照的に",
  "ENG_to_JPN_Answer_D": "何度も"
},
{
  "word": "durable",
  "explanation": "「durable」は「耐久性のある」「長持ちする」という意味の形容詞で、製品や素材が長期間にわたって損耗しにくい特性を示します。家具や家電、建材など、品質を評価する基準として重要視される要素の一つです。",
  "exampleSentence": "We need d______ materials for this outdoor project.",
  "japaneseTranslation": "この屋外プロジェクトには耐久性のある素材が必要です。",
  "meaningAdjective": "耐久性のある、長持ちする",
  "phoneticSymbols": "/ˈdʊr.ə.bəl/ (AmE: /ˈdjʊr-/)",
  "wordSynonyms": "long-lasting, sturdy, tough",
  "wordAntonym": "fragile",
  "ENG_to_JPN_Answer": "耐久性のある",
  "ENG_to_JPN_Answer_A": "耐久性のある",
  "ENG_to_JPN_Answer_B": "奇抜な",
  "ENG_to_JPN_Answer_C": "脆弱な",
  "ENG_to_JPN_Answer_D": "多機能な"
},
{
  "word": "landmark",
  "explanation": "「landmark」は名詞としては「目印」や「画期的な出来事」を指し、建物や自然物など周囲の景観と比較して特徴的な存在を示す際に使われます。転じて、歴史的に重要な事件や出来事を表すこともあり、観光ガイドやニュースでもよく登場します。",
  "exampleSentence": "The Statue of Liberty is a famous l_______ in New York City.",
  "japaneseTranslation": "自由の女神像はニューヨーク市の有名なランドマークです。",
  "meaningNoun": "目印、画期的な出来事",
  "phoneticSymbols": "/ˈlænd.mɑːrk/ (AmE: /-mɑːrk/)",
  "ENG_to_JPN_Answer": "目印",
  "ENG_to_JPN_Answer_A": "目印",
  "ENG_to_JPN_Answer_B": "論文",
  "ENG_to_JPN_Answer_C": "政令",
  "ENG_to_JPN_Answer_D": "災害"
},
{
  "word": "prototype",
  "explanation": "「prototype」は「試作品」「原型」として設計・製造されるものを指す名詞で、本格的な量産や正式導入の前に性能や機能を検証する目的で作られます。ハードウェアからソフトウェアまで幅広い分野で開発プロセスの重要ステップとなっています。",
  "exampleSentence": "They built a p_________ of the new smartphone for testing.",
  "japaneseTranslation": "新型スマートフォンの試作品を作成しテストを行いました。",
  "meaningNoun": "試作品、原型",
  "phoneticSymbols": "/ˈprəʊ.tə.taɪp/ (AmE: /ˈproʊ-/)",
  "wordSynonyms": "model, sample, pilot",
  "ENG_to_JPN_Answer": "試作品",
  "ENG_to_JPN_Answer_A": "試作品",
  "ENG_to_JPN_Answer_B": "特許",
  "ENG_to_JPN_Answer_C": "既製品",
  "ENG_to_JPN_Answer_D": "取扱説明書"
},
{
  "word": "transit",
  "explanation": "「transit」は名詞としては「輸送」「通過」、動詞としては「通過する」という意味を持ち、主に公共交通機関や国際輸送などの文脈で使われます。空港のトランジットや都市の公共交通システムなど、移動や運搬に関わる広範な概念を含みます。",
  "exampleSentence": "The city’s public t______ system is being upgraded to reduce congestion.",
  "japaneseTranslation": "交通渋滞を緩和するために市の公共輸送システムがアップグレードされています。",
  "meaningNoun": "輸送、通過",
  "phoneticSymbols": "/ˈtræn.zɪt/ (AmE: /-sɪt/)",
  "ENG_to_JPN_Answer": "輸送",
  "ENG_to_JPN_Answer_A": "輸送",
  "ENG_to_JPN_Answer_B": "倉庫管理",
  "ENG_to_JPN_Answer_C": "建設計画",
  "ENG_to_JPN_Answer_D": "保険補償"
},
{
  "word": "verify",
  "explanation": "「verify」は「検証する」「確かめる」という意味の動詞で、情報や事実が正しいかどうかを確認する行為を指します。システム開発、品質管理、報道など、正確性が重視されるあらゆる分野で欠かせないプロセスです。",
  "exampleSentence": "Please v_____ your email address before accessing the account.",
  "japaneseTranslation": "アカウントにアクセスする前にメールアドレスを確認してください。",
  "meaningVerb": "検証する、確認する",
  "phoneticSymbols": "/ˈver.ɪ.faɪ/",
  "wordSynonyms": "check, confirm, validate",
  "wordAntonym": "neglect",
  "ENG_to_JPN_Answer": "検証する",
  "ENG_to_JPN_Answer_A": "検証する",
  "ENG_to_JPN_Answer_B": "削除する",
  "ENG_to_JPN_Answer_C": "推察する",
  "ENG_to_JPN_Answer_D": "分散させる"
},
{
  "word": "managerial",
  "explanation": "「managerial」は「管理職の」「経営に関する」という意味の形容詞で、マネージャーや経営陣の役割や責任に関連する場合に用いられます。組織運営やリーダーシップ、意思決定の場面で頻繁に使われ、経営学でも重要な概念です。",
  "exampleSentence": "She took a m________ role overseeing multiple departments.",
  "japaneseTranslation": "彼女は複数の部署を監督する管理職の役割を担いました。",
  "meaningAdjective": "管理職の、経営に関する",
  "phoneticSymbols": "/ˌmæn.ɪˈdʒɪə.ri.əl/ (AmE: /-ˈdʒɪr.i-/)",
  "ENG_to_JPN_Answer": "管理職の",
  "ENG_to_JPN_Answer_A": "管理職の",
  "ENG_to_JPN_Answer_B": "運搬用の",
  "ENG_to_JPN_Answer_C": "大衆的な",
  "ENG_to_JPN_Answer_D": "自発的な"
},
{
  "word": "culinary",
  "explanation": "「culinary」は「料理の」「食事の」という意味の形容詞で、主に料理や食に関連する文脈で使われます。料理学校（culinary school）や料理芸術（culinary arts）などの表現でもよく登場し、美食文化や調理技術を指す場合に重宝されます。",
  "exampleSentence": "She studied c________ arts in Paris.",
  "japaneseTranslation": "彼女はパリで料理芸術を学びました。",
  "meaningAdjective": "料理の、食事に関する",
  "phoneticSymbols": "/ˈkʌl.ɪ.nər.i/ (AmE: /ˈkuː.lɪ.ner.i/)",
  "ENG_to_JPN_Answer": "料理の",
  "ENG_to_JPN_Answer_A": "料理の",
  "ENG_to_JPN_Answer_B": "芸術的な",
  "ENG_to_JPN_Answer_C": "教育的な",
  "ENG_to_JPN_Answer_D": "実験的な"
},
{
  "word": "attire",
  "explanation": "「attire」は「服装」「衣装」を指す名詞で、フォーマルな場面やドレスコードに関する文脈でよく使われます。ビジネスアタイアやカジュアルアタイアなど、TPOに応じた服装選びの重要性を示す単語として重宝されています。",
  "exampleSentence": "Please wear formal a______ for the award ceremony.",
  "japaneseTranslation": "表彰式にはフォーマルな服装を身につけてください。",
  "meaningNoun": "服装、衣装",
  "phoneticSymbols": "/əˈtaɪər/",
  "wordSynonyms": "clothing, garments, outfit",
  "ENG_to_JPN_Answer": "服装",
  "ENG_to_JPN_Answer_A": "服装",
  "ENG_to_JPN_Answer_B": "礼儀",
  "ENG_to_JPN_Answer_C": "社交術",
  "ENG_to_JPN_Answer_D": "携帯品"
},
{
  "word": "reimburse",
  "explanation": "「reimburse」は「払い戻す」「返済する」という意味の動詞で、立替払いをした費用などを後から補填する場合に使われます。出張経費や医療費の返金処理など、経理や保険などの手続きで頻繁に登場する重要な表現です。",
  "exampleSentence": "The company will r________ travel expenses for the conference.",
  "japaneseTranslation": "会社はカンファレンスでかかった交通費を払い戻してくれます。",
  "meaningVerb": "払い戻す、返済する",
  "phoneticSymbols": "/ˌriː.ɪmˈbɝːs/",
  "wordSynonyms": "refund, compensate, pay back",
  "ENG_to_JPN_Answer": "払い戻す",
  "ENG_to_JPN_Answer_A": "払い戻す",
  "ENG_to_JPN_Answer_B": "請求する",
  "ENG_to_JPN_Answer_C": "節約する",
  "ENG_to_JPN_Answer_D": "先延ばしにする"
},
{
  "word": "courteous",
  "explanation": "「courteous」は「礼儀正しい」「丁寧な」という意味を持つ形容詞で、相手に対して配慮や敬意を示す態度を表します。接客業やビジネスの場面では非常に重視され、顧客満足度や信頼関係の構築において重要な要素です。",
  "exampleSentence": "The staff was extremely c________ and helpful.",
  "japaneseTranslation": "スタッフは非常に礼儀正しく、親切でした。",
  "meaningAdjective": "礼儀正しい、丁寧な",
  "phoneticSymbols": "/ˈkɝː.t̬i.əs/ (BrE: /ˈkɜː.ti.əs/)",
  "wordSynonyms": "polite, respectful, well-mannered",
  "wordAntonym": "rude",
  "ENG_to_JPN_Answer": "礼儀正しい",
  "ENG_to_JPN_Answer_A": "礼儀正しい",
  "ENG_to_JPN_Answer_B": "儀式的な",
  "ENG_to_JPN_Answer_C": "強制的な",
  "ENG_to_JPN_Answer_D": "曖昧な"
},
{
  "word": "furnished",
  "explanation": "「furnished」は主に不動産やホテルの部屋などが「家具付きの」「備え付けの調度品がある」という意味の形容詞です。部屋を借りる際にベッドやソファなどが最初から設置されている場合に用いられ、入居者にとっては引っ越し時の手間を減らすメリットがあります。",
  "exampleSentence": "The apartment is fully f________ and ready to move in.",
  "japaneseTranslation": "そのアパートは完全に家具付きで、すぐに入居できます。",
  "meaningAdjective": "家具付きの",
  "phoneticSymbols": "/ˈfɝː.nɪʃt/ (BrE: /ˈfɜː.nɪʃt/)",
  "ENG_to_JPN_Answer": "家具付きの",
  "ENG_to_JPN_Answer_A": "家具付きの",
  "ENG_to_JPN_Answer_B": "改装中の",
  "ENG_to_JPN_Answer_C": "防音処理の",
  "ENG_to_JPN_Answer_D": "隔離された"
},
{
  "word": "knowledgeable",
  "explanation": "「knowledgeable」は「知識が豊富な」「物知りな」という意味の形容詞で、特定の分野や全般的に深い理解や情報を持つ人を評価する際に用いられます。業務での専門性や学術面での博識など、多様なシーンで使われる称賛の言葉です。",
  "exampleSentence": "He is very k________ about the latest technology trends.",
  "japaneseTranslation": "彼は最新の技術動向にとても詳しいです。",
  "meaningAdjective": "知識豊富な、博識な",
  "phoneticSymbols": "/ˈnɒl.ɪ.dʒə.bəl/ (AmE: /ˈnɑː.lɪ-/)",
  "wordSynonyms": "informed, well-versed, educated",
  "wordAntonym": "uninformed",
  "ENG_to_JPN_Answer": "知識豊富な",
  "ENG_to_JPN_Answer_A": "知識豊富な",
  "ENG_to_JPN_Answer_B": "偏見のある",
  "ENG_to_JPN_Answer_C": "衝動的な",
  "ENG_to_JPN_Answer_D": "無責任な"
},
{
  "word": "craftspeople",
  "explanation": "「craftspeople」は職人や工芸家など、手作業による技能を持つ人々を指す名詞の複数形です。伝統的な手工業から現代アートまで、熟練の技で質の高い作品を生み出す人々を総称し、地域文化や産業の担い手として重要な役割を果たします。",
  "exampleSentence": "Local c________ create handmade pottery and textiles.",
  "japaneseTranslation": "地元の職人たちは手作りの陶器や織物を制作しています。",
  "meaningNoun": "職人、工芸家（の複数形）",
  "phoneticSymbols": "/ˈkræftsˌpiːpl/",
  "ENG_to_JPN_Answer": "職人たち",
  "ENG_to_JPN_Answer_A": "職人たち",
  "ENG_to_JPN_Answer_B": "投資家たち",
  "ENG_to_JPN_Answer_C": "科学者たち",
  "ENG_to_JPN_Answer_D": "建築家たち"
},
{
  "word": "delete",
  "explanation": "「delete」は「削除する」「消去する」を意味する動詞で、主にデジタルデータやテキストなどを対象に用いられます。パソコンやスマートフォンの操作でファイルや文章を取り除くときに使われるなど、日常的にも頻繁に登場する表現です。",
  "exampleSentence": "Make sure to d______ any sensitive information from the report.",
  "japaneseTranslation": "報告書から機密情報を削除することを忘れないでください。",
  "meaningVerb": "削除する、消去する",
  "phoneticSymbols": "/dɪˈliːt/",
  "wordSynonyms": "remove, erase, discard",
  "wordAntonym": "retain",
  "ENG_to_JPN_Answer": "削除する",
  "ENG_to_JPN_Answer_A": "削除する",
  "ENG_to_JPN_Answer_B": "強化する",
  "ENG_to_JPN_Answer_C": "複合する",
  "ENG_to_JPN_Answer_D": "命名する"
},
{
  "word": "emerging",
  "explanation": "「emerging」は「新興の」「現れつつある」という意味の形容詞で、特に新興市場や新たな技術、産業などが台頭してきている場面で多用されます。世界経済やトレンドの分析で登場し、今後の可能性や成長が期待される領域を示す表現です。",
  "exampleSentence": "We are expanding our business in e________ markets overseas.",
  "japaneseTranslation": "私たちは海外の新興市場で事業を拡大しています。",
  "meaningAdjective": "新興の、現れつつある",
  "phoneticSymbols": "/ɪˈmɜː.dʒɪŋ/ (AmE: /-ˈmɝː-/)",
  "wordSynonyms": "developing, arising, up-and-coming",
  "ENG_to_JPN_Answer": "新興の",
  "ENG_to_JPN_Answer_A": "新興の",
  "ENG_to_JPN_Answer_B": "停滞した",
  "ENG_to_JPN_Answer_C": "歴史的な",
  "ENG_to_JPN_Answer_D": "限定的な"
},
{
  "word": "enroll",
  "explanation": "「enroll」は「登録する」「入学する」「加入する」という意味の動詞で、学校や講座、サービスなどに正式に参加・受け入れられる場合に用いられます。入学手続きや会員登録など多様なシーンで一般的に使われる表現です。",
  "exampleSentence": "You can e_____ in the course online through our website.",
  "japaneseTranslation": "コースには弊社ウェブサイトを通じてオンラインで登録できます。",
  "meaningVerb": "登録する、入学する",
  "phoneticSymbols": "/ɪnˈroʊl/",
  "wordSynonyms": "register, sign up, join",
  "wordAntonym": "withdraw",
  "ENG_to_JPN_Answer": "登録する",
  "ENG_to_JPN_Answer_A": "登録する",
  "ENG_to_JPN_Answer_B": "延期する",
  "ENG_to_JPN_Answer_C": "批判する",
  "ENG_to_JPN_Answer_D": "護送する"
},
{
  "word": "proficiency",
  "explanation": "「proficiency」は「熟達」「習熟度」を意味する名詞で、言語や技能などをどの程度うまくこなせるかを示す指標として使われます。英語力やプログラミングスキルなど、客観的に測定・評価される場面でよく登場します。",
  "exampleSentence": "Her p_________ in multiple languages is a major asset.",
  "japaneseTranslation": "複数言語における彼女の高い熟達度は大きな強みです。",
  "meaningNoun": "熟達、習熟度",
  "phoneticSymbols": "/prəˈfɪʃ.ən.si/",
  "wordSynonyms": "skill, competence, ability",
  "ENG_to_JPN_Answer": "熟達",
  "ENG_to_JPN_Answer_A": "熟達",
  "ENG_to_JPN_Answer_B": "不審",
  "ENG_to_JPN_Answer_C": "欠落",
  "ENG_to_JPN_Answer_D": "過剰"
},
{
  "word": "scenic",
  "explanation": "「scenic」は「景色の良い」「眺めの美しい」という意味の形容詞で、自然や観光地など、眺望が特に魅力的な場所を示す際に使われます。美しい風景やルートを紹介する場合、旅行ガイドや広告でよく登場する表現です。",
  "exampleSentence": "This s______ route offers breathtaking mountain views.",
  "japaneseTranslation": "この景色の良いルートでは息をのむような山の景色が楽しめます。",
  "meaningAdjective": "景色の良い",
  "phoneticSymbols": "/ˈsiː.nɪk/",
  "wordSynonyms": "picturesque, beautiful, panoramic",
  "wordAntonym": "unattractive",
  "ENG_to_JPN_Answer": "景色の良い",
  "ENG_to_JPN_Answer_A": "景色の良い",
  "ENG_to_JPN_Answer_B": "危険な",
  "ENG_to_JPN_Answer_C": "密閉された",
  "ENG_to_JPN_Answer_D": "不明瞭な"
},
{
  "word": "cuisine",
  "explanation": "「cuisine」は特定の地域や国、文化に根ざした料理スタイルを指す名詞です。素材の選び方や調理法、味付けなど独自の特徴が表れるため、グルメ情報や旅行ガイドなどで頻繁に登場する重要なキーワードです。",
  "exampleSentence": "Italian c______ is popular worldwide for its pasta and pizza.",
  "japaneseTranslation": "イタリア料理はパスタやピザで世界的に人気があります。",
  "meaningNoun": "料理（特定地域・文化の）",
  "phoneticSymbols": "/kwɪˈziːn/",
  "wordSynonyms": "food, cooking style, gastronomy",
  "ENG_to_JPN_Answer": "料理",
  "ENG_to_JPN_Answer_A": "料理",
  "ENG_to_JPN_Answer_B": "器具",
  "ENG_to_JPN_Answer_C": "書籍",
  "ENG_to_JPN_Answer_D": "飲料"
},
{
  "word": "acclaimed",
  "explanation": "「acclaimed」は批評家や世間から高く評価されている、称賛を受けていることを表す形容詞です。映画や本、アーティストなどが優れた作品・成果を通じて名声を得た場合などに使われ、賞や口コミで高い評判がある状態を示します。",
  "exampleSentence": "Her a________ novel won several literary awards.",
  "japaneseTranslation": "彼女の高く評価された小説は複数の文学賞を受賞しました。",
  "meaningAdjective": "高く評価された、称賛された",
  "phoneticSymbols": "/əˈkleɪmd/",
  "wordSynonyms": "praised, celebrated, renowned",
  "ENG_to_JPN_Answer": "高く評価された",
  "ENG_to_JPN_Answer_A": "高く評価された",
  "ENG_to_JPN_Answer_B": "埋もれた",
  "ENG_to_JPN_Answer_C": "急進的な",
  "ENG_to_JPN_Answer_D": "不明瞭な"
},
{
  "word": "certified",
  "explanation": "「certified」は「公認の」「資格のある」という意味の形容詞で、特定の技能や条件を満たして正式な証明を受けた人や製品を指します。職業資格や品質保証など、信頼性や専門性を示したい時に使われる表現です。",
  "exampleSentence": "He is a c________ translator with years of experience.",
  "japaneseTranslation": "彼は何年もの経験を持つ公認翻訳者です。",
  "meaningAdjective": "公認の、証明された",
  "phoneticSymbols": "/ˈsɜː.tɪ.faɪd/ (AmE: /ˈsɝː-/)",
  "wordSynonyms": "accredited, licensed, qualified",
  "ENG_to_JPN_Answer": "公認の",
  "ENG_to_JPN_Answer_A": "公認の",
  "ENG_to_JPN_Answer_B": "見習いの",
  "ENG_to_JPN_Answer_C": "臨時の",
  "ENG_to_JPN_Answer_D": "違法な"
},
{
  "word": "medication",
  "explanation": "「medication」は病気や症状を緩和するための薬剤や治療薬を指す名詞で、処方薬や市販薬など幅広く含みます。医療現場や薬局での会話で頻出し、正しい服用方法や副作用の注意が重要視される用語です。",
  "exampleSentence": "Please take this m________ twice a day after meals.",
  "japaneseTranslation": "この薬を1日2回、食後に服用してください。",
  "meaningNoun": "薬剤、投薬",
  "phoneticSymbols": "/ˌmed.ɪˈkeɪ.ʃən/",
  "wordSynonyms": "medicine, drug, treatment",
  "ENG_to_JPN_Answer": "薬",
  "ENG_to_JPN_Answer_A": "薬",
  "ENG_to_JPN_Answer_B": "注射器",
  "ENG_to_JPN_Answer_C": "手術",
  "ENG_to_JPN_Answer_D": "包帯"
},
{
  "word": "overview",
  "explanation": "「overview」は「概要」「概観」を示す名詞で、プロジェクトやレポート、システムなどの全体像を把握したいときに使われます。詳細に踏み込む前に主要ポイントを整理・理解するために役立つ表現としてビジネスや学術の場で頻繁に登場します。",
  "exampleSentence": "The first chapter provides an o_______ of the entire project.",
  "japaneseTranslation": "第一章ではプロジェクト全体の概要が示されています。",
  "meaningNoun": "概要、概観",
  "phoneticSymbols": "/ˈoʊ.vɚ.vjuː/",
  "wordSynonyms": "summary, outline, synopsis",
  "ENG_to_JPN_Answer": "概要",
  "ENG_to_JPN_Answer_A": "概要",
  "ENG_to_JPN_Answer_B": "矛盾",
  "ENG_to_JPN_Answer_C": "補論",
  "ENG_to_JPN_Answer_D": "質問"
},
{
  "word": "resistant",
  "explanation": "「resistant」は「耐性のある」「抵抗力のある」という意味の形容詞で、特定の環境や物質、影響に対して影響を受けにくい状態を指します。防水や耐久、化学物質への耐性など、製品仕様や医学領域でも重要な概念としてよく使われます。",
  "exampleSentence": "These materials are r________ to extreme temperatures.",
  "japaneseTranslation": "これらの素材は極端な温度に対して耐性があります。",
  "meaningAdjective": "耐性のある、抵抗力のある",
  "phoneticSymbols": "/rɪˈzɪs.tənt/",
  "wordSynonyms": "immune, impervious, proof",
  "wordAntonym": "vulnerable",
  "ENG_to_JPN_Answer": "耐性のある",
  "ENG_to_JPN_Answer_A": "耐性のある",
  "ENG_to_JPN_Answer_B": "連鎖的な",
  "ENG_to_JPN_Answer_C": "散逸した",
  "ENG_to_JPN_Answer_D": "安価な"
},
{
  "word": "superb",
  "explanation": "「superb」は「素晴らしい」「最高の」という意味を持つ形容詞で、品質やパフォーマンスが非常に優れていることを表します。食品やサービス、景色など、さまざまなものに対して使われ、賞賛の気持ちを強く表す際に便利な単語です。",
  "exampleSentence": "The hotel provided s_____ service throughout our stay.",
  "japaneseTranslation": "ホテルは滞在中、素晴らしいサービスを提供してくれました。",
  "meaningAdjective": "素晴らしい、最高の",
  "phoneticSymbols": "/suːˈpɜːb/ (AmE: /-ˈpɝːb/)",
  "wordSynonyms": "excellent, outstanding, marvelous",
  "ENG_to_JPN_Answer": "素晴らしい",
  "ENG_to_JPN_Answer_A": "素晴らしい",
  "ENG_to_JPN_Answer_B": "大がかりな",
  "ENG_to_JPN_Answer_C": "平均的な",
  "ENG_to_JPN_Answer_D": "残念な"
},
{
  "word": "array",
  "explanation": "「array」は「配列」「多彩な並び」を意味する名詞で、同質または類似する要素が整然と並んだ状態を表します。プログラミングにおけるデータ構造を指す場合や、商品ラインアップを指す際など、多様な場面で使用される表現です。",
  "exampleSentence": "We offer an a____ of products to meet various needs.",
  "japaneseTranslation": "私たちは多彩なニーズに応えるため、様々な製品を取り揃えています。",
  "meaningNoun": "配列、多彩な並び",
  "phoneticSymbols": "/əˈreɪ/",
  "wordSynonyms": "range, collection, lineup",
  "ENG_to_JPN_Answer": "配列",
  "ENG_to_JPN_Answer_A": "配列",
  "ENG_to_JPN_Answer_B": "不良在庫",
  "ENG_to_JPN_Answer_C": "顧客名簿",
  "ENG_to_JPN_Answer_D": "経費伝票"
},
{
  "word": "informative",
  "explanation": "「informative」は「情報が豊富な」「有益な」という意味の形容詞で、読み手や聞き手に対して多くの知識や役立つデータを提供する場合に使われます。プレゼンテーションや記事、セミナーなどで内容が充実しているときに評価の言葉として用いられます。",
  "exampleSentence": "The workshop was highly i________, covering a wide range of topics.",
  "japaneseTranslation": "そのワークショップは非常に有益で、幅広いトピックをカバーしていました。",
  "meaningAdjective": "有益な、情報豊富な",
  "phoneticSymbols": "/ɪnˈfɔː.mə.tɪv/ (AmE: /-ˈfɔːr-/)",
  "wordSynonyms": "educational, enlightening, instructive",
  "wordAntonym": "unhelpful",
  "ENG_to_JPN_Answer": "有益な",
  "ENG_to_JPN_Answer_A": "有益な",
  "ENG_to_JPN_Answer_B": "偏った",
  "ENG_to_JPN_Answer_C": "騒がしい",
  "ENG_to_JPN_Answer_D": "過度に難解な"
},
{
  "word": "nationwide",
  "explanation": "「nationwide」は「全国的に」「全国規模の」という意味を持つ形容詞・副詞で、国全体を対象または範囲とする状況を指します。製品展開、キャンペーン、調査などが全国的に行われる場合によく使われる表現です。",
  "exampleSentence": "The company launched a n________ marketing campaign.",
  "japaneseTranslation": "その会社は全国規模のマーケティングキャンペーンを開始しました。",
  "meaningAdjective": "全国規模の",
  "phoneticSymbols": "/ˌneɪ.ʃənˈwaɪd/",
  "ENG_to_JPN_Answer": "全国規模の",
  "ENG_to_JPN_Answer_A": "全国規模の",
  "ENG_to_JPN_Answer_B": "地域限定の",
  "ENG_to_JPN_Answer_C": "国際的な",
  "ENG_to_JPN_Answer_D": "不十分な"
},
{
  "word": "outdated",
  "explanation": "「outdated」は「時代遅れの」「古くなった」という意味を持つ形容詞で、情報や技術、デザインなどが最新のものと比較して遅れている状態を表します。アップデートやリニューアルが必要な場合を示唆する際に用いられる表現です。",
  "exampleSentence": "The software is o________ and needs an immediate upgrade.",
  "japaneseTranslation": "そのソフトウェアは時代遅れなので、早急にアップグレードが必要です。",
  "meaningAdjective": "古い、時代遅れの",
  "phoneticSymbols": "/ˌaʊtˈdeɪ.tɪd/",
  "wordSynonyms": "obsolete, old-fashioned, archaic",
  "ENG_to_JPN_Answer": "古い",
  "ENG_to_JPN_Answer_A": "古い",
  "ENG_to_JPN_Answer_B": "高速な",
  "ENG_to_JPN_Answer_C": "強力な",
  "ENG_to_JPN_Answer_D": "正確な"
},
{
  "word": "shareholder",
  "explanation": "「shareholder」は企業の株を所有する株主を指す名詞です。会社の業績や経営方針に対して利害関係を持つ立場で、配当金や議決権を通じて企業運営に関わる重要なステークホルダーとして扱われます。",
  "exampleSentence": "S__________ are entitled to vote on major company decisions.",
  "japaneseTranslation": "株主には会社の主要な決定に投票する権利があります。",
  "meaningNoun": "株主",
  "phoneticSymbols": "/ˈʃeərˌhəʊl.dər/ (AmE: /ˈʃerˌhoʊl.dɚ/)",
  "wordSynonyms": "stockholder, investor, stakeholder",
  "ENG_to_JPN_Answer": "株主",
  "ENG_to_JPN_Answer_A": "株主",
  "ENG_to_JPN_Answer_B": "貸借人",
  "ENG_to_JPN_Answer_C": "調整役",
  "ENG_to_JPN_Answer_D": "広告代理店"
},
{
  "word": "voucher",
  "explanation": "「voucher」は割引券や引換券、クーポンなどを指す名詞です。商品やサービスを受け取る際、所定の金額や特典を得られる仕組みを提供し、集客や顧客満足度を高めるための手段としてビジネスで広く活用されています。",
  "exampleSentence": "You can redeem this v______ for a free drink.",
  "japaneseTranslation": "このクーポンを使うと無料ドリンクがもらえます。",
  "meaningNoun": "クーポン、引換券",
  "phoneticSymbols": "/ˈvaʊ.tʃər/ (AmE: /-tʃɚ/)",
  "wordSynonyms": "coupon, ticket, certificate",
  "ENG_to_JPN_Answer": "引換券",
  "ENG_to_JPN_Answer_A": "引換券",
  "ENG_to_JPN_Answer_B": "違反通知",
  "ENG_to_JPN_Answer_C": "自己申告",
  "ENG_to_JPN_Answer_D": "セキュリティコード"
},
{
  "word": "adjacent",
  "explanation": "「adjacent」は「隣接した」「近接した」という意味の形容詞で、地理的または空間的にすぐそばに位置する状態を表します。建物やエリアが連続している場面などで使われ、地図上や不動産案内などで頻繁に登場する表現です。",
  "exampleSentence": "Our office is a_______ to the main train station.",
  "japaneseTranslation": "私たちのオフィスは主要駅に隣接しています。",
  "meaningAdjective": "隣接した、近接した",
  "phoneticSymbols": "/əˈdʒeɪ.sənt/",
  "wordSynonyms": "next to, adjoining, neighboring",
  "ENG_to_JPN_Answer": "隣接した",
  "ENG_to_JPN_Answer_A": "隣接した",
  "ENG_to_JPN_Answer_B": "取り除かれた",
  "ENG_to_JPN_Answer_C": "改善された",
  "ENG_to_JPN_Answer_D": "未完成の"
},
{
  "word": "correspondence",
  "explanation": "「correspondence」は「通信」「文書のやり取り」を指す名詞で、手紙やメールなどを通して情報を交換する行為や内容を表します。ビジネス文書や公的書簡において、やり取りの履歴や記録が重要となるシーンで頻出する用語です。",
  "exampleSentence": "All c____________ regarding the contract should be saved.",
  "japaneseTranslation": "契約に関するすべての通信記録は保存しておく必要があります。",
  "meaningNoun": "通信、文書のやり取り",
  "phoneticSymbols": "/ˌkɒr.ɪˈspɒn.dəns/ (AmE: /ˌkɔːr-/)",
  "wordSynonyms": "communication, mail, letters",
  "ENG_to_JPN_Answer": "通信",
  "ENG_to_JPN_Answer_A": "通信",
  "ENG_to_JPN_Answer_B": "破棄",
  "ENG_to_JPN_Answer_C": "投資",
  "ENG_to_JPN_Answer_D": "請求"
},
{
  "word": "detergent",
  "explanation": "「detergent」は洗剤やクリーニング剤を指す名詞で、衣類や食器、住居などの汚れを落とすために用いられます。液体や粉末、固形など様々な形状があり、成分や機能が幅広い製品として販売されている日用品の一種です。",
  "exampleSentence": "Use a mild d________ to avoid damaging delicate fabrics.",
  "japaneseTranslation": "繊細な生地を傷めないように、やさしい洗剤を使ってください。",
  "meaningNoun": "洗剤、クリーニング剤",
  "phoneticSymbols": "/dɪˈtɝː.dʒənt/",
  "ENG_to_JPN_Answer": "洗剤",
  "ENG_to_JPN_Answer_A": "洗剤",
  "ENG_to_JPN_Answer_B": "塗料",
  "ENG_to_JPN_Answer_C": "接着剤",
  "ENG_to_JPN_Answer_D": "研磨材"
},
{
  "word": "duration",
  "explanation": "「duration」は「継続時間」「期間」を意味する名詞で、イベントや契約、タスクなどがどれくらいの長さ続くかを示します。スケジュール管理やコスト見積もりなどにおいて、正確な期間の把握が必要な場面でよく用いられます。",
  "exampleSentence": "The d_______ of the training program is three months.",
  "japaneseTranslation": "その研修プログラムの期間は3ヶ月です。",
  "meaningNoun": "期間、継続時間",
  "phoneticSymbols": "/djʊəˈreɪ.ʃən/ (AmE: /duː-/)",
  "wordSynonyms": "length, span, period",
  "ENG_to_JPN_Answer": "期間",
  "ENG_to_JPN_Answer_A": "期間",
  "ENG_to_JPN_Answer_B": "習慣",
  "ENG_to_JPN_Answer_C": "費用",
  "ENG_to_JPN_Answer_D": "回数"
},
{
  "word": "functional",
  "explanation": "「functional」は「機能的な」「実用的な」という意味の形容詞で、デザインやシステムなどが目的に合った有用性を持つ状態を表します。装飾や外観よりも、性能や使い勝手、役立ち度を重視する文脈で頻繁に使われます。",
  "exampleSentence": "This f________ design maximizes workspace efficiency.",
  "japaneseTranslation": "この機能的なデザインは作業スペースの効率を最大化します。",
  "meaningAdjective": "機能的な、実用的な",
  "phoneticSymbols": "/ˈfʌŋk.ʃən.əl/",
  "wordSynonyms": "practical, utilitarian, useful",
  "ENG_to_JPN_Answer": "機能的な",
  "ENG_to_JPN_Answer_A": "機能的な",
  "ENG_to_JPN_Answer_B": "先進的な",
  "ENG_to_JPN_Answer_C": "虚飾の多い",
  "ENG_to_JPN_Answer_D": "限定的な"
},
{
  "word": "hands-on",
  "explanation": "「hands-on」は「実践的な」「体験型の」という意味を持つ形容詞で、理論ではなく実際に手を動かして学ぶ手法を指します。職業訓練やワークショップ、実習プログラムなどで用いられ、実務スキルを身につける際に重要なスタイルです。",
  "exampleSentence": "We offer h_____-o_ training to ensure practical skills.",
  "japaneseTranslation": "私たちは実践的なスキルを確実に習得できるよう、体験型の研修を提供しています。",
  "meaningAdjective": "実践的な、体験型の",
  "phoneticSymbols": "/ˌhændzˈɒn/ (AmE: /-ˈɑːn/)",
  "ENG_to_JPN_Answer": "実践的な",
  "ENG_to_JPN_Answer_A": "実践的な",
  "ENG_to_JPN_Answer_B": "理論的な",
  "ENG_to_JPN_Answer_C": "強制的な",
  "ENG_to_JPN_Answer_D": "一時的な"
},
{
  "word": "intensive",
  "explanation": "「intensive」は「集中的な」「徹底的な」という意味を持つ形容詞で、限られた時間内に高い密度で作業や学習を行うことを示します。集中講座や短期プログラムで用いられ、効率よく成果を得たい場合に好んで使われます。",
  "exampleSentence": "They enrolled in an i________ language course to improve quickly.",
  "japaneseTranslation": "彼らは短期間で上達するために集中的な語学コースに登録しました。",
  "meaningAdjective": "集中的な",
  "phoneticSymbols": "/ɪnˈten.sɪv/",
  "wordSynonyms": "concentrated, thorough, rigorous",
  "wordAntonym": "light",
  "ENG_to_JPN_Answer": "集中的な",
  "ENG_to_JPN_Answer_A": "集中的な",
  "ENG_to_JPN_Answer_B": "悠長な",
  "ENG_to_JPN_Answer_C": "遅延した",
  "ENG_to_JPN_Answer_D": "不愉快な"
},
{
  "word": "last-minute",
  "explanation": "「last-minute」は「土壇場の」「直前の」という意味の形容詞で、締め切りや期限が間近に迫った状態を指します。急ぎの対応や計画変更を余儀なくされる場面で用いられ、ビジネスから日常生活まで幅広く登場する表現です。",
  "exampleSentence": "We had to make a l____-m_____ change to the schedule.",
  "japaneseTranslation": "私たちはスケジュールに土壇場で変更を加えなければなりませんでした。",
  "meaningAdjective": "直前の、土壇場の",
  "phoneticSymbols": "/ˈlæstˌmɪnɪt/",
  "ENG_to_JPN_Answer": "直前の",
  "ENG_to_JPN_Answer_A": "直前の",
  "ENG_to_JPN_Answer_B": "余裕のある",
  "ENG_to_JPN_Answer_C": "途方もない",
  "ENG_to_JPN_Answer_D": "例外的な"
},
{
  "word": "thrilled",
  "explanation": "「thrilled」は「わくわくしている」「大喜びである」という感情を表す形容詞です。嬉しいニュースを聞いたときや刺激的な体験をするときに感じる興奮を示し、ポジティブな感情を強調したいときに使われます。",
  "exampleSentence": "I’m t_______ to announce our new product line.",
  "japaneseTranslation": "新しい製品ラインを発表できることにわくわくしています。",
  "meaningAdjective": "大喜びしている、わくわくしている",
  "phoneticSymbols": "/θrɪld/",
  "wordSynonyms": "excited, delighted, exhilarated",
  "wordAntonym": "disappointed",
  "ENG_to_JPN_Answer": "大喜びしている",
  "ENG_to_JPN_Answer_A": "大喜びしている",
  "ENG_to_JPN_Answer_B": "落ち込んでいる",
  "ENG_to_JPN_Answer_C": "うんざりしている",
  "ENG_to_JPN_Answer_D": "半信半疑である"
},
{
  "word": "spectacular",
  "explanation": "「spectacular」は「壮観な」「目を見張るような」という意味の形容詞で、視覚的に非常に印象深い景色やパフォーマンスなどを表します。花火大会やショー、大自然の風景など、強い感動や驚きを伴う場面でよく使われる語です。",
  "exampleSentence": "The fireworks display was truly s__________.",
  "japaneseTranslation": "その花火大会は本当に壮観でした。",
  "meaningAdjective": "壮観な、目を見張るような",
  "phoneticSymbols": "/spekˈtæk.jə.lər/",
  "wordSynonyms": "impressive, stunning, magnificent",
  "ENG_to_JPN_Answer": "壮観な",
  "ENG_to_JPN_Answer_A": "壮観な",
  "ENG_to_JPN_Answer_B": "短命な",
  "ENG_to_JPN_Answer_C": "地味な",
  "ENG_to_JPN_Answer_D": "危険な"
},
{
  "word": "entrepreneur",
  "explanation": "「entrepreneur」は事業を創出し、リスクを負いつつ新たな価値やサービスを提供する起業家を指す名詞です。スタートアップ企業やイノベーションの場面でよく取り上げられ、社会や経済に新しい動きをもたらす存在として注目されます。",
  "exampleSentence": "An e_____________ must be willing to take calculated risks.",
  "japaneseTranslation": "起業家は計画的なリスクを取る覚悟が必要です。",
  "meaningNoun": "起業家、事業家",
  "phoneticSymbols": "/ˌɒn.trə.prəˈnɜːr/ (AmE: /ˌɑːn-/)",
  "wordSynonyms": "founder, business owner, innovator",
  "ENG_to_JPN_Answer": "起業家",
  "ENG_to_JPN_Answer_A": "起業家",
  "ENG_to_JPN_Answer_B": "投資家",
  "ENG_to_JPN_Answer_C": "監査役",
  "ENG_to_JPN_Answer_D": "ベテラン社員"
},
{
  "word": "introductory",
  "explanation": "「introductory」は「入門の」「初歩的な」「紹介のための」を意味する形容詞で、初めて学ぶ人向けの基礎内容や、概念を簡単に提示する際に使われます。コース名や割引オファーなどで「お試し」的な意味合いを持つ場合も多いです。",
  "exampleSentence": "He’s taking an i____________ course in computer programming.",
  "japaneseTranslation": "彼はコンピュータプログラミングの入門コースを受講しています。",
  "meaningAdjective": "入門の、紹介用の",
  "phoneticSymbols": "/ˌɪn.trəˈdʌk.tər.i/ (AmE: /-tɔːr.i/)",
  "wordSynonyms": "beginner’s, preliminary, opening",
  "ENG_to_JPN_Answer": "入門の",
  "ENG_to_JPN_Answer_A": "入門の",
  "ENG_to_JPN_Answer_B": "混合の",
  "ENG_to_JPN_Answer_C": "厳格な",
  "ENG_to_JPN_Answer_D": "並外れた"
},
{
  "word": "minimize",
  "explanation": "「minimize」は「最小限にする」「軽減する」という意味の動詞で、リスクやコスト、影響などをできるだけ低く抑える場合に用いられます。業務効率化や環境への負荷軽減など、様々な場面で頻繁に登場する重要な概念です。",
  "exampleSentence": "We aim to m________ waste by improving our production process.",
  "japaneseTranslation": "生産工程を改善することで廃棄物を最小限に抑えることを目指しています。",
  "meaningVerb": "最小限にする、軽減する",
  "phoneticSymbols": "/ˈmɪn.ɪ.maɪz/",
  "wordSynonyms": "reduce, lessen, diminish",
  "wordAntonym": "maximize",
  "ENG_to_JPN_Answer": "最小限にする",
  "ENG_to_JPN_Answer_A": "最小限にする",
  "ENG_to_JPN_Answer_B": "増強する",
  "ENG_to_JPN_Answer_C": "誇大宣伝する",
  "ENG_to_JPN_Answer_D": "隠蔽する"
},
{
  "word": "prestigious",
  "explanation": "「prestigious」は「名声のある」「一流の」という意味の形容詞で、高い評価や権威を持つ人・組織・賞などを表す際に使われます。大学や企業、イベントなど、社会的信用やステータスを伴う対象を示す重要な形容詞です。",
  "exampleSentence": "She graduated from a p_________ university with top honors.",
  "japaneseTranslation": "彼女は名門大学をトップの成績で卒業しました。",
  "meaningAdjective": "名声のある、一流の",
  "phoneticSymbols": "/preˈstɪdʒ.əs/ (AmE: /-ˈstɪː-/)",
  "wordSynonyms": "renowned, esteemed, highly regarded",
  "ENG_to_JPN_Answer": "名声のある",
  "ENG_to_JPN_Answer_A": "名声のある",
  "ENG_to_JPN_Answer_B": "平凡な",
  "ENG_to_JPN_Answer_C": "小規模の",
  "ENG_to_JPN_Answer_D": "不確かな"
},
{
  "word": "screening",
  "explanation": "「screening」は名詞として映画や映像の上映、または病気や応募者などを選別・検査するスクリーニングを指します。映画館やイベントでの上映、あるいは健康診断や採用活動の場面など、内容に応じて多義的に使われる表現です。",
  "exampleSentence": "They held a private s________ of the new documentary.",
  "japaneseTranslation": "彼らは新しいドキュメンタリーのプライベート上映会を行いました。",
  "meaningNoun": "上映、検査・選別",
  "phoneticSymbols": "/ˈskriː.nɪŋ/",
  "wordSynonyms": "showing, testing, examination",
  "ENG_to_JPN_Answer": "上映（または検査）",
  "ENG_to_JPN_Answer_A": "上映（または検査）",
  "ENG_to_JPN_Answer_B": "構築",
  "ENG_to_JPN_Answer_C": "保管",
  "ENG_to_JPN_Answer_D": "改修"
},
{
  "word": "amenity",
  "explanation": "「amenity」はホテルやマンション、オフィスビルなどの施設において、利用者の快適性や利便性を高めるために設置されている設備やサービスを指します。プールやジム、ラウンジなどが代表的で、物件の価値や魅力を左右する要素となります。",
  "exampleSentence": "The hotel offers various a______ such as a pool and a spa.",
  "japaneseTranslation": "そのホテルにはプールやスパなど多様なアメニティがあります。",
  "meaningNoun": "施設内の設備やサービス",
  "phoneticSymbols": "/əˈmen.ə.ti/ (AmE: /-ˈme.nɪ.t̬i/)",
  "wordSynonyms": "facility, convenience, comfort",
  "ENG_to_JPN_Answer": "設備",
  "ENG_to_JPN_Answer_A": "設備",
  "ENG_to_JPN_Answer_B": "布製品",
  "ENG_to_JPN_Answer_C": "請求書",
  "ENG_to_JPN_Answer_D": "媒介物"
},
{
  "word": "lengthy",
  "explanation": "「lengthy」は「長時間の」「長ったらしい」という意味を持つ形容詞で、会議や手続き、文章などが想定より長く続く場合に使われます。ネガティブなニュアンスを含む場合が多く、効率や簡潔さが求められる場面で特に意識される語です。",
  "exampleSentence": "The approval process can be l______ and complicated.",
  "japaneseTranslation": "承認プロセスは長引き、複雑になりがちです。",
  "meaningAdjective": "長時間の、冗長な",
  "phoneticSymbols": "/ˈleŋ.θi/",
  "wordSynonyms": "prolonged, extended, long-winded",
  "ENG_to_JPN_Answer": "長時間の",
  "ENG_to_JPN_Answer_A": "長時間の",
  "ENG_to_JPN_Answer_B": "軽快な",
  "ENG_to_JPN_Answer_C": "偶発的な",
  "ENG_to_JPN_Answer_D": "高額な"
},
{
  "word": "compensate",
  "explanation": "「compensate」は「補償する」「埋め合わせをする」という意味を持つ動詞で、損失や不利益を被った人に対して金銭やサービスなどで償う行為を指します。企業の保証制度や労働環境においてよく使われる重要な概念です。",
  "exampleSentence": "The airline will c________ passengers for the delayed flight.",
  "japaneseTranslation": "航空会社は遅延したフライトに対して乗客へ補償を行います。",
  "meaningVerb": "補償する、償う",
  "phoneticSymbols": "/ˈkɒm.pən.seɪt/ (AmE: /ˈkɑːm-/)",
  "wordSynonyms": "reimburse, atone, make up for",
  "ENG_to_JPN_Answer": "補償する",
  "ENG_to_JPN_Answer_A": "補償する",
  "ENG_to_JPN_Answer_B": "提出する",
  "ENG_to_JPN_Answer_C": "撤退する",
  "ENG_to_JPN_Answer_D": "評価する"
},
{
  "word": "misplace",
  "explanation": "「misplace」は「置き忘れる」「紛失する」という意味の動詞で、本来あるべき所に物を置かずになくしてしまう状態を指します。書類や鍵、スマートフォンなどの日用品でよく起こり、注意力不足や忙しさが原因となることが多いです。",
  "exampleSentence": "I must have m_______ my phone somewhere in the office.",
  "japaneseTranslation": "オフィスのどこかに電話を置き忘れてしまったようです。",
  "meaningVerb": "置き忘れる、紛失する",
  "phoneticSymbols": "/ˌmɪsˈpleɪs/",
  "wordSynonyms": "lose, mislay, misplace",
  "ENG_to_JPN_Answer": "置き忘れる",
  "ENG_to_JPN_Answer_A": "置き忘れる",
  "ENG_to_JPN_Answer_B": "掃除する",
  "ENG_to_JPN_Answer_C": "投函する",
  "ENG_to_JPN_Answer_D": "寄贈する"
},
{
  "word": "notable",
  "explanation": "「notable」は「注目に値する」「顕著な」という意味を持つ形容詞で、人物や出来事、成果などが特に目を引く際に使われます。実績があったり、歴史的・社会的に重要であったりする場合に用いられ、ポジティブな評価を含意する場合が多いです。",
  "exampleSentence": "He made a n______ contribution to the research project.",
  "japaneseTranslation": "彼は研究プロジェクトに顕著な貢献をしました。",
  "meaningAdjective": "注目に値する、顕著な",
  "phoneticSymbols": "/ˈnəʊ.tə.bəl/ (AmE: /ˈnoʊ-/)",
  "wordSynonyms": "remarkable, significant, noteworthy",
  "ENG_to_JPN_Answer": "注目に値する",
  "ENG_to_JPN_Answer_A": "注目に値する",
  "ENG_to_JPN_Answer_B": "無意味な",
  "ENG_to_JPN_Answer_C": "隠蔽された",
  "ENG_to_JPN_Answer_D": "不規則な"
},
{
  "word": "subsidiary",
  "explanation": "「subsidiary」は親会社に所有・管理されている子会社を指す名詞です。企業グループ内で独立した法人格を持ちながらも、経営方針や財務面で親会社に大きく影響を受ける存在として経営戦略上重要な役割を担います。",
  "exampleSentence": "This s_________ focuses on technology research and development.",
  "japaneseTranslation": "この子会社は技術の研究開発に特化しています。",
  "meaningNoun": "子会社",
  "phoneticSymbols": "/səbˈsɪd.i.ə.ri/ (AmE: /-er.i/)",
  "wordSynonyms": "affiliate, branch, subdivision",
  "ENG_to_JPN_Answer": "子会社",
  "ENG_to_JPN_Answer_A": "子会社",
  "ENG_to_JPN_Answer_B": "合弁会社",
  "ENG_to_JPN_Answer_C": "労働組合",
  "ENG_to_JPN_Answer_D": "規制当局"
},
{
  "word": "authentic",
  "explanation": "「authentic」は「本物の」「信頼できる」という意味を持つ形容詞で、偽物ではなく真正であること、または情報などが正確で信頼に足ることを指します。料理や芸術作品などのオリジナル性を強調する場合にも用いられます。",
  "exampleSentence": "They serve a________ Italian pizza made by a native chef.",
  "japaneseTranslation": "彼らは本場のシェフが作る本物のイタリアピザを提供しています。",
  "meaningAdjective": "本物の、真正の",
  "phoneticSymbols": "/ɔːˈθen.tɪk/ (AmE: /ɑː-/)",
  "wordSynonyms": "genuine, real, legitimate",
  "wordAntonym": "fake",
  "ENG_to_JPN_Answer": "本物の",
  "ENG_to_JPN_Answer_A": "本物の",
  "ENG_to_JPN_Answer_B": "希薄な",
  "ENG_to_JPN_Answer_C": "過剰な",
  "ENG_to_JPN_Answer_D": "複合的な"
},
{
  "word": "designated",
  "explanation": "「designated」は「指定された」「任命された」という意味の形容詞で、特定の場所や人物、任務などを正式に割り当てられた状態を表します。担当者や駐車スペースなど、公的または組織的な意思決定による指定を示す文脈でよく使われます。",
  "exampleSentence": "Please wait in the d________ area until your name is called.",
  "japaneseTranslation": "名前を呼ばれるまで、指定されたエリアでお待ちください。",
  "meaningAdjective": "指定された、任命された",
  "phoneticSymbols": "/ˈdez.ɪɡ.neɪ.tɪd/",
  "wordSynonyms": "appointed, assigned, allocated",
  "ENG_to_JPN_Answer": "指定された",
  "ENG_to_JPN_Answer_A": "指定された",
  "ENG_to_JPN_Answer_B": "廃止された",
  "ENG_to_JPN_Answer_C": "補完された",
  "ENG_to_JPN_Answer_D": "強奪された"
},
{
  "word": "disruption",
  "explanation": "「disruption」は「混乱」「中断」「破壊的変化」を意味する名詞で、通常の流れや秩序が妨げられる状態を表します。交通機関の遅延やサービス停止などの物理的な混乱だけでなく、革新的技術が市場を根本から変える状況を指す場合にも使われる表現です。",
  "exampleSentence": "A power outage caused serious d________ to production.",
  "japaneseTranslation": "停電が発生し、生産に重大な混乱をもたらしました。",
  "meaningNoun": "混乱、中断、破壊的変化",
  "phoneticSymbols": "/dɪsˈrʌp.ʃən/",
  "wordSynonyms": "disturbance, interruption, upheaval",
  "ENG_to_JPN_Answer": "混乱",
  "ENG_to_JPN_Answer_A": "混乱",
  "ENG_to_JPN_Answer_B": "回復",
  "ENG_to_JPN_Answer_C": "適合",
  "ENG_to_JPN_Answer_D": "躊躇"
},
{
  "word": "fragile",
  "explanation": "「fragile」は「壊れやすい」「もろい」という意味を持つ形容詞で、ガラス製品や繊細な機器など、取り扱いに注意が必要な物を表す際に用いられます。心理的・経済的にも不安定な状態を比喩的に表す場合があり、注意深い対応を促す言葉です。",
  "exampleSentence": "Handle the f______ glassware with utmost care.",
  "japaneseTranslation": "この壊れやすいガラス製品は十分に注意して扱ってください。",
  "meaningAdjective": "壊れやすい、もろい",
  "phoneticSymbols": "/ˈfrædʒ.aɪl/ (AmE: /-əl/)",
  "wordSynonyms": "delicate, breakable, brittle",
  "wordAntonym": "durable",
  "ENG_to_JPN_Answer": "壊れやすい",
  "ENG_to_JPN_Answer_A": "壊れやすい",
  "ENG_to_JPN_Answer_B": "鋭利な",
  "ENG_to_JPN_Answer_C": "溶解性の",
  "ENG_to_JPN_Answer_D": "詰め込み式の"
},
{
  "word": "ongoing",
  "explanation": "「ongoing」は「進行中の」「継続している」という意味を持つ形容詞で、まだ完了しておらず今も続いているプロセスや状態を表します。プロジェクトや調査、交渉など、完了までに一定の時間を要する活動を指す際に頻繁に使用されます。",
  "exampleSentence": "The o______ negotiations may take another week to conclude.",
  "japaneseTranslation": "現在進行中の交渉は、完了までにあと1週間ほどかかるかもしれません。",
  "meaningAdjective": "進行中の、継続している",
  "phoneticSymbols": "/ˈɒŋ.ɡoʊ.ɪŋ/ (AmE: /ˈɑːŋ-/)",
  "wordSynonyms": "continuing, in progress, current",
  "ENG_to_JPN_Answer": "進行中の",
  "ENG_to_JPN_Answer_A": "進行中の",
  "ENG_to_JPN_Answer_B": "過去の",
  "ENG_to_JPN_Answer_C": "急停止した",
  "ENG_to_JPN_Answer_D": "秘密裏の"
},
{
  "word": "periodical",
  "explanation": "「periodical」は定期的に発行される雑誌や刊行物などを指す名詞、または「定期的な」という意味の形容詞です。学術雑誌や業界誌などが典型例で、一定の周期で新しい情報や研究成果を掲載し続ける媒体として使われます。",
  "exampleSentence": "She writes articles for a well-known academic p__________.",
  "japaneseTranslation": "彼女は有名な学術定期刊行物に記事を書いています。",
  "meaningNoun": "定期刊行物",
  "meaningAdjective": "定期的な",
  "phoneticSymbols": "/ˌpɪə.riˈɒd.ɪ.kəl/ (AmE: /ˌpɪr.iˈɑː.dɪ-/)",
  "ENG_to_JPN_Answer": "定期刊行物",
  "ENG_to_JPN_Answer_A": "定期刊行物",
  "ENG_to_JPN_Answer_B": "新聞の特別号",
  "ENG_to_JPN_Answer_C": "論文要旨",
  "ENG_to_JPN_Answer_D": "図鑑"
},
{
  "word": "plumber",
  "explanation": "「plumber」は水道管や排水設備などの配管工事を専門とする職人、またはその業務を指す名詞です。家庭や建物での水漏れや詰まりなどのトラブルシューティングや新規配管の設置を担い、インフラを支える重要な職業です。",
  "exampleSentence": "We called a p______ to fix the leaking faucet.",
  "japaneseTranslation": "水漏れしている蛇口を直すために配管工を呼びました。",
  "meaningNoun": "配管工",
  "phoneticSymbols": "/ˈplʌm.ər/ (AmE: /-ɚ/)",
  "wordSynonyms": "pipe fitter, handyman, tradesperson",
  "ENG_to_JPN_Answer": "配管工",
  "ENG_to_JPN_Answer_A": "配管工",
  "ENG_to_JPN_Answer_B": "建築家",
  "ENG_to_JPN_Answer_C": "電気技師",
  "ENG_to_JPN_Answer_D": "溶接工"
},
{
  "word": "incur",
  "explanation": "「incur」は「（損害や費用などを）被る」「招く」という意味の動詞で、ある行動や状況によって好ましくない結果を引き起こす場合に使われます。遅延損害金や追加コストなど、経済的・責任的負担を負う状況でしばしば登場する語です。",
  "exampleSentence": "If you cancel late, you may i____ a penalty fee.",
  "japaneseTranslation": "遅れてキャンセルするとペナルティ料金が発生する可能性があります。",
  "meaningVerb": "被る、招く",
  "phoneticSymbols": "/ɪnˈkɜːr/",
  "wordSynonyms": "face, suffer, bring upon oneself",
  "ENG_to_JPN_Answer": "被る",
  "ENG_to_JPN_Answer_A": "被る",
  "ENG_to_JPN_Answer_B": "分配する",
  "ENG_to_JPN_Answer_C": "節約する",
  "ENG_to_JPN_Answer_D": "干渉する"
},
{
  "word": "oversee",
  "explanation": "「oversee」は「監督する」「管理する」という意味の動詞で、業務やプロジェクト全体を見渡し、進捗や品質、メンバーの動きをチェックする立場を表します。管理職やリーダーが責任を持って全体を把握する場面でよく使われます。",
  "exampleSentence": "He was hired to o______ the company's new marketing initiative.",
  "japaneseTranslation": "彼はその会社の新しいマーケティング活動を管理するために雇われました。",
  "meaningVerb": "監督する、管理する",
  "phoneticSymbols": "/ˌəʊ.vəˈsiː/ (AmE: /ˌoʊ.vɚ-/)",
  "wordSynonyms": "supervise, manage, direct",
  "ENG_to_JPN_Answer": "監督する",
  "ENG_to_JPN_Answer_A": "監督する",
  "ENG_to_JPN_Answer_B": "放置する",
  "ENG_to_JPN_Answer_C": "論破する",
  "ENG_to_JPN_Answer_D": "収束させる"
},
{
  "word": "retrieve",
  "explanation": "「retrieve」は「取り戻す」「回収する」「検索する」という意味を持つ動詞で、失ったり預けたりした物や情報を再び手に入れる場合に使われます。データベース検索やファイルの復元など、IT分野でも重要なオペレーションを示す単語です。",
  "exampleSentence": "You can r_______ the stored data using this password.",
  "japaneseTranslation": "このパスワードを使用して、保存されたデータを取り出すことができます。",
  "meaningVerb": "取り戻す、回収する",
  "phoneticSymbols": "/rɪˈtriːv/",
  "wordSynonyms": "recover, regain, get back",
  "ENG_to_JPN_Answer": "取り戻す",
  "ENG_to_JPN_Answer_A": "取り戻す",
  "ENG_to_JPN_Answer_B": "送信する",
  "ENG_to_JPN_Answer_C": "削除する",
  "ENG_to_JPN_Answer_D": "置き換える"
},
{
  "word": "reunion",
  "explanation": "「reunion」は「再会」「同窓会」など、離れていた人々が再び集まることを指す名詞です。家族や友人、卒業生などが一定期間を経て顔を合わせるイベントや場面で使われ、思い出話や近況報告で盛り上がる機会を表す言葉です。",
  "exampleSentence": "We’re planning a family r_______ for the holidays.",
  "japaneseTranslation": "私たちは休日に家族の再会を計画しています。",
  "meaningNoun": "再会、同窓会",
  "phoneticSymbols": "/ˌriːˈjuː.njən/",
  "wordSynonyms": "gathering, get-together, homecoming",
  "ENG_to_JPN_Answer": "再会",
  "ENG_to_JPN_Answer_A": "再会",
  "ENG_to_JPN_Answer_B": "競争",
  "ENG_to_JPN_Answer_C": "就職活動",
  "ENG_to_JPN_Answer_D": "通達"
},
{
  "word": "rigorous",
  "explanation": "「rigorous」は「厳格な」「徹底的な」という意味を持つ形容詞で、調査や訓練、検査などを厳密に行い、一切の手抜きや甘さがない状態を指します。学術研究や品質管理などで高い基準を求める場合に頻出する重要な表現です。",
  "exampleSentence": "The lab conducts r________ testing before approving any new drug.",
  "japaneseTranslation": "その研究所では新しい薬を承認する前に徹底的なテストを行います。",
  "meaningAdjective": "厳格な、徹底的な",
  "phoneticSymbols": "/ˈrɪɡ.ər.əs/ (AmE: /-ɚ-/)",
  "wordSynonyms": "strict, thorough, meticulous",
  "wordAntonym": "lenient",
  "ENG_to_JPN_Answer": "厳格な",
  "ENG_to_JPN_Answer_A": "厳格な",
  "ENG_to_JPN_Answer_B": "有害な",
  "ENG_to_JPN_Answer_C": "適当な",
  "ENG_to_JPN_Answer_D": "優雅な"
},
{
  "word": "specification",
  "explanation": "「specification」は「仕様書」「明細」「スペック」として、製品やサービスに要求される詳細条件・基準を示す名詞です。開発や製造などの技術分野で重要視され、品質や性能を担保する上で欠かせないドキュメントとなります。",
  "exampleSentence": "We must meet all s_____________ to ensure safety and quality.",
  "japaneseTranslation": "安全と品質を確保するために、すべての仕様を満たさなければなりません。",
  "meaningNoun": "仕様、明細",
  "phoneticSymbols": "/ˌspes.ɪ.fɪˈkeɪ.ʃən/",
  "wordSynonyms": "requirements, details, criteria",
  "ENG_to_JPN_Answer": "仕様",
  "ENG_to_JPN_Answer_A": "仕様",
  "ENG_to_JPN_Answer_B": "図鑑",
  "ENG_to_JPN_Answer_C": "雑感",
  "ENG_to_JPN_Answer_D": "妥協点"
},
{
  "word": "tentative",
  "explanation": "「tentative」は「仮の」「試験的な」という意味を持つ形容詞で、正式に確定していない段階での計画や日程、案などを表します。ビジネス会議のアジェンダやリリース予定などにおいて、まだ変更の可能性があることを示す表現です。",
  "exampleSentence": "We set a t________ date for the product launch, subject to change.",
  "japaneseTranslation": "製品ローンチの仮の日程を設定しましたが、変更の可能性があります。",
  "meaningAdjective": "仮の、試験的な",
  "phoneticSymbols": "/ˈten.tə.tɪv/ (AmE: /-t̬ə.t̬ɪv/)",
  "wordSynonyms": "provisional, temporary, preliminary",
  "ENG_to_JPN_Answer": "仮の",
  "ENG_to_JPN_Answer_A": "仮の",
  "ENG_to_JPN_Answer_B": "確定の",
  "ENG_to_JPN_Answer_C": "虚偽の",
  "ENG_to_JPN_Answer_D": "使い捨ての"
},

  ];

  for (var wordData in wordsData) {
    try {
      // コレクション内のドキュメント数を取得し、新しい Word_id を設定
      final snapshot = await firestore.collection(collectionPath).get();
      final newWordId = snapshot.docs.length + 1;

      // データをFirebaseに保存
      await firestore.collection(collectionPath).add({
        'Word_id': newWordId,
        'ENG_to_JPN_Answer': wordData['ENG_to_JPN_Answer'],
        'ENG_to_JPN_Answer_A': wordData['ENG_to_JPN_Answer_A'],
        'ENG_to_JPN_Answer_B': wordData['ENG_to_JPN_Answer_B'],
        'ENG_to_JPN_Answer_C': wordData['ENG_to_JPN_Answer_C'],
        'ENG_to_JPN_Answer_D': wordData['ENG_to_JPN_Answer_D'],
        'Word': wordData['word'] ?? '',
        'Explanation': wordData['explanation'] ?? '',
        'JPN_to_ENG_Answer': wordData['word'] ?? '',
        'JPN_to_ENG_Question_ENG': wordData['exampleSentence'] ?? '',
        'JPN_to_ENG_Question_JPN': wordData['japaneseTranslation'] ?? '',
        'Meaning_Adjective': wordData['meaningAdjective'] ?? '',
        'Meaning_Adverb': wordData['meaningAdverb'] ?? '',
        'Meaning_Noun': wordData['meaningNoun'] ?? '',
        'Meaning_Preposition': wordData['meaningPreposition'] ?? '',
        'Meaning_Verb': wordData['meaningVerb'] ?? '',
        'Phonetic_Symbols': wordData['phoneticSymbols'] ?? '',
        'Word_Preposition': wordData['wordPreposition'] ?? '',
        'Word_Related': wordData['wordRelated'] ?? '',
        'Word_Verb': wordData['wordVerb'] ?? '',
        'Word_Noun': wordData['wordNoun'] ?? '',
        'Word_Adjective': wordData['wordAdjective'] ?? '',
        'Word_Adverb': wordData['wordAdverb'] ?? '',
        'Word_Synonyms': wordData['wordSynonyms'] ?? '',
        'Word_Antonym': wordData['wordAntonym'] ?? '',
      });

      print('単語 "${wordData['word']}" を登録しました (Word_id: $newWordId)');
    } catch (e) {
      print('単語 "${wordData['word']}" の登録中にエラーが発生しました: $e');
    }
  }
}


