import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> uploadWordsToFirestore() async {
  final firestore = FirebaseFirestore.instance;
  const collectionPath = 'English_Skills/TOEIC/up_to_990/Words/Word';

  // 登録するデータ
  final List<Map<String, dynamic>> wordsData = [
{
  "word": "subsequent",
  "explanation": "「subsequent」は「後に続く」「その次の」という意味の形容詞で、何か出来事や行動の後に起こる事柄を指し示します。ビジネスや学術論文などで時系列を示す際に頻繁に用いられる表現です。",
  "exampleSentence": "All s________ updates will be emailed to you.",
  "japaneseTranslation": "後に続くすべてのアップデートはメールでお送りします。",
  "meaningAdjective": "後に続く、次の",
  "phoneticSymbols": "/ˈsʌb.sɪ.kwənt/",
  "wordSynonyms": "following, later, ensuing",
  "wordAntonym": "previous",
  "ENG_to_JPN_Answer": "後に続く",
  "ENG_to_JPN_Answer_A": "後に続く",
  "ENG_to_JPN_Answer_B": "一時的な",
  "ENG_to_JPN_Answer_C": "不可欠な",
  "ENG_to_JPN_Answer_D": "先行する"
},
{
  "word": "thoughtfully",
  "explanation": "「thoughtfully」は「思慮深く」「慎重に」という意味の副詞で、発言や行動を行う際に相手の状況や可能性をよく考慮することを示します。ビジネスメールや議論の場面で丁寧さや配慮を表す言葉として使われます。",
  "exampleSentence": "She t__________ considered all opinions before making a decision.",
  "japaneseTranslation": "彼女は決定を下す前に、すべての意見を慎重に考慮しました。",
  "meaningAdverb": "思慮深く、慎重に",
  "phoneticSymbols": "/ˈθɔːt.fəl.i/",
  "wordSynonyms": "carefully, considerately, attentively",
  "ENG_to_JPN_Answer": "思慮深く",
  "ENG_to_JPN_Answer_A": "思慮深く",
  "ENG_to_JPN_Answer_B": "即興で",
  "ENG_to_JPN_Answer_C": "緊張して",
  "ENG_to_JPN_Answer_D": "意図せず"
},
{
  "word": "abridged",
  "explanation": "「abridged」は「要約された」「短縮版の」という意味の形容詞で、原本の重要部分を残しつつも簡略化した形式を表します。書籍や記事などを短くまとめる際によく使われ、コンパクトに内容を把握したい場合に重宝されます。",
  "exampleSentence": "He read an a_______ version of the classic novel.",
  "japaneseTranslation": "彼はその古典小説の要約版を読んでいました。",
  "meaningAdjective": "要約された、短縮版の",
  "phoneticSymbols": "/əˈbrɪdʒd/",
  "wordSynonyms": "shortened, condensed, summarized",
  "wordAntonym": "unabridged",
  "ENG_to_JPN_Answer": "要約された",
  "ENG_to_JPN_Answer_A": "要約された",
  "ENG_to_JPN_Answer_B": "台無しの",
  "ENG_to_JPN_Answer_C": "誇張された",
  "ENG_to_JPN_Answer_D": "肥大化した"
},
{
  "word": "carpool",
  "explanation": "「carpool」は、同じ目的地へ行く人同士が車を共有して通勤・通学などを行うことを指す名詞・動詞です。交通費や環境負荷の削減に役立つ仕組みとして、多くの企業や自治体で推奨されることがあります。",
  "exampleSentence": "We decided to c______ to save on fuel costs.",
  "japaneseTranslation": "燃料費を節約するために私たちは相乗りをすることにしました。",
  "meaningNoun": "相乗り、カープール",
  "phoneticSymbols": "/ˈkɑːrpuːl/",
  "ENG_to_JPN_Answer": "相乗り",
  "ENG_to_JPN_Answer_A": "相乗り",
  "ENG_to_JPN_Answer_B": "買い占め",
  "ENG_to_JPN_Answer_C": "貸し借り",
  "ENG_to_JPN_Answer_D": "中継輸送"
},
{
  "word": "compatible",
  "explanation": "「compatible」は「互換性のある」「両立できる」という意味の形容詞で、機器やシステム、考え方などが問題なく一緒に機能したり共存できる状態を指します。コンピュータソフトや企業文化の相性など、多様な場面で使われます。",
  "exampleSentence": "The new software is c________ with most operating systems.",
  "japaneseTranslation": "その新しいソフトウェアはほとんどのオペレーティングシステムと互換性があります。",
  "meaningAdjective": "互換性のある、両立できる",
  "phoneticSymbols": "/kəmˈpæt.ə.bəl/",
  "wordSynonyms": "consistent, well-matched, harmonious",
  "wordAntonym": "incompatible",
  "ENG_to_JPN_Answer": "互換性のある",
  "ENG_to_JPN_Answer_A": "互換性のある",
  "ENG_to_JPN_Answer_B": "不可解な",
  "ENG_to_JPN_Answer_C": "不十分な",
  "ENG_to_JPN_Answer_D": "不安定な"
},
{
  "word": "endorse",
  "explanation": "「endorse」は「支持する」「推奨する」「承認する」という意味の動詞で、特定の意見や商品、サービスを公に肯定的に評価する行為を指します。広告やマーケティングでも有名人が商品を推奨する際に用いられる重要な表現です。",
  "exampleSentence": "The celebrity agreed to e_____ the new skincare line.",
  "japaneseTranslation": "その有名人は新しいスキンケアラインを推奨することに同意しました。",
  "meaningVerb": "支持する、承認する",
  "phoneticSymbols": "/ɪnˈdɔːs/ (AmE: /-ˈdɔːrs/)",
  "wordSynonyms": "approve, support, recommend",
  "wordAntonym": "oppose",
  "ENG_to_JPN_Answer": "支持する",
  "ENG_to_JPN_Answer_A": "支持する",
  "ENG_to_JPN_Answer_B": "衝突する",
  "ENG_to_JPN_Answer_C": "放置する",
  "ENG_to_JPN_Answer_D": "破棄する"
},
{
  "word": "explicit",
  "explanation": "「explicit」は「明白な」「明確な」という意味を持つ形容詞で、曖昧さがなくはっきりと書かれたり述べられたりしている状態を指します。契約書や説明書などで誤解を生まないために、明示的な表現が求められる場合によく用いられます。",
  "exampleSentence": "The manager gave e________ instructions on how to proceed.",
  "japaneseTranslation": "マネージャーは次のステップについて明確な指示を出しました。",
  "meaningAdjective": "明白な、明確な",
  "phoneticSymbols": "/ɪkˈsplɪs.ɪt/",
  "wordSynonyms": "clear, unambiguous, straightforward",
  "wordAntonym": "implicit",
  "ENG_to_JPN_Answer": "明確な",
  "ENG_to_JPN_Answer_A": "明確な",
  "ENG_to_JPN_Answer_B": "厳重な",
  "ENG_to_JPN_Answer_C": "違法な",
  "ENG_to_JPN_Answer_D": "些細な"
},
{
  "word": "keenly",
  "explanation": "「keenly」は「鋭く」「熱心に」という意味の副詞で、物事を強い関心をもって深く観察・感じ取る様子を表します。ビジネスや学問の場では、相手の発言や状況を熱心にとらえる姿勢を示す言葉としてよく使われます。",
  "exampleSentence": "They listened k______ to the market trends.",
  "japaneseTranslation": "彼らは市場動向を熱心に聞き入りました。",
  "meaningAdverb": "鋭く、熱心に",
  "phoneticSymbols": "/ˈkiːn.li/",
  "ENG_to_JPN_Answer": "熱心に",
  "ENG_to_JPN_Answer_A": "熱心に",
  "ENG_to_JPN_Answer_B": "緩慢に",
  "ENG_to_JPN_Answer_C": "不注意に",
  "ENG_to_JPN_Answer_D": "落胆して"
},
{
  "word": "plaque",
  "explanation": "「plaque」は記念のプレートや盾、あるいは歯垢など、硬い表面に付着する膜状のものを指す名詞です。文脈によっては、建物の来歴を示す銘板や顕彰プレートを示すことも多く、歯科分野では歯垢を表します。",
  "exampleSentence": "They unveiled a commemorative p_____ at the historical site.",
  "japaneseTranslation": "その歴史的な場所で記念プレートが除幕されました。",
  "meaningNoun": "銘板、歯垢（文脈により)",
  "phoneticSymbols": "/plæk/ (AmE often /plæk/ or /plɑːk/)",
  "ENG_to_JPN_Answer": "銘板",
  "ENG_to_JPN_Answer_A": "銘板",
  "ENG_to_JPN_Answer_B": "錠剤",
  "ENG_to_JPN_Answer_C": "手形",
  "ENG_to_JPN_Answer_D": "集会所"
},
{
  "word": "dilute",
  "explanation": "「dilute」は「希釈する」「薄める」という意味の動詞・形容詞で、液体や効果、影響などを弱める場合に使われます。化学や料理、ビジネス戦略など多様な文脈で、濃度や強度を下げることを示す表現です。",
  "exampleSentence": "You can d_____ the solution with water if it's too strong.",
  "japaneseTranslation": "もし濃度が強すぎる場合は、水でその溶液を希釈してください。",
  "meaningVerb": "希釈する、薄める",
  "phoneticSymbols": "/daɪˈluːt/",
  "wordSynonyms": "water down, weaken, thin out",
  "ENG_to_JPN_Answer": "希釈する",
  "ENG_to_JPN_Answer_A": "希釈する",
  "ENG_to_JPN_Answer_B": "梱包する",
  "ENG_to_JPN_Answer_C": "圧縮する",
  "ENG_to_JPN_Answer_D": "融合させる"
},
{
  "word": "exempt",
  "explanation": "「exempt」は「免除された」「～を免れた」という意味を持つ形容詞・動詞で、通常なら適用される規則や義務、費用などを支払わなくてよい状況を指します。税金や手数料、各種免除制度などを説明する場面でよく使われます。",
  "exampleSentence": "Employees working on weekends are e_____ from the parking fee.",
  "japaneseTranslation": "週末に働く従業員は駐車料金が免除されます。",
  "meaningAdjective": "免除された",
  "phoneticSymbols": "/ɪɡˈzɛmpt/",
  "wordSynonyms": "excused, freed, absolved",
  "ENG_to_JPN_Answer": "免除された",
  "ENG_to_JPN_Answer_A": "免除された",
  "ENG_to_JPN_Answer_B": "対象となる",
  "ENG_to_JPN_Answer_C": "考慮中の",
  "ENG_to_JPN_Answer_D": "特定されていない"
},
{
  "word": "centerpiece",
  "explanation": "「centerpiece」は「中心となるもの」「最も重要な要素」を指す名詞で、食卓の中央を飾る装飾品や、プロジェクトや議題の核心を示す場合にも用いられます。華やかさや注目を集めるポイントとして機能する概念です。",
  "exampleSentence": "The new policy became the c________ of the conference discussion.",
  "japaneseTranslation": "その新しい方針が会議の中心的な議題となりました。",
  "meaningNoun": "中心的存在、メインの装飾",
  "phoneticSymbols": "/ˈsɛn.tər.piːs/",
  "wordSynonyms": "focus, highlight, main feature",
  "ENG_to_JPN_Answer": "中心的存在",
  "ENG_to_JPN_Answer_A": "中心的存在",
  "ENG_to_JPN_Answer_B": "余剰物",
  "ENG_to_JPN_Answer_C": "秘密裏の計画",
  "ENG_to_JPN_Answer_D": "臨時措置"
},
{
  "word": "oversight",
  "explanation": "「oversight」は文脈によって「見落とし」「監督・管理」という二つの意味を持つ名詞です。見落としの場合は単なるミスを指し、監督という場合はプロセス全体を見渡して管理する行為を示します。混同に注意が必要な単語です。",
  "exampleSentence": "Due to an o________, the invoice was not sent out on time.",
  "japaneseTranslation": "見落としが原因で、その請求書は期日通りに送付されませんでした。",
  "meaningNoun": "見落とし、監督・管理",
  "phoneticSymbols": "/ˈoʊ.vɚ.saɪt/",
  "wordSynonyms": "error, lapse, supervision",
  "ENG_to_JPN_Answer": "見落とし",
  "ENG_to_JPN_Answer_A": "見落とし",
  "ENG_to_JPN_Answer_B": "過剰支払い",
  "ENG_to_JPN_Answer_C": "検査完了",
  "ENG_to_JPN_Answer_D": "自動送信"
},
{
  "word": "privileged",
  "explanation": "「privileged」は「特権のある」「恵まれた」という意味の形容詞で、一般的には得られない特別な権利や地位、機会を与えられている状態を指します。法律上の秘匿特権や、社会的に恵まれた環境を示す場合など、文脈に応じて幅広く使用されます。",
  "exampleSentence": "We feel p________ to have access to such valuable resources.",
  "japaneseTranslation": "私たちは、そのように貴重な資源を利用できる特権を与えられていることを光栄に思います。",
  "meaningAdjective": "特権のある、恵まれた",
  "phoneticSymbols": "/ˈprɪv.lɪdʒd/",
  "wordSynonyms": "advantaged, favored, special",
  "ENG_to_JPN_Answer": "特権のある",
  "ENG_to_JPN_Answer_A": "特権のある",
  "ENG_to_JPN_Answer_B": "未承諾の",
  "ENG_to_JPN_Answer_C": "隔離された",
  "ENG_to_JPN_Answer_D": "過度に単純な"
},
{
  "word": "recur",
  "explanation": "「recur」は「再発する」「繰り返し起こる」という意味の動詞で、病気やトラブルなど、同じ現象がまた発生する状況を示します。問題解決や定期的なイベントなど、繰り返しが想定される文脈で使われる単語です。",
  "exampleSentence": "The error may r____ if the system isn’t fully updated.",
  "japaneseTranslation": "システムが完全にアップデートされていない場合、そのエラーは再発する可能性があります。",
  "meaningVerb": "再発する、繰り返す",
  "phoneticSymbols": "/rɪˈkɜːr/ (AmE: /-ˈkɝː/)",
  "wordSynonyms": "happen again, repeat, return",
  "ENG_to_JPN_Answer": "再発する",
  "ENG_to_JPN_Answer_A": "再発する",
  "ENG_to_JPN_Answer_B": "拡散する",
  "ENG_to_JPN_Answer_C": "隠蔽する",
  "ENG_to_JPN_Answer_D": "無効化する"
},
{
  "word": "skeptical",
  "explanation": "「skeptical」は「懐疑的な」「疑い深い」という意味の形容詞で、新しい情報や提案に対してすぐに信じず、批判的に評価する態度を示します。科学やビジネスの分野など、証拠や合理性を重視する際にしばしば用いられます。",
  "exampleSentence": "He was s________ about the product’s claimed benefits.",
  "japaneseTranslation": "彼はその製品が謳うメリットに対して懐疑的でした。",
  "meaningAdjective": "懐疑的な、疑い深い",
  "phoneticSymbols": "/ˈskɛp.tɪ.kəl/",
  "wordSynonyms": "doubtful, dubious, suspicious",
  "wordAntonym": "convinced",
  "ENG_to_JPN_Answer": "懐疑的な",
  "ENG_to_JPN_Answer_A": "懐疑的な",
  "ENG_to_JPN_Answer_B": "肯定的な",
  "ENG_to_JPN_Answer_C": "義務的な",
  "ENG_to_JPN_Answer_D": "精巧な"
},
{
  "word": "sustainable",
  "explanation": "「sustainable」は「持続可能な」「環境に優しい」という意味の形容詞で、将来にわたって負荷をかけずに継続可能な状態や手法を表します。ビジネスや環境保護、社会的課題の文脈で特に重要なキーワードです。",
  "exampleSentence": "We aim to adopt s__________ practices throughout our supply chain.",
  "japaneseTranslation": "私たちはサプライチェーン全体で持続可能な手法を採用することを目指しています。",
  "meaningAdjective": "持続可能な、環境に配慮した",
  "phoneticSymbols": "/səˈsteɪ.nə.bəl/",
  "wordSynonyms": "eco-friendly, viable, renewable",
  "ENG_to_JPN_Answer": "持続可能な",
  "ENG_to_JPN_Answer_A": "持続可能な",
  "ENG_to_JPN_Answer_B": "短命な",
  "ENG_to_JPN_Answer_C": "不公平な",
  "ENG_to_JPN_Answer_D": "意図しない"
},
{
  "word": "artifact",
  "explanation": "「artifact」は「工芸品」「人工遺物」を指す名詞で、歴史的・文化的価値を持つ人間の手によって作られた品物を示します。博物館や考古学の文脈でよく使われ、過去の生活や芸術を知る手がかりとして重要視されます。",
  "exampleSentence": "The museum’s new exhibit features rare a________ from ancient civilizations.",
  "japaneseTranslation": "その博物館の新しい展示では、古代文明の希少な工芸品が紹介されています。",
  "meaningNoun": "工芸品、人工遺物",
  "phoneticSymbols": "/ˈɑː.tɪ.fækt/ (AmE: /ˈɑːr.t̬ə-/)",
  "wordSynonyms": "relic, object, historical item",
  "ENG_to_JPN_Answer": "工芸品",
  "ENG_to_JPN_Answer_A": "工芸品",
  "ENG_to_JPN_Answer_B": "自然鉱物",
  "ENG_to_JPN_Answer_C": "見本市",
  "ENG_to_JPN_Answer_D": "合成素材"
},
{
  "word": "keynote",
  "explanation": "「keynote」は「基調」「基本方針」を指す名詞で、イベントや会議などで最も重要なテーマや主題、もしくはそれを解説する講演を意味します。カンファレンスなどでは「基調講演（keynote speech）」としてよく使われます。",
  "exampleSentence": "The CEO delivered the k______ address at the annual conference.",
  "japaneseTranslation": "その年次カンファレンスで、CEOが基調講演を行いました。",
  "meaningNoun": "基調、基本方針",
  "phoneticSymbols": "/ˈkiː.noʊt/",
  "wordSynonyms": "main theme, central idea, focal point",
  "ENG_to_JPN_Answer": "基調",
  "ENG_to_JPN_Answer_A": "基調",
  "ENG_to_JPN_Answer_B": "謝辞",
  "ENG_to_JPN_Answer_C": "閉会宣言",
  "ENG_to_JPN_Answer_D": "打ち合わせ"
},
{
  "word": "breathtaking",
  "explanation": "「breathtaking」は「息をのむような」「驚くべき」という意味の形容詞で、景色や演出、出来事などが非常に美しく壮大であることを強調します。旅行や芸術作品のレビューなどで用いられることが多い表現です。",
  "exampleSentence": "We enjoyed a b___________ view from the mountain summit.",
  "japaneseTranslation": "私たちは山の頂上から息をのむような景色を堪能しました。",
  "meaningAdjective": "息をのむような、驚くべき",
  "phoneticSymbols": "/ˈbreθˌteɪ.kɪŋ/",
  "wordSynonyms": "astonishing, stunning, spectacular",
  "ENG_to_JPN_Answer": "息をのむような",
  "ENG_to_JPN_Answer_A": "息をのむような",
  "ENG_to_JPN_Answer_B": "退屈な",
  "ENG_to_JPN_Answer_C": "悲惨な",
  "ENG_to_JPN_Answer_D": "人里離れた"
},
{
  "word": "cubicle",
  "explanation": "「cubicle」はオフィスなどで区切られた小さな作業スペースを指す名詞で、パーティションやデスク周りを囲む仕切りによって、半個室のように作業環境を確保する形式を示します。オープンスペースとプライバシーを両立させるために用いられます。",
  "exampleSentence": "She works in a c______ surrounded by partitions.",
  "japaneseTranslation": "彼女はパーティションに囲まれた小さな作業スペースで仕事をしています。",
  "meaningNoun": "仕切られた小作業スペース",
  "phoneticSymbols": "/ˈkjuː.bɪ.kl̩/",
  "wordSynonyms": "compartment, workspace, booth",
  "ENG_to_JPN_Answer": "仕切られた小作業スペース",
  "ENG_to_JPN_Answer_A": "仕切られた小作業スペース",
  "ENG_to_JPN_Answer_B": "倉庫スペース",
  "ENG_to_JPN_Answer_C": "玄関口",
  "ENG_to_JPN_Answer_D": "防音室"
},
{
  "word": "outage",
  "explanation": "「outage」は停電や通信障害などの「供給停止」「機能停止」を指す名詞で、電力会社やインターネットプロバイダからの供給が止まる状態を示します。業務や生活に大きな影響を及ぼす場合が多く、迅速な対応が求められます。",
  "exampleSentence": "A power o_____ caused the factory to halt production temporarily.",
  "japaneseTranslation": "停電により、工場の生産は一時的に停止しました。",
  "meaningNoun": "供給停止、機能停止",
  "phoneticSymbols": "/ˈaʊ.tɪdʒ/",
  "wordSynonyms": "shutdown, blackout, failure",
  "ENG_to_JPN_Answer": "供給停止",
  "ENG_to_JPN_Answer_A": "供給停止",
  "ENG_to_JPN_Answer_B": "誤作動",
  "ENG_to_JPN_Answer_C": "脱税",
  "ENG_to_JPN_Answer_D": "除外"
},
{
  "word": "perishable",
  "explanation": "「perishable」は食品などが「腐りやすい」「傷みやすい」という意味の形容詞で、鮮度管理が必要な製品を表します。流通・保管の際には冷蔵・冷凍設備や迅速な配送が求められるため、サプライチェーン上の重要な概念です。",
  "exampleSentence": "Store p________ goods in a refrigerator to keep them fresh.",
  "japaneseTranslation": "腐りやすい食品は冷蔵庫に保管して鮮度を保ちましょう。",
  "meaningAdjective": "腐りやすい、傷みやすい",
  "phoneticSymbols": "/ˈper.ɪ.ʃə.bəl/",
  "wordSynonyms": "spoilable, easily spoiled, not durable",
  "ENG_to_JPN_Answer": "腐りやすい",
  "ENG_to_JPN_Answer_A": "腐りやすい",
  "ENG_to_JPN_Answer_B": "乾燥した",
  "ENG_to_JPN_Answer_C": "作動しにくい",
  "ENG_to_JPN_Answer_D": "温度耐性がある"
},
{
  "word": "avid",
  "explanation": "「avid」は「熱心な」「熱烈な」という意味の形容詞で、趣味や学習などに強い関心を抱き、積極的に取り組む姿勢を示します。本を大量に読む「avid reader」のような表現で使われることが多い単語です。",
  "exampleSentence": "He’s an a___ traveler who visits at least three countries a year.",
  "japaneseTranslation": "彼は毎年少なくとも3カ国を訪れる熱心な旅行好きです。",
  "meaningAdjective": "熱心な、熱烈な",
  "phoneticSymbols": "/ˈæv.ɪd/",
  "wordSynonyms": "enthusiastic, eager, passionate",
  "ENG_to_JPN_Answer": "熱心な",
  "ENG_to_JPN_Answer_A": "熱心な",
  "ENG_to_JPN_Answer_B": "何気ない",
  "ENG_to_JPN_Answer_C": "淡白な",
  "ENG_to_JPN_Answer_D": "厳粛な"
},
{
  "word": "detour",
  "explanation": "「detour」は「迂回」「遠回り」を指す名詞・動詞で、通行止めや事故などで本来のルートが使えない場合に、別の道を通る行為を示します。旅行や運搬時にはスケジュールへの影響を考慮し、事前に迂回路を確認することが重要です。",
  "exampleSentence": "We took a d_____ to avoid heavy traffic on the highway.",
  "japaneseTranslation": "高速道路の渋滞を避けるために私たちは迂回しました。",
  "meaningNoun": "迂回、遠回り",
  "phoneticSymbols": "/ˈdiː.tʊər/ (AmE: /-tʊr/)",
  "wordSynonyms": "bypass, diversion, alternate route",
  "ENG_to_JPN_Answer": "迂回",
  "ENG_to_JPN_Answer_A": "迂回",
  "ENG_to_JPN_Answer_B": "加速",
  "ENG_to_JPN_Answer_C": "深呼吸",
  "ENG_to_JPN_Answer_D": "直行"
},
{
  "word": "expedite",
  "explanation": "「expedite」は「迅速に進める」「はかどらせる」という意味の動詞で、手続きやプロセスを通常よりも早く完了させる場合に使われます。業務効率化や納期短縮の場面で特に重要となる表現です。",
  "exampleSentence": "We need to e________ the shipping process for urgent orders.",
  "japaneseTranslation": "至急の注文に対応するため、出荷プロセスを迅速化する必要があります。",
  "meaningVerb": "迅速に進める、はかどらせる",
  "phoneticSymbols": "/ˈek.spə.daɪt/",
  "wordSynonyms": "speed up, accelerate, facilitate",
  "wordAntonym": "delay",
  "ENG_to_JPN_Answer": "迅速に進める",
  "ENG_to_JPN_Answer_A": "迅速に進める",
  "ENG_to_JPN_Answer_B": "無視する",
  "ENG_to_JPN_Answer_C": "複雑化する",
  "ENG_to_JPN_Answer_D": "妨害する"
},
{
  "word": "vicinity",
  "explanation": "「vicinity」は「近辺」「周辺地域」を指す名詞で、ある地点や場所の周りにある範囲を示します。店舗や住宅探しなどで距離感やアクセスを説明する際にしばしば用いられる表現です。",
  "exampleSentence": "There are several restaurants in the v________ of the hotel.",
  "japaneseTranslation": "ホテルの近辺にはいくつかのレストランがあります。",
  "meaningNoun": "近辺、周辺地域",
  "phoneticSymbols": "/vɪˈsɪn.ə.ti/",
  "wordSynonyms": "neighborhood, area, proximity",
  "ENG_to_JPN_Answer": "近辺",
  "ENG_to_JPN_Answer_A": "近辺",
  "ENG_to_JPN_Answer_B": "奥地",
  "ENG_to_JPN_Answer_C": "国境線",
  "ENG_to_JPN_Answer_D": "気象条件"
},
{
  "word": "affiliated",
  "explanation": "「affiliated」は「提携している」「関連のある」という意味の形容詞で、企業や団体などが共同で事業を行っていたり、同じグループに属している関係性を示します。ビジネスパートナーや子会社との関係を説明する際によく使われます。",
  "exampleSentence": "This organization is a________ with several global NGOs.",
  "japaneseTranslation": "この組織はいくつかのグローバルなNGOと提携しています。",
  "meaningAdjective": "提携している、関連のある",
  "phoneticSymbols": "/əˈfɪl.i.eɪ.tɪd/",
  "wordSynonyms": "associated, connected, allied",
  "ENG_to_JPN_Answer": "提携している",
  "ENG_to_JPN_Answer_A": "提携している",
  "ENG_to_JPN_Answer_B": "孤立している",
  "ENG_to_JPN_Answer_C": "競合している",
  "ENG_to_JPN_Answer_D": "見習い中の"
},
{
  "word": "definitive",
  "explanation": "「definitive」は「最終的な」「決定版の」という意味の形容詞で、これ以上の変更や疑義のない確定的な状態、あるいは完全性の高い内容を示します。研究やレポートが「決定版」として位置付けられる場合にも用いられます。",
  "exampleSentence": "This report provides a d________ analysis of consumer trends.",
  "japaneseTranslation": "このレポートは消費者動向に関する決定版の分析を提供しています。",
  "meaningAdjective": "最終的な、決定版の",
  "phoneticSymbols": "/dɪˈfɪn.ɪ.tɪv/",
  "wordSynonyms": "conclusive, authoritative, final",
  "wordAntonym": "tentative",
  "ENG_to_JPN_Answer": "最終的な",
  "ENG_to_JPN_Answer_A": "最終的な",
  "ENG_to_JPN_Answer_B": "柔軟な",
  "ENG_to_JPN_Answer_C": "矛盾した",
  "ENG_to_JPN_Answer_D": "曖昧な"
},
{
  "word": "demolish",
  "explanation": "「demolish」は「取り壊す」「破壊する」という意味を持つ動詞で、建物や構造物を完全に解体する場合などに使われます。再開発や古い建物の撤去時に用いられ、比喩的に論理や主張を「打ち破る」という意味でも使われることがあります。",
  "exampleSentence": "They plan to d_______ the old warehouse to build a new mall.",
  "japaneseTranslation": "新しいショッピングモールを建設するために、古い倉庫を取り壊す予定です。",
  "meaningVerb": "取り壊す、破壊する",
  "phoneticSymbols": "/dɪˈmɒl.ɪʃ/ (AmE: /dɪˈmɑː.lɪʃ/)",
  "wordSynonyms": "destroy, raze, tear down",
  "ENG_to_JPN_Answer": "取り壊す",
  "ENG_to_JPN_Answer_A": "取り壊す",
  "ENG_to_JPN_Answer_B": "改修する",
  "ENG_to_JPN_Answer_C": "装飾する",
  "ENG_to_JPN_Answer_D": "封鎖する"
},
{
  "word": "feasible",
  "explanation": "「feasible」は「実行可能な」「実現可能な」という意味の形容詞で、計画やアイデアが実際の状況下で成功裏に行える見込みがある場合に使われます。ビジネス・学術・工学など、あらゆる分野で検討内容の妥当性を評価する際に重要となる語です。",
  "exampleSentence": "We need to assess if this project is f_______ within our budget.",
  "japaneseTranslation": "予算内でこのプロジェクトが実行可能かどうかを評価する必要があります。",
  "meaningAdjective": "実行可能な、実現可能な",
  "phoneticSymbols": "/ˈfiː.zə.bəl/",
  "wordSynonyms": "possible, viable, workable",
  "wordAntonym": "impractical",
  "ENG_to_JPN_Answer": "実行可能な",
  "ENG_to_JPN_Answer_A": "実行可能な",
  "ENG_to_JPN_Answer_B": "任意の",
  "ENG_to_JPN_Answer_C": "不当な",
  "ENG_to_JPN_Answer_D": "過剰な"
},
{
  "word": "inaugural",
  "explanation": "「inaugural」は「就任の」「初開催の」という意味の形容詞で、新たに就任した人物や、新規イベントが始まる際に用いられます。大統領の就任演説や初回のカンファレンスなど、重要なスタートを表す場面でよく登場します。",
  "exampleSentence": "This is the i________ event of our annual leadership forum.",
  "japaneseTranslation": "これは私たちの年次リーダーシップフォーラムの初開催となるイベントです。",
  "meaningAdjective": "就任の、初開催の",
  "phoneticSymbols": "/ɪˈnɔː.ɡjʊ.rəl/ (AmE: /-ˈnɑː-/)",
  "wordSynonyms": "first, opening, initial",
  "ENG_to_JPN_Answer": "初開催の",
  "ENG_to_JPN_Answer_A": "初開催の",
  "ENG_to_JPN_Answer_B": "義務的な",
  "ENG_to_JPN_Answer_C": "並行している",
  "ENG_to_JPN_Answer_D": "長期的な"
},
{
  "word": "installment",
  "explanation": "「installment」は「分割払い」「分冊」などを指す名詞で、大きな支払いを複数回に分けて行う場合や、シリーズものの一部としての刊行物を示します。特にローンやサブスクリプションでの支払い計画として多用される言葉です。",
  "exampleSentence": "You can pay for the car in monthly i________ over two years.",
  "japaneseTranslation": "その車は2年間の月々の分割払いで購入できます。",
  "meaningNoun": "分割払い、分冊・シリーズの一部",
  "phoneticSymbols": "/ɪnˈstɔːl.mənt/ (AmE: /-ˈstɑːl-/)",
  "wordSynonyms": "partial payment, segment, episode",
  "ENG_to_JPN_Answer": "分割払い",
  "ENG_to_JPN_Answer_A": "分割払い",
  "ENG_to_JPN_Answer_B": "値上げ",
  "ENG_to_JPN_Answer_C": "一括前払い",
  "ENG_to_JPN_Answer_D": "保証費"
},
{
  "word": "redeemable",
  "explanation": "「redeemable」は「交換可能な」「償還できる」という意味を持つ形容詞で、クーポンやポイントなどを現金や商品に引き換えできる場合や、債券が将来償還される場合に使われます。買い物や金融商品でよく用いられる表現です。",
  "exampleSentence": "The gift certificate is r________ for any item in the store.",
  "japaneseTranslation": "そのギフト券は店内のどのアイテムにも交換することができます。",
  "meaningAdjective": "交換可能な、償還できる",
  "phoneticSymbols": "/rɪˈdiː.mə.bəl/",
  "wordSynonyms": "exchangeable, refundable, cashable",
  "ENG_to_JPN_Answer": "交換可能な",
  "ENG_to_JPN_Answer_A": "交換可能な",
  "ENG_to_JPN_Answer_B": "不可分な",
  "ENG_to_JPN_Answer_C": "強制的な",
  "ENG_to_JPN_Answer_D": "偽造防止の"
},
{
  "word": "streamline",
  "explanation": "「streamline」は「合理化する」「簡略化する」という意味の動詞で、業務プロセスやシステムを見直して、より効率的にし、無駄を省くことを指します。コスト削減やスピードアップなどを目指すビジネス改革の際に頻繁に使われるキーワードです。",
  "exampleSentence": "We plan to s________ the workflow to improve productivity.",
  "japaneseTranslation": "生産性を向上させるために、ワークフローを合理化する予定です。",
  "meaningVerb": "合理化する、簡略化する",
  "phoneticSymbols": "/ˈstriːm.laɪn/",
  "wordSynonyms": "simplify, optimize, modernize",
  "ENG_to_JPN_Answer": "合理化する",
  "ENG_to_JPN_Answer_A": "合理化する",
  "ENG_to_JPN_Answer_B": "混乱させる",
  "ENG_to_JPN_Answer_C": "継承する",
  "ENG_to_JPN_Answer_D": "解体する"
},
{
  "word": "insulation",
  "explanation": "「insulation」は「断熱材」「絶縁体」など、外部環境からの温度変化や電気的影響を遮断するために用いられる素材や処理を指す名詞です。建築・電気工事など多くの分野で使われ、快適性や安全性を確保する上で重要となる概念です。",
  "exampleSentence": "Proper i________ can significantly lower energy costs.",
  "japaneseTranslation": "適切な断熱材を使用すると、エネルギーコストを大幅に削減できます。",
  "meaningNoun": "断熱材、絶縁材",
  "phoneticSymbols": "/ˌɪn.sjəˈleɪ.ʃən/ (AmE: /-sə-/)",
  "wordSynonyms": "protection, barrier, sealing",
  "ENG_to_JPN_Answer": "断熱材",
  "ENG_to_JPN_Answer_A": "断熱材",
  "ENG_to_JPN_Answer_B": "冷凍庫",
  "ENG_to_JPN_Answer_C": "複写機",
  "ENG_to_JPN_Answer_D": "拡声器"
},
{
  "word": "intact",
  "explanation": "「intact」は「無傷の」「完全な状態の」という意味の形容詞で、物やシステムなどが損傷を受けず、本来の状態を保っていることを示します。輸送や保存の場面、またはデータの整合性を話題にする際によく登場する語です。",
  "exampleSentence": "The package arrived i_____ despite the long journey.",
  "japaneseTranslation": "長い道のりにもかかわらず、その荷物は無傷の状態で届きました。",
  "meaningAdjective": "損なわれていない、完全な状態の",
  "phoneticSymbols": "/ɪnˈtækt/",
  "wordSynonyms": "undamaged, whole, untouched",
  "wordAntonym": "damaged",
  "ENG_to_JPN_Answer": "無傷の",
  "ENG_to_JPN_Answer_A": "無傷の",
  "ENG_to_JPN_Answer_B": "隠蔽された",
  "ENG_to_JPN_Answer_C": "希薄な",
  "ENG_to_JPN_Answer_D": "二次的な"
},
{
  "word": "occupancy",
  "explanation": "「occupancy」は「占有（状態）」「稼働率」「宿泊率」を示す名詞で、ホテルや建物、部屋などが実際に使われている割合を指します。経営分析や不動産管理などで用いられ、資源の利用状況を評価する上で重要な指標です。",
  "exampleSentence": "The hotel’s o________ is nearly 90% during peak season.",
  "japaneseTranslation": "ピークシーズンには、そのホテルの稼働率はほぼ90%に達します。",
  "meaningNoun": "占有、稼働率",
  "phoneticSymbols": "/ˈɒk.jə.pən.si/ (AmE: /ˈɑːk.jə-)",
  "wordSynonyms": "usage rate, tenancy, occupancy rate",
  "ENG_to_JPN_Answer": "稼働率",
  "ENG_to_JPN_Answer_A": "稼働率",
  "ENG_to_JPN_Answer_B": "備蓄量",
  "ENG_to_JPN_Answer_C": "日焼け度",
  "ENG_to_JPN_Answer_D": "割引率"
},
{
  "word": "turnover",
  "explanation": "「turnover」は「離職率」「売上高」など、文脈によって異なる意味を持つ名詞です。人事では一定期間に退職・入社する人数の割合を示し、財務・経営では一定期間内に企業が得た売上総額を指します。",
  "exampleSentence": "Our staff t_______ has decreased since we improved benefits.",
  "japaneseTranslation": "福利厚生を改善してから、私たちのスタッフの離職率は下がりました。",
  "meaningNoun": "離職率、売上高",
  "phoneticSymbols": "/ˈtɜːnˌəʊ.vər/ (AmE: /ˈtɝːnˌoʊ.vɚ/)",
  "wordSynonyms": "staff attrition, sales revenue, revenue",
  "ENG_to_JPN_Answer": "離職率または売上高",
  "ENG_to_JPN_Answer_A": "離職率または売上高",
  "ENG_to_JPN_Answer_B": "設備投資",
  "ENG_to_JPN_Answer_C": "誤差範囲",
  "ENG_to_JPN_Answer_D": "市場占有率"
},
{
  "word": "unanimous",
  "explanation": "「unanimous」は「全会一致の」「意見が一致した」という意味の形容詞で、会議や投票などにおいて参加者全員が同じ意見・結論に達している状態を表します。合意形成を強調する文脈でよく使われる語です。",
  "exampleSentence": "The committee reached a u________ decision to approve the proposal.",
  "japaneseTranslation": "委員会はその提案を承認するという全会一致の決定に至りました。",
  "meaningAdjective": "全会一致の",
  "phoneticSymbols": "/juːˈnæn.ɪ.məs/",
  "wordSynonyms": "in complete agreement, united, of one mind",
  "ENG_to_JPN_Answer": "全会一致の",
  "ENG_to_JPN_Answer_A": "全会一致の",
  "ENG_to_JPN_Answer_B": "僅差で可決された",
  "ENG_to_JPN_Answer_C": "否決された",
  "ENG_to_JPN_Answer_D": "厳密ではない"
},
{
  "word": "deteriorate",
  "explanation": "「deteriorate」は「悪化する」「低下する」という意味の動詞で、状況や品質、健康状態などが徐々に悪くなっていく様子を示します。経済環境や環境問題、病状など、継続的にマイナス方向に進む場合に使われる重要な表現です。",
  "exampleSentence": "If we ignore regular maintenance, the machine may d________ over time.",
  "japaneseTranslation": "定期的なメンテナンスを怠ると、機械は時とともに悪化する可能性があります。",
  "meaningVerb": "悪化する、低下する",
  "phoneticSymbols": "/dɪˈtɪə.ri.ə.reɪt/ (AmE: /-ˈtɪr.i-/)",
  "wordSynonyms": "worsen, decline, degrade",
  "wordAntonym": "improve",
  "ENG_to_JPN_Answer": "悪化する",
  "ENG_to_JPN_Answer_A": "悪化する",
  "ENG_to_JPN_Answer_B": "保証する",
  "ENG_to_JPN_Answer_C": "修復する",
  "ENG_to_JPN_Answer_D": "隠蔽する"
},
{
  "word": "sturdy",
  "explanation": "「sturdy」は「頑丈な」「しっかりした」という意味の形容詞で、物や体が壊れにくく安定感がある状態を表します。家具や建物、スポーツ用品など、耐久性が求められる場面でしばしば用いられる便利な単語です。",
  "exampleSentence": "This table is s_____ enough to hold heavy equipment.",
  "japaneseTranslation": "このテーブルは重い機器を支えるのに十分な頑丈さがあります。",
  "meaningAdjective": "頑丈な、しっかりした",
  "phoneticSymbols": "/ˈstɜː.di/ (AmE: /ˈstɝː-/)",
  "wordSynonyms": "robust, strong, durable",
  "wordAntonym": "fragile",
  "ENG_to_JPN_Answer": "頑丈な",
  "ENG_to_JPN_Answer_A": "頑丈な",
  "ENG_to_JPN_Answer_B": "繊細な",
  "ENG_to_JPN_Answer_C": "柔軟な",
  "ENG_to_JPN_Answer_D": "不格好な"
},
{
  "word": "adverse",
  "explanation": "「adverse」は「不利な」「有害な」という意味の形容詞で、状況や条件が望ましくない方向に働く様子を示します。天候や経済、健康など、多方面で悪い影響を及ぼす場合に使われる重要な単語です。",
  "exampleSentence": "The project was postponed due to a______ weather conditions.",
  "japaneseTranslation": "不利な天候状況のため、そのプロジェクトは延期されました。",
  "meaningAdjective": "不利な、有害な",
  "phoneticSymbols": "/ˈæd.vɜːs/ (AmE: /-vɝːs/)",
  "wordSynonyms": "unfavorable, harmful, negative",
  "wordAntonym": "favorable",
  "ENG_to_JPN_Answer": "不利な",
  "ENG_to_JPN_Answer_A": "不利な",
  "ENG_to_JPN_Answer_B": "快適な",
  "ENG_to_JPN_Answer_C": "過度な",
  "ENG_to_JPN_Answer_D": "強制的な"
},
{
  "word": "bearer",
  "explanation": "「bearer」は「持参人」「携行者」を指す名詞で、手紙や小切手、証券などを所持している人を表します。ビジネスや金融の文脈で使われ、特に「持参人払い」の小切手（bearer check）などの形で登場することがあります。",
  "exampleSentence": "This ticket states that the b_____ is entitled to free admission.",
  "japaneseTranslation": "このチケットには、所持している人が無料入場できると記載されています。",
  "meaningNoun": "持参人、携行者",
  "phoneticSymbols": "/ˈbeər.ər/ (AmE: /ˈber.ɚ/)",
  "wordSynonyms": "holder, carrier, possessor",
  "ENG_to_JPN_Answer": "持参人",
  "ENG_to_JPN_Answer_A": "持参人",
  "ENG_to_JPN_Answer_B": "受取拒否者",
  "ENG_to_JPN_Answer_C": "監督官",
  "ENG_to_JPN_Answer_D": "運搬機器"
},
{
  "word": "unprecedented",
  "explanation": "「unprecedented」は「前例のない」「かつてない」という意味の形容詞で、これまでに起こったことがなく新規性が高い状況を指します。社会現象や技術革新など、過去に類例がない出来事を強調する際に使われる表現です。",
  "exampleSentence": "The company experienced u_____________ growth in the last quarter.",
  "japaneseTranslation": "その会社は前期にかつてない成長を遂げました。",
  "meaningAdjective": "前例のない、空前の",
  "phoneticSymbols": "/ʌnˈpres.ɪ.den.tɪd/",
  "wordSynonyms": "unmatched, unparalleled, extraordinary",
  "ENG_to_JPN_Answer": "前例のない",
  "ENG_to_JPN_Answer_A": "前例のない",
  "ENG_to_JPN_Answer_B": "悲観的な",
  "ENG_to_JPN_Answer_C": "はるか昔の",
  "ENG_to_JPN_Answer_D": "平凡な"
},
{
  "word": "botanical",
  "explanation": "「botanical」は「植物の」「植物学の」という意味を持つ形容詞で、植物やその研究に関わるものを表します。植物園（botanical garden）や植物成分を使った製品など、自然や環境を論じる際に使われる用語です。",
  "exampleSentence": "She loves visiting b________ gardens to learn about rare plants.",
  "japaneseTranslation": "彼女は珍しい植物を学ぶために植物園を訪れるのが大好きです。",
  "meaningAdjective": "植物（学）の",
  "phoneticSymbols": "/bəˈtæn.ɪ.kəl/",
  "wordSynonyms": "plant-based, herbal, floristic",
  "ENG_to_JPN_Answer": "植物の",
  "ENG_to_JPN_Answer_A": "植物の",
  "ENG_to_JPN_Answer_B": "昆虫の",
  "ENG_to_JPN_Answer_C": "医学的な",
  "ENG_to_JPN_Answer_D": "天候の"
},
{
  "word": "commensurate",
  "explanation": "「commensurate」は「釣り合った」「比例した」という意味を持つ形容詞で、能力や成果、条件に見合った報酬や待遇など、相応する関係性を示す際に用いられます。ビジネスや学術論文などで、公平性を評価する場合に登場する単語です。",
  "exampleSentence": "Your salary will be c___________ with your experience.",
  "japaneseTranslation": "あなたの給与はあなたの経験に見合ったものになるでしょう。",
  "meaningAdjective": "釣り合った、比例した",
  "phoneticSymbols": "/kəˈmen.sjər.ət/",
  "wordSynonyms": "proportionate, corresponding, equivalent",
  "ENG_to_JPN_Answer": "釣り合った",
  "ENG_to_JPN_Answer_A": "釣り合った",
  "ENG_to_JPN_Answer_B": "公的支援の",
  "ENG_to_JPN_Answer_C": "停滞した",
  "ENG_to_JPN_Answer_D": "逆説的な"
},
{
  "word": "consecutive",
  "explanation": "「consecutive」は「連続した」「連続的な」という意味の形容詞で、何かが切れ目なく順番に続いている状態を表します。日数や年数、数字などが続いている場合に使われ、記録更新や成績評価などでよく登場する単語です。",
  "exampleSentence": "She worked seven c_________ days without a break.",
  "japaneseTranslation": "彼女は休みなしで7日間連続で働きました。",
  "meaningAdjective": "連続した、連続的な",
  "phoneticSymbols": "/kənˈsek.jə.tɪv/",
  "wordSynonyms": "in a row, sequential, back-to-back",
  "ENG_to_JPN_Answer": "連続した",
  "ENG_to_JPN_Answer_A": "連続した",
  "ENG_to_JPN_Answer_B": "不定期の",
  "ENG_to_JPN_Answer_C": "同時並行の",
  "ENG_to_JPN_Answer_D": "選択的な"
},
{
  "word": "deliberation",
  "explanation": "「deliberation」は「熟考」「審議」という意味を持つ名詞で、慎重に考えたり検討したりする行為を表します。会議や法廷などで重要な決定をする際に時間をかけて議論・検討するプロセスを指す表現として多用されます。",
  "exampleSentence": "After lengthy d____________, the board approved the new budget.",
  "japaneseTranslation": "長時間の熟考の末、取締役会は新たな予算を承認しました。",
  "meaningNoun": "熟考、審議",
  "phoneticSymbols": "/dɪˌlɪb.əˈreɪ.ʃən/",
  "wordSynonyms": "consideration, discussion, reflection",
  "ENG_to_JPN_Answer": "熟考",
  "ENG_to_JPN_Answer_A": "熟考",
  "ENG_to_JPN_Answer_B": "強行",
  "ENG_to_JPN_Answer_C": "暴露",
  "ENG_to_JPN_Answer_D": "妥協"
},
{
  "word": "discreetly",
  "explanation": "「discreetly」は「慎重に」「目立たないように」という意味の副詞で、周囲に配慮しながら細心の注意をもって行動する様子を示します。プライバシー保護や気まずい状況の回避など、配慮が必要なシーンでよく用いられる表現です。",
  "exampleSentence": "She d________ asked for a private meeting to discuss the issue.",
  "japaneseTranslation": "彼女はその問題を話し合うために慎重に個別のミーティングを依頼しました。",
  "meaningAdverb": "慎重に、目立たぬように",
  "phoneticSymbols": "/dɪˈskriːt.li/",
  "wordSynonyms": "carefully, tactfully, unobtrusively",
  "ENG_to_JPN_Answer": "慎重に",
  "ENG_to_JPN_Answer_A": "慎重に",
  "ENG_to_JPN_Answer_B": "強引に",
  "ENG_to_JPN_Answer_C": "大まかに",
  "ENG_to_JPN_Answer_D": "優先的に"
},
{
  "word": "entail",
  "explanation": "「entail」は「伴う」「含意する」「結果として～を必要とする」という意味の動詞で、ある行動や状況が次のステップや条件を必然的に引き起こすことを表します。契約条件や業務内容の説明などで頻繁に使われる重要な表現です。",
  "exampleSentence": "The position may e_____ working overtime during peak season.",
  "japaneseTranslation": "その職務には繁忙期の残業が伴う場合があります。",
  "meaningVerb": "伴う、必要とする",
  "phoneticSymbols": "/ɪnˈteɪl/ (also /en-/)",
  "wordSynonyms": "involve, require, necessitate",
  "ENG_to_JPN_Answer": "伴う",
  "ENG_to_JPN_Answer_A": "伴う",
  "ENG_to_JPN_Answer_B": "提案する",
  "ENG_to_JPN_Answer_C": "否定する",
  "ENG_to_JPN_Answer_D": "報酬を約束する"
},
{
  "word": "fluctuation",
  "explanation": "「fluctuation」は「変動」「上下」を指す名詞で、経済指標や温度などが一定ではなく上がり下がりする状況を表します。マーケットの動向や自然現象など、安定しない要素に言及する際に重宝される単語です。",
  "exampleSentence": "Currency f____________ can affect international trade significantly.",
  "japaneseTranslation": "為替の変動は国際貿易に大きな影響を及ぼす可能性があります。",
  "meaningNoun": "変動、上下",
  "phoneticSymbols": "/ˌflʌk.tʃuˈeɪ.ʃən/",
  "wordSynonyms": "variation, oscillation, volatility",
  "ENG_to_JPN_Answer": "変動",
  "ENG_to_JPN_Answer_A": "変動",
  "ENG_to_JPN_Answer_B": "固定",
  "ENG_to_JPN_Answer_C": "合併",
  "ENG_to_JPN_Answer_D": "沈静化"
},
{
  "word": "foremost",
  "explanation": "「foremost」は「最も重要な」「第一線の」という意味の形容詞で、ある分野において最高の地位や権威を持つ存在や、最優先されるべき事項を表します。専門家の評価や組織のリーダーシップなどを形容する際によく使われる表現です。",
  "exampleSentence": "He is one of the f_______ experts in renewable energy.",
  "japaneseTranslation": "彼は再生可能エネルギーの分野で最も重要な専門家の一人です。",
  "meaningAdjective": "最も重要な、第一人者の",
  "phoneticSymbols": "/ˈfɔː.məʊst/ (AmE: /ˈfɔːr.moʊst/)",
  "wordSynonyms": "leading, principal, top",
  "ENG_to_JPN_Answer": "最も重要な",
  "ENG_to_JPN_Answer_A": "最も重要な",
  "ENG_to_JPN_Answer_B": "平均的な",
  "ENG_to_JPN_Answer_C": "冗長的な",
  "ENG_to_JPN_Answer_D": "弱小な"
},
{
  "word": "imperative",
  "explanation": "「imperative」は「必須の」「急を要する」という意味の形容詞・名詞で、避けられない義務や喫緊の課題を表します。ビジネスや政治の場面で、この対応を怠ると大きなリスクがある場合に用いられる重要な語です。",
  "exampleSentence": "It’s i________ to address the issue before it escalates further.",
  "japaneseTranslation": "問題がこれ以上深刻化する前に対応することが必須です。",
  "meaningAdjective": "必須の、急を要する",
  "phoneticSymbols": "/ɪmˈper.ə.tɪv/",
  "wordSynonyms": "critical, essential, urgent",
  "ENG_to_JPN_Answer": "必須の",
  "ENG_to_JPN_Answer_A": "必須の",
  "ENG_to_JPN_Answer_B": "割高の",
  "ENG_to_JPN_Answer_C": "余裕のある",
  "ENG_to_JPN_Answer_D": "妥協的な"
},
{
  "word": "mandatory",
  "explanation": "「mandatory」は「義務的な」「強制的な」という意味の形容詞で、法律や規則などによって必ず行わなければならない状況を表します。会社の研修参加や法定手続きなど、従わない場合には罰則や不利益が生じる場面で使われます。",
  "exampleSentence": "Attendance at the safety training is m________ for all employees.",
  "japaneseTranslation": "安全研修への参加は全従業員に対して義務付けられています。",
  "meaningAdjective": "義務的な、強制的な",
  "phoneticSymbols": "/ˈmæn.də.tər.i/ (AmE: /-tɔːr.i/)",
  "wordSynonyms": "compulsory, required, obligatory",
  "ENG_to_JPN_Answer": "義務的な",
  "ENG_to_JPN_Answer_A": "義務的な",
  "ENG_to_JPN_Answer_B": "自発的な",
  "ENG_to_JPN_Answer_C": "一時的な",
  "ENG_to_JPN_Answer_D": "稀少な"
},
{
  "word": "meticulously",
  "explanation": "「meticulously」は「細心の注意を払って」「綿密に」という意味の副詞で、非常に丁寧に一つひとつの要素を確認しながら作業する様子を表します。ミスの許されない設計や検査などで求められる、慎重な姿勢を示す語です。",
  "exampleSentence": "She m____________ reviewed every detail of the report.",
  "japaneseTranslation": "彼女は報告書の細部を非常に綿密に確認しました。",
  "meaningAdverb": "細心の注意を払って、綿密に",
  "phoneticSymbols": "/məˈtɪk.jə.ləs.li/",
  "wordSynonyms": "carefully, thoroughly, painstakingly",
  "ENG_to_JPN_Answer": "細心の注意を払って",
  "ENG_to_JPN_Answer_A": "細心の注意を払って",
  "ENG_to_JPN_Answer_B": "焦って",
  "ENG_to_JPN_Answer_C": "奔放に",
  "ENG_to_JPN_Answer_D": "不定期に"
},
{
  "word": "outreach",
  "explanation": "「outreach」は「支援活動」「情報提供活動」を指す名詞・動詞で、地域社会や特定の集団に対して、企業や団体が手を差し伸べて行う活動を意味します。啓発や教育、ボランティアなど、相手に直接働きかけるアプローチでよく使われる表現です。",
  "exampleSentence": "Our o_______ program helps local communities access essential services.",
  "japaneseTranslation": "当社の支援活動プログラムは地域社会が必要なサービスにアクセスする手助けをしています。",
  "meaningNoun": "支援活動、情報提供活動",
  "phoneticSymbols": "/ˈaʊt.riːtʃ/",
  "wordSynonyms": "support program, community service, engagement",
  "ENG_to_JPN_Answer": "支援活動",
  "ENG_to_JPN_Answer_A": "支援活動",
  "ENG_to_JPN_Answer_B": "広告戦略",
  "ENG_to_JPN_Answer_C": "資金調達",
  "ENG_to_JPN_Answer_D": "在庫管理"
},
{
  "word": "tenure",
  "explanation": "「tenure」は「在職期間」「保有期間」を示す名詞で、特定の役職や地位を務める期間を指します。大学教授や公職者などの人事制度でよく使われ、また、不動産における所有や賃貸の期間を表す場合にも登場します。",
  "exampleSentence": "During his t_____, he introduced major policy reforms.",
  "japaneseTranslation": "在職期間中に、彼は主要な政策改革を導入しました。",
  "meaningNoun": "在職期間、保有期間",
  "phoneticSymbols": "/ˈten.jər/ (AmE: /-jʊr/)",
  "wordSynonyms": "term, period, occupancy",
  "ENG_to_JPN_Answer": "在職期間",
  "ENG_to_JPN_Answer_A": "在職期間",
  "ENG_to_JPN_Answer_B": "試用期間",
  "ENG_to_JPN_Answer_C": "研修制度",
  "ENG_to_JPN_Answer_D": "終身保証"
},
{
  "word": "versatile",
  "explanation": "「versatile」は「多才な」「多用途の」という意味の形容詞で、人の場合は多方面のスキルを持つ、また物の場合はさまざまな用途に使えることを表します。柔軟性や対応力の高さを強調したいときに便利な表現です。",
  "exampleSentence": "This v________ tool can be used for cooking, baking, and even grilling.",
  "japaneseTranslation": "この多用途の器具は調理、焼き菓子作り、さらにはグリルにも使えます。",
  "meaningAdjective": "多才な、多用途の",
  "phoneticSymbols": "/ˈvɜː.sə.taɪl/ (AmE: /ˈvɝː.sə.t̬əl/)",
  "wordSynonyms": "adaptable, flexible, all-round",
  "ENG_to_JPN_Answer": "多才な",
  "ENG_to_JPN_Answer_A": "多才な",
  "ENG_to_JPN_Answer_B": "高額な",
  "ENG_to_JPN_Answer_C": "危険な",
  "ENG_to_JPN_Answer_D": "画期的な"
},
{
  "word": "alleviate",
  "explanation": "「alleviate」は「和らげる」「軽減する」という意味を持つ動詞で、痛みや負担、問題などを少しでも小さくする場合に使われます。医療や福祉分野からビジネスの問題解決まで、幅広い文脈で登場する便利な表現です。",
  "exampleSentence": "We need to a________ congestion by improving public transport.",
  "japaneseTranslation": "公共交通機関を改善することで混雑を緩和する必要があります。",
  "meaningVerb": "和らげる、軽減する",
  "phoneticSymbols": "/əˈliː.vi.eɪt/",
  "wordSynonyms": "reduce, relieve, ease",
  "ENG_to_JPN_Answer": "和らげる",
  "ENG_to_JPN_Answer_A": "和らげる",
  "ENG_to_JPN_Answer_B": "増幅する",
  "ENG_to_JPN_Answer_C": "遮断する",
  "ENG_to_JPN_Answer_D": "限定する"
},
{
  "word": "exemplary",
  "explanation": "「exemplary」は「模範的な」「称賛に値する」という意味の形容詞で、他の人が真似するに値する優れた行動や業績を評価する際に使われます。教育や職場での表彰、顧客サービスの事例など、ポジティブな称賛の文脈で登場することが多いです。",
  "exampleSentence": "She received an award for her e________ performance.",
  "japaneseTranslation": "彼女は模範的な業績により表彰を受けました。",
  "meaningAdjective": "模範的な、立派な",
  "phoneticSymbols": "/ɪɡˈzem.plər.i/",
  "wordSynonyms": "ideal, commendable, excellent",
  "ENG_to_JPN_Answer": "模範的な",
  "ENG_to_JPN_Answer_A": "模範的な",
  "ENG_to_JPN_Answer_B": "些細な",
  "ENG_to_JPN_Answer_C": "不十分な",
  "ENG_to_JPN_Answer_D": "常習的な"
},
{
  "word": "gala",
  "explanation": "「gala」は「祝祭」「盛大な催し」を指す名詞で、パーティーやイベントなど華やかな雰囲気の催し物を示します。チャリティーイベントや祝賀会など、ドレスコードや演出が豪華な場でしばしば使われる単語です。",
  "exampleSentence": "They organized a g___ to celebrate the charity’s anniversary.",
  "japaneseTranslation": "彼らはその慈善団体の周年を祝うために盛大なパーティーを企画しました。",
  "meaningNoun": "祝祭、盛大な催し",
  "phoneticSymbols": "/ˈɡɑː.lə/ (AmE: /ˈɡeɪ.lə/ など複数の発音あり)",
  "wordSynonyms": "festivity, celebration, grand event",
  "ENG_to_JPN_Answer": "盛大な催し",
  "ENG_to_JPN_Answer_A": "盛大な催し",
  "ENG_to_JPN_Answer_B": "会議室",
  "ENG_to_JPN_Answer_C": "配送トラック",
  "ENG_to_JPN_Answer_D": "稼働率"
},
{
  "word": "mural",
  "explanation": "「mural」は「壁画」「壁の装飾絵」を指す名詞で、建物の壁面に直接描かれる大規模な絵画や装飾を示します。公共施設やアートプロジェクトなどでよく見られ、その場の雰囲気や地域性を象徴する重要な文化的要素となります。",
  "exampleSentence": "The artist painted a colorful m____ on the side of the school.",
  "japaneseTranslation": "その芸術家は学校の壁面にカラフルな壁画を描きました。",
  "meaningNoun": "壁画、壁の装飾絵",
  "phoneticSymbols": "/ˈmjʊə.rəl/ (AmE: /ˈmjʊr.əl/)",
  "wordSynonyms": "wall painting, fresco, artwork",
  "ENG_to_JPN_Answer": "壁画",
  "ENG_to_JPN_Answer_A": "壁画",
  "ENG_to_JPN_Answer_B": "舞台照明",
  "ENG_to_JPN_Answer_C": "防音壁",
  "ENG_to_JPN_Answer_D": "アルバムアート"
},
{
  "word": "proprietor",
  "explanation": "「proprietor」は「所有者」「経営者」を指す名詞で、特に個人事業や店舗などを所有し、経営している人を意味します。企業形態としては法人ではなく個人名義の場合によく使われる表現で、経営責任を直接負う立場を表します。",
  "exampleSentence": "He’s the sole p________ of the small bookstore downtown.",
  "japaneseTranslation": "彼は街の中心部にあるその小さな書店の唯一の経営者です。",
  "meaningNoun": "所有者、経営者",
  "phoneticSymbols": "/prəˈpraɪə.tər/ (AmE: /-t̬ɚ/)",
  "wordSynonyms": "owner, holder, businessperson",
  "ENG_to_JPN_Answer": "所有者",
  "ENG_to_JPN_Answer_A": "所有者",
  "ENG_to_JPN_Answer_B": "派遣労働者",
  "ENG_to_JPN_Answer_C": "債権者",
  "ENG_to_JPN_Answer_D": "共同組合員"
},
{
  "word": "stagnant",
  "explanation": "「stagnant」は「停滞した」「よどんだ」という意味の形容詞で、経済や成長、流れが一時的または長期的に止まっている状態を表します。景気や業績が伸び悩む様子や、空気や水が動かずによどんでいる状態などに使われる表現です。",
  "exampleSentence": "The economy has been s_______ for months, with little sign of recovery.",
  "japaneseTranslation": "景気は数ヶ月にわたって停滞しており、回復の兆しはほとんどありません。",
  "meaningAdjective": "停滞した、よどんだ",
  "phoneticSymbols": "/ˈstæɡ.nənt/",
  "wordSynonyms": "still, sluggish, inactive",
  "wordAntonym": "dynamic",
  "ENG_to_JPN_Answer": "停滞した",
  "ENG_to_JPN_Answer_A": "停滞した",
  "ENG_to_JPN_Answer_B": "みずみずしい",
  "ENG_to_JPN_Answer_C": "誇張された",
  "ENG_to_JPN_Answer_D": "絶え間なく動く"
},
{
  "word": "stringent",
  "explanation": "「stringent」は「厳格な」「厳しい」という意味の形容詞で、規則や基準、制限などが非常に厳密に設定されていることを示します。安全基準や品質管理など、ミスが許されない場面で多用される重要な単語です。",
  "exampleSentence": "Our factory follows s________ safety protocols to ensure product quality.",
  "japaneseTranslation": "当工場では製品の品質を保証するため、厳格な安全プロトコルに従っています。",
  "meaningAdjective": "厳格な、厳しい",
  "phoneticSymbols": "/ˈstrɪn.dʒənt/",
  "wordSynonyms": "strict, rigorous, tough",
  "ENG_to_JPN_Answer": "厳格な",
  "ENG_to_JPN_Answer_A": "厳格な",
  "ENG_to_JPN_Answer_B": "曖昧な",
  "ENG_to_JPN_Answer_C": "即興の",
  "ENG_to_JPN_Answer_D": "臨時の"
},
{
  "word": "testimonial",
  "explanation": "「testimonial」は商品やサービスに対する「推薦状」「感想」「実績証明」を示す名詞です。顧客や利用者からの評価や経験談として、マーケティングや採用時の参考情報として活用されます。信頼性や品質をアピールする際に重要な役割を果たします。",
  "exampleSentence": "We included a positive t____________ from a satisfied client on our website.",
  "japaneseTranslation": "私たちは満足している顧客からの肯定的な推薦文をウェブサイトに掲載しました。",
  "meaningNoun": "推薦状、感想文、実績証明",
  "phoneticSymbols": "/ˌtes.tɪˈməʊ.ni.əl/ (AmE: /-ˈmoʊ-/)",
  "wordSynonyms": "endorsement, recommendation, statement",
  "ENG_to_JPN_Answer": "推薦文",
  "ENG_to_JPN_Answer_A": "推薦文",
  "ENG_to_JPN_Answer_B": "辞表",
  "ENG_to_JPN_Answer_C": "約款",
  "ENG_to_JPN_Answer_D": "再販証明"
},
{
  "word": "turnout",
  "explanation": "「turnout」は集会や選挙などの「参加者数」「投票率」を指す名詞で、どれだけの人が実際に足を運んだか、または行動を起こしたかを数量的に示す際に使われます。イベントや政治キャンペーンの成果を測る重要な指標です。",
  "exampleSentence": "The concert had an impressive t_______, with thousands in attendance.",
  "japaneseTranslation": "そのコンサートには何千人もの人が来場し、驚くべき参加者数を記録しました。",
  "meaningNoun": "参加者数、投票率",
  "phoneticSymbols": "/ˈtɜːn.aʊt/ (AmE: /ˈtɝːn-/)",
  "wordSynonyms": "attendance, participation, crowd",
  "ENG_to_JPN_Answer": "参加者数",
  "ENG_to_JPN_Answer_A": "参加者数",
  "ENG_to_JPN_Answer_B": "作業手順",
  "ENG_to_JPN_Answer_C": "賃金引当",
  "ENG_to_JPN_Answer_D": "集荷時間"
},
{
  "word": "waive",
  "explanation": "「waive」は「放棄する」「（権利や請求などを）免除する」という意味の動詞で、通常適用される費用や手続き、義務などをあえて行わずに免除する場合に用いられます。契約や法律の文脈でしばしば登場し、特別措置を示す際に重要な表現です。",
  "exampleSentence": "We decided to w____ the late fees for loyal customers.",
  "japaneseTranslation": "私たちは常連客に対して延滞料金を免除することにしました。",
  "meaningVerb": "放棄する、免除する",
  "phoneticSymbols": "/weɪv/",
  "wordSynonyms": "give up, relinquish, forgo",
  "ENG_to_JPN_Answer": "免除する",
  "ENG_to_JPN_Answer_A": "免除する",
  "ENG_to_JPN_Answer_B": "重課税する",
  "ENG_to_JPN_Answer_C": "譲渡する",
  "ENG_to_JPN_Answer_D": "請求を保留にする"
},
{
  "word": "faucet",
  "explanation": "「faucet」は蛇口を指す名詞で、シンクや洗面台などに取り付けられ、給水・止水を調節するための器具です。主に北米で用いられる表現で、イギリス英語では「tap」が同義語として使われます。",
  "exampleSentence": "The k______ faucet is dripping, so we should fix it.",
  "japaneseTranslation": "キッチンの蛇口が水漏れしているので、直したほうがいいですね。",
  "meaningNoun": "蛇口",
  "phoneticSymbols": "/ˈfɔː.sɪt/ (AmE: /ˈfɑː-/)",
  "wordSynonyms": "tap, spigot (AmE), valve",
  "ENG_to_JPN_Answer": "蛇口",
  "ENG_to_JPN_Answer_A": "蛇口",
  "ENG_to_JPN_Answer_B": "排水口",
  "ENG_to_JPN_Answer_C": "洗剤入れ",
  "ENG_to_JPN_Answer_D": "空気清浄機"
},
{
  "word": "amendment",
  "explanation": "「amendment」は「改正」「修正案」という意味を持つ名詞で、法律や規定などを変更・追加する際に用いられます。米国憲法の修正条項（Amendments）などが有名で、正式な手続きにより内容を修正する場合に使われる重要な表現です。",
  "exampleSentence": "The board approved an a________ to the company’s bylaws.",
  "japaneseTranslation": "取締役会は会社の内規に対する修正案を承認しました。",
  "meaningNoun": "改正、修正案",
  "phoneticSymbols": "/əˈmend.mənt/",
  "wordSynonyms": "revision, modification, change",
  "ENG_to_JPN_Answer": "改正",
  "ENG_to_JPN_Answer_A": "改正",
  "ENG_to_JPN_Answer_B": "合意破棄",
  "ENG_to_JPN_Answer_C": "無効判決",
  "ENG_to_JPN_Answer_D": "起訴"
},
{
  "word": "anonymous",
  "explanation": "「anonymous」は「匿名の」「作者不明の」という意味の形容詞で、個人の身元や情報を明かさない状態を示します。寄付や投稿などで身元を伏せる場合、あるいは作品の作者名が分からない場合に用いられる表現です。",
  "exampleSentence": "The donation was made by an a________ supporter.",
  "japaneseTranslation": "その寄付は匿名の支援者によって行われました。",
  "meaningAdjective": "匿名の、作者不明の",
  "phoneticSymbols": "/əˈnɒn.ɪ.məs/ (AmE: /-ˈnɑː-/)",
  "wordSynonyms": "unidentified, unnamed, unknown",
  "wordAntonym": "identified",
  "ENG_to_JPN_Answer": "匿名の",
  "ENG_to_JPN_Answer_A": "匿名の",
  "ENG_to_JPN_Answer_B": "大衆的な",
  "ENG_to_JPN_Answer_C": "著名な",
  "ENG_to_JPN_Answer_D": "短命な"
},
{
  "word": "fraud",
  "explanation": "「fraud」は「詐欺」「不正行為」を指す名詞で、金銭や権利などを不正な手段で得る行為を表します。企業活動や金融取引、インターネット上の詐欺など、多様な場面で問題となり、法律的にも厳しく取り締まられる行為です。",
  "exampleSentence": "The bank is investigating a possible f____ involving credit cards.",
  "japaneseTranslation": "銀行はクレジットカードに関わる可能性のある詐欺行為を調査しています。",
  "meaningNoun": "詐欺、不正行為",
  "phoneticSymbols": "/frɔːd/ (AmE: /frɑːd/)",
  "wordSynonyms": "scam, deception, swindle",
  "ENG_to_JPN_Answer": "詐欺",
  "ENG_to_JPN_Answer_A": "詐欺",
  "ENG_to_JPN_Answer_B": "慈善活動",
  "ENG_to_JPN_Answer_C": "宣誓供述",
  "ENG_to_JPN_Answer_D": "精算手続き"
},
{
  "word": "liable",
  "explanation": "「liable」は「法的責任がある」「～しがちな」という意味を持つ形容詞で、主に責任や義務を負っている状態を表します。契約や賠償問題などで法的に責任を問われる場合に用いられ、日常表現では「～しやすい」という軽い意味でも使われます。",
  "exampleSentence": "The company could be l_____ for damages if safety standards aren’t met.",
  "japaneseTranslation": "安全基準を満たさない場合、会社は損害に対して法的責任を問われる可能性があります。",
  "meaningAdjective": "法的責任がある、～しがちな",
  "phoneticSymbols": "/ˈlaɪ.ə.bəl/",
  "wordSynonyms": "responsible, accountable, likely",
  "ENG_to_JPN_Answer": "法的責任がある",
  "ENG_to_JPN_Answer_A": "法的責任がある",
  "ENG_to_JPN_Answer_B": "免除されている",
  "ENG_to_JPN_Answer_C": "軽蔑される",
  "ENG_to_JPN_Answer_D": "証拠不十分の"
},
{
  "word": "considerate",
  "explanation": "「considerate」は「思いやりのある」「配慮の行き届いた」という意味の形容詞で、相手の気持ちや状況を尊重し、行動や発言に気を配る態度を表します。ビジネスや日常生活での良好な人間関係を築く上で重要な資質として評価されます。",
  "exampleSentence": "Please be c________ of others when using shared facilities.",
  "japaneseTranslation": "共同施設を利用する際は、他の人に配慮をお願い致します。",
  "meaningAdjective": "思いやりのある、配慮のある",
  "phoneticSymbols": "/kənˈsɪd.ər.ət/",
  "wordSynonyms": "thoughtful, attentive, kind",
  "ENG_to_JPN_Answer": "思いやりのある",
  "ENG_to_JPN_Answer_A": "思いやりのある",
  "ENG_to_JPN_Answer_B": "攻撃的な",
  "ENG_to_JPN_Answer_C": "怠惰な",
  "ENG_to_JPN_Answer_D": "傲慢な"
},
{
  "word": "consolidate",
  "explanation": "「consolidate」は「統合する」「強化する」という意味の動詞で、複数のものを一つにまとめたり、基盤や立場をしっかり固める行為を示します。会社の合併や借金の一本化、権力の集中など、ビジネスや政治で多用される表現です。",
  "exampleSentence": "They plan to c__________ their loans into a single monthly payment.",
  "japaneseTranslation": "彼らは借金を一本化して月々一回の支払いにする予定です。",
  "meaningVerb": "統合する、強化する",
  "phoneticSymbols": "/kənˈsɒl.ɪ.deɪt/ (AmE: /-ˈsɑː.lɪ-/)",
  "wordSynonyms": "merge, combine, strengthen",
  "ENG_to_JPN_Answer": "統合する",
  "ENG_to_JPN_Answer_A": "統合する",
  "ENG_to_JPN_Answer_B": "分散させる",
  "ENG_to_JPN_Answer_C": "移譲する",
  "ENG_to_JPN_Answer_D": "詐称する"
},
{
  "word": "vigorous",
  "explanation": "「vigorous」は「活発な」「精力的な」という意味を持つ形容詞で、人や活動などがエネルギーに満ち溢れている様子を表します。スポーツやビジネスでの取り組み、あるいは成長市場などを形容する際に使われる便利な語です。",
  "exampleSentence": "They launched a v________ marketing campaign to boost sales.",
  "japaneseTranslation": "売上を伸ばすため、彼らは精力的なマーケティングキャンペーンを開始しました。",
  "meaningAdjective": "活発な、精力的な",
  "phoneticSymbols": "/ˈvɪɡ.ər.əs/",
  "wordSynonyms": "energetic, dynamic, lively",
  "ENG_to_JPN_Answer": "活発な",
  "ENG_to_JPN_Answer_A": "活発な",
  "ENG_to_JPN_Answer_B": "偽装した",
  "ENG_to_JPN_Answer_C": "消極的な",
  "ENG_to_JPN_Answer_D": "怠惰な"
},
{
  "word": "retreat",
  "explanation": "「retreat」は「退却」「後退」、または「静養・研修のための施設」を指す名詞・動詞です。軍事面では敵から退く行為を示し、ビジネスやスピリチュアル面では自然豊かな場所で行う研修やリラックスの機会を意味します。",
  "exampleSentence": "The team went on a r______ to brainstorm new ideas in a relaxed environment.",
  "japaneseTranslation": "チームは落ち着いた環境で新しいアイデアを出すための研修を行いに行きました。",
  "meaningNoun": "退却、研修・静養施設",
  "phoneticSymbols": "/rɪˈtriːt/",
  "wordSynonyms": "withdrawal, getaway, haven",
  "ENG_to_JPN_Answer": "退却（または研修）",
  "ENG_to_JPN_Answer_A": "退却（または研修）",
  "ENG_to_JPN_Answer_B": "攻勢",
  "ENG_to_JPN_Answer_C": "浪費",
  "ENG_to_JPN_Answer_D": "救援要請"
},
{
  "word": "custodian",
  "explanation": "「custodian」は建物や施設の「管理人」「守衛」、または「保管人」を指す名詞で、財産や書類などを安全に保持・管理する役割を担う人物を表します。学校やオフィスビルなどで清掃や簡単な修理を担う管理担当者もこう呼ばれます。",
  "exampleSentence": "The c________ ensures the building is well-maintained and secure.",
  "japaneseTranslation": "その管理人は建物が適切に維持管理され、安全が確保されていることを保証します。",
  "meaningNoun": "管理人、保管人",
  "phoneticSymbols": "/kʌˈstəʊ.di.ən/ (AmE: /-ˈstoʊ-/)",
  "wordSynonyms": "caretaker, guardian, keeper",
  "ENG_to_JPN_Answer": "管理人",
  "ENG_to_JPN_Answer_A": "管理人",
  "ENG_to_JPN_Answer_B": "借金取り",
  "ENG_to_JPN_Answer_C": "派遣社員",
  "ENG_to_JPN_Answer_D": "潜入捜査官"
},
{
  "word": "forge",
  "explanation": "「forge」は文脈に応じて複数の意味があり、「築く」「偽造する」という動詞として使われます。前者は関係や道を切り拓く際に、後者は文書や通貨などを不正に偽造する行為を示します。ビジネス面では主にポジティブに使われることが多いです。",
  "exampleSentence": "They hope to f____ strong partnerships with international firms.",
  "japaneseTranslation": "彼らは海外企業との強力なパートナーシップを築くことを望んでいます。",
  "meaningVerb": "（関係などを）築く、（文書などを）偽造する",
  "phoneticSymbols": "/fɔːdʒ/ (AmE: /fɔːrdʒ/)",
  "wordSynonyms": "establish, create, counterfeit",
  "ENG_to_JPN_Answer": "築く（または偽造する）",
  "ENG_to_JPN_Answer_A": "築く（または偽造する）",
  "ENG_to_JPN_Answer_B": "解体する",
  "ENG_to_JPN_Answer_C": "脅迫する",
  "ENG_to_JPN_Answer_D": "受け継ぐ"
},
{
  "word": "impending",
  "explanation": "「impending」は「差し迫った」「近い将来に起こりそうな」という意味の形容詞で、危機や重要なイベントなどが間近に迫っている状況を表します。ビジネスや政治、自然災害など、何か重大な出来事を予期する場面でよく使われます。",
  "exampleSentence": "Experts warn of an i________ economic downturn.",
  "japaneseTranslation": "専門家たちは差し迫った景気後退があると警告しています。",
  "meaningAdjective": "差し迫った、近い将来の",
  "phoneticSymbols": "/ɪmˈpen.dɪŋ/",
  "wordSynonyms": "upcoming, imminent, approaching",
  "ENG_to_JPN_Answer": "差し迫った",
  "ENG_to_JPN_Answer_A": "差し迫った",
  "ENG_to_JPN_Answer_B": "遠く及ばない",
  "ENG_to_JPN_Answer_C": "空想上の",
  "ENG_to_JPN_Answer_D": "一過性の"
},
{
  "word": "itemize",
  "explanation": "「itemize」は「項目ごとに列挙する」「内訳を示す」という意味の動詞で、レシートや報告書などで一つひとつの要素や費用を分けて明確に記載する場合に使われます。経理や会計での透明性を高める上で重宝される表現です。",
  "exampleSentence": "Please i______ all your business expenses in the report.",
  "japaneseTranslation": "ビジネス経費をレポートにすべて項目ごとに列挙してください。",
  "meaningVerb": "項目ごとに列挙する、内訳を示す",
  "phoneticSymbols": "/ˈaɪ.tə.maɪz/",
  "wordSynonyms": "list, detail, specify",
  "ENG_to_JPN_Answer": "項目ごとに列挙する",
  "ENG_to_JPN_Answer_A": "項目ごとに列挙する",
  "ENG_to_JPN_Answer_B": "概算を示す",
  "ENG_to_JPN_Answer_C": "破棄する",
  "ENG_to_JPN_Answer_D": "要約する"
},
{
  "word": "liaison",
  "explanation": "「liaison」は「連絡係」「調整役」という意味の名詞で、異なる組織や部門、個人同士の連携を円滑に進めるための架け橋となる役割を指します。コミュニケーションや情報交換が重要なプロジェクトでしばしば使用される表現です。",
  "exampleSentence": "She acts as a l______ between the marketing and sales teams.",
  "japaneseTranslation": "彼女はマーケティングチームとセールスチームの間の連絡係を務めています。",
  "meaningNoun": "連絡係、調整役",
  "phoneticSymbols": "/liˈeɪ.zɒn/ (AmE: /-zɑːn/ または /-zɒn/)",
  "wordSynonyms": "contact, intermediary, connection",
  "ENG_to_JPN_Answer": "連絡係",
  "ENG_to_JPN_Answer_A": "連絡係",
  "ENG_to_JPN_Answer_B": "競争相手",
  "ENG_to_JPN_Answer_C": "後援者",
  "ENG_to_JPN_Answer_D": "傍観者"
},
{
  "word": "objectionable",
  "explanation": "「objectionable」は「不快な」「問題のある」という意味の形容詞で、人々から反対や苦情を招くような行為や表現を示します。道徳的・社会的に受け入れがたい事柄を説明する場面で使われることが多い表現です。",
  "exampleSentence": "Some viewers found the commercial o____________ due to its content.",
  "japaneseTranslation": "一部の視聴者はそのコマーシャルの内容を不快に思いました。",
  "meaningAdjective": "不快な、問題のある",
  "phoneticSymbols": "/əbˈdʒek.ʃən.ə.bəl/",
  "wordSynonyms": "offensive, unacceptable, disagreeable",
  "ENG_to_JPN_Answer": "不快な",
  "ENG_to_JPN_Answer_A": "不快な",
  "ENG_to_JPN_Answer_B": "心地よい",
  "ENG_to_JPN_Answer_C": "誤りのない",
  "ENG_to_JPN_Answer_D": "改善された"
},
{
  "word": "repave",
  "explanation": "「repave」は「再舗装する」という意味の動詞で、道路や駐車場などの表面を新しいアスファルトやコンクリートで敷き直す作業を指します。インフラ整備や改修プロジェクトで用いられる表現で、道路の安全性や見た目を向上させる目的があります。",
  "exampleSentence": "The city will r_____ the main street to improve traffic flow.",
  "japaneseTranslation": "交通の流れを改善するために、市はメインストリートを再舗装する予定です。",
  "meaningVerb": "再舗装する",
  "phoneticSymbols": "/ˌriːˈpeɪv/",
  "ENG_to_JPN_Answer": "再舗装する",
  "ENG_to_JPN_Answer_A": "再舗装する",
  "ENG_to_JPN_Answer_B": "封鎖する",
  "ENG_to_JPN_Answer_C": "輪郭を描く",
  "ENG_to_JPN_Answer_D": "踏切を設置する"
},
{
  "word": "shortcoming",
  "explanation": "「shortcoming」は「欠点」「短所」を意味する名詞で、計画やシステム、人の性格などで不足や問題がある点を指します。改善提案や批判的検証の場面で使われ、課題認識を明確にする際に活躍する語です。",
  "exampleSentence": "Despite its benefits, the new software has some s____________ we need to address.",
  "japaneseTranslation": "利点がある一方で、その新しいソフトウェアには対処すべきいくつかの欠点があります。",
  "meaningNoun": "欠点、短所",
  "phoneticSymbols": "/ˈʃɔːtˌkʌm.ɪŋ/",
  "wordSynonyms": "defect, flaw, limitation",
  "ENG_to_JPN_Answer": "欠点",
  "ENG_to_JPN_Answer_A": "欠点",
  "ENG_to_JPN_Answer_B": "特権",
  "ENG_to_JPN_Answer_C": "冗談",
  "ENG_to_JPN_Answer_D": "期限延長"
},
{
  "word": "viable",
  "explanation": "「viable」は「実行可能な」「存続可能な」という意味の形容詞で、計画やビジネスモデルなどが成功する見込みがあり、経済的・技術的に成り立つ状態を示します。新規事業の立ち上げや研究開発の成果を評価する際によく登場します。",
  "exampleSentence": "They’re looking for a v______ solution that can be scaled globally.",
  "japaneseTranslation": "彼らはグローバルに拡張できる実行可能なソリューションを探しています。",
  "meaningAdjective": "実行可能な、存続可能な",
  "phoneticSymbols": "/ˈvaɪ.ə.bəl/",
  "wordSynonyms": "workable, feasible, practical",
  "wordAntonym": "unfeasible",
  "ENG_to_JPN_Answer": "実行可能な",
  "ENG_to_JPN_Answer_A": "実行可能な",
  "ENG_to_JPN_Answer_B": "酷使された",
  "ENG_to_JPN_Answer_C": "逆説的な",
  "ENG_to_JPN_Answer_D": "意図せぬ"
},
{
  "word": "memorabilia",
  "explanation": "「memorabilia」は「記念品」「思い出の品」を指す名詞の複数形で、有名人のサイン入りグッズやイベントの限定商品、旅行の際に手に入れた品物などを示します。コレクターズアイテムとしての価値も高く、収集の対象になることが多いです。",
  "exampleSentence": "He collects sports m____________ like signed baseballs and jerseys.",
  "japaneseTranslation": "彼はサイン入りの野球ボールやユニフォームなどのスポーツ記念品を収集しています。",
  "meaningNoun": "記念品、思い出の品（複数形）",
  "phoneticSymbols": "/ˌmem.ər.əˈbɪl.i.ə/",
  "wordSynonyms": "souvenirs, keepsakes, collectibles",
  "ENG_to_JPN_Answer": "記念品",
  "ENG_to_JPN_Answer_A": "記念品",
  "ENG_to_JPN_Answer_B": "金券",
  "ENG_to_JPN_Answer_C": "公証人",
  "ENG_to_JPN_Answer_D": "遺失物"
},
{
  "word": "deplete",
  "explanation": "「deplete」は「使い果たす」「枯渇させる」という意味を持つ動詞で、資源や在庫などが徐々に消費されてしまう様子を表します。環境問題やエネルギー資源の減少など、限りある資源を取り扱う文脈でしばしば登場する単語です。",
  "exampleSentence": "Overfishing can d______ the ocean’s fish populations.",
  "japaneseTranslation": "過剰な漁獲は海の魚の数を枯渇させる可能性があります。",
  "meaningVerb": "使い果たす、枯渇させる",
  "phoneticSymbols": "/dɪˈpliːt/",
  "wordSynonyms": "exhaust, use up, drain",
  "ENG_to_JPN_Answer": "枯渇させる",
  "ENG_to_JPN_Answer_A": "枯渇させる",
  "ENG_to_JPN_Answer_B": "保管する",
  "ENG_to_JPN_Answer_C": "安定化させる",
  "ENG_to_JPN_Answer_D": "誘導する"
},
{
  "word": "jeopardy",
  "explanation": "「jeopardy」は「危機」「危険」に直面している状態を指す名詞で、生命や財産、地位などが失われるリスクが高い状況を意味します。法律用語の「double jeopardy（二重処罰の禁止）」としても広く知られている表現です。",
  "exampleSentence": "The company’s reputation is in j_______ after the scandal.",
  "japaneseTranslation": "そのスキャンダルの後、会社の評判は危機にさらされています。",
  "meaningNoun": "危機、危険",
  "phoneticSymbols": "/ˈdʒep.ə.di/ (AmE: /-ɚ-/)",
  "wordSynonyms": "danger, peril, risk",
  "ENG_to_JPN_Answer": "危機",
  "ENG_to_JPN_Answer_A": "危機",
  "ENG_to_JPN_Answer_B": "温床",
  "ENG_to_JPN_Answer_C": "隠れ家",
  "ENG_to_JPN_Answer_D": "利益"
},
{
  "word": "nominal",
  "explanation": "「nominal」は「名目上の」「ごくわずかな」という意味を持つ形容詞で、実質的な価値や量が少ない場合や、形式だけのものを指す際に使われます。料金や費用がごくわずかである場合や、肩書だけが存在する場合などに頻出する単語です。",
  "exampleSentence": "They charge only a n______ fee for the membership service.",
  "japaneseTranslation": "その会員サービスには、名目上のわずかな料金しかかかりません。",
  "meaningAdjective": "名目上の、ごくわずかな",
  "phoneticSymbols": "/ˈnɒm.ɪ.nəl/ (AmE: /ˈnɑː.mə-/)",
  "wordSynonyms": "token, minimal, insignificant",
  "ENG_to_JPN_Answer": "名目上の",
  "ENG_to_JPN_Answer_A": "名目上の",
  "ENG_to_JPN_Answer_B": "流動的な",
  "ENG_to_JPN_Answer_C": "大幅な",
  "ENG_to_JPN_Answer_D": "恒久的な"
},
{
  "word": "deviate",
  "explanation": "「deviate」は「逸脱する」「それる」という意味の動詞で、計画やルート、規範などから外れた行動を取る場合に使われます。予定やルールがあるにもかかわらず別の方向に進む状況を示す際に用いられる表現です。",
  "exampleSentence": "We shouldn’t d______ from the original plan without proper reasoning.",
  "japaneseTranslation": "正当な理由がない限り、元の計画から逸脱すべきではありません。",
  "meaningVerb": "逸脱する、それる",
  "phoneticSymbols": "/ˈdiː.vi.eɪt/",
  "wordSynonyms": "diverge, stray, differ",
  "ENG_to_JPN_Answer": "逸脱する",
  "ENG_to_JPN_Answer_A": "逸脱する",
  "ENG_to_JPN_Answer_B": "集約する",
  "ENG_to_JPN_Answer_C": "促進する",
  "ENG_to_JPN_Answer_D": "報酬を与える"
},{
  "word": "forfeit",
  "explanation": "「forfeit」は「没収される」「権利を失う」「（権利を）放棄する」という意味の動詞・名詞で、ルール違反や契約不履行などが原因で利益や所持物を失う場合に使われます。スポーツやギャンブル、法的手続きなど、多様な場面で登場する語です。",
  "exampleSentence": "They had to f______ the match because of insufficient players.",
  "japaneseTranslation": "選手数が足りなかったため、彼らは試合を放棄しなければなりませんでした。",
  "meaningVerb": "没収される、放棄する",
  "phoneticSymbols": "/ˈfɔː.fɪt/ (AmE: /ˈfɔːr-/)",
  "wordSynonyms": "lose, give up, surrender",
  "ENG_to_JPN_Answer": "没収される（放棄する）",
  "ENG_to_JPN_Answer_A": "没収される（放棄する）",
  "ENG_to_JPN_Answer_B": "補償を要求する",
  "ENG_to_JPN_Answer_C": "値引きする",
  "ENG_to_JPN_Answer_D": "併合する"
},
{
  "word": "bolster",
  "explanation": "「bolster」は「強化する」「支援する」という意味の動詞で、計画や組織、感情などを支えたり補強したりする場合に使われます。信頼性や自信を高めたり、弱点を補完して安定性を増す際によく用いられる表現です。",
  "exampleSentence": "We need to b______ our online presence with better marketing strategies.",
  "japaneseTranslation": "より良いマーケティング戦略によって、オンラインでの存在感を強化する必要があります。",
  "meaningVerb": "強化する、支援する",
  "phoneticSymbols": "/ˈbəʊl.stər/ (AmE: /ˈboʊl-/)",
  "wordSynonyms": "strengthen, support, reinforce",
  "ENG_to_JPN_Answer": "強化する",
  "ENG_to_JPN_Answer_A": "強化する",
  "ENG_to_JPN_Answer_B": "削除する",
  "ENG_to_JPN_Answer_C": "中断する",
  "ENG_to_JPN_Answer_D": "転送する"
},
{
  "word": "optimal",
  "explanation": "「optimal」は「最適な」「ベストの」という意味を持つ形容詞で、状況や条件の中で最も望ましい選択や状態を示します。業務効率やパフォーマンスを最大化したい場合や、バランスを考慮して最も適切な解を導く際に使われる表現です。",
  "exampleSentence": "We found an o______ solution that satisfies both cost and quality requirements.",
  "japaneseTranslation": "コストと品質の要件を両立させる最適な解決策を見つけました。",
  "meaningAdjective": "最適な、ベストの",
  "phoneticSymbols": "/ˈɒp.tɪ.məl/ (AmE: /ˈɑːp-/)",
  "wordSynonyms": "ideal, best, perfect",
  "ENG_to_JPN_Answer": "最適な",
  "ENG_to_JPN_Answer_A": "最適な",
  "ENG_to_JPN_Answer_B": "推測の",
  "ENG_to_JPN_Answer_C": "臨時の",
  "ENG_to_JPN_Answer_D": "浮動的な"
},
{
  "word": "purveyor",
  "explanation": "「purveyor」は商品やサービスの「供給業者」「販売業者」を指す名詞で、特に食料品や原材料を卸したり供給したりする会社や個人を示します。飲食業や小売店などと取引し、安定した供給を行う役割を果たす点が特徴です。",
  "exampleSentence": "They are the main p________ of organic produce in this region.",
  "japaneseTranslation": "彼らはこの地域でオーガニック食品を主に供給する業者です。",
  "meaningNoun": "供給業者、販売業者",
  "phoneticSymbols": "/pɜːˈveɪ.ər/ (AmE: /pɝːˈveɪ.ɚ/)",
  "wordSynonyms": "supplier, vendor, provider",
  "ENG_to_JPN_Answer": "供給業者",
  "ENG_to_JPN_Answer_A": "供給業者",
  "ENG_to_JPN_Answer_B": "監督官",
  "ENG_to_JPN_Answer_C": "調停者",
  "ENG_to_JPN_Answer_D": "借主"
},
{
  "word": "raffle",
  "explanation": "「raffle」は「慈善などのためのくじ引き」「福引き」を指す名詞・動詞で、参加者がチケットを購入し、抽選で景品を渡す仕組みを表します。チャリティーイベントの一環として用いられることが多く、集まった資金は慈善活動に充てられます。",
  "exampleSentence": "The school organized a r_____ to raise funds for new equipment.",
  "japaneseTranslation": "学校は新しい設備を購入する資金を集めるために福引きを企画しました。",
  "meaningNoun": "慈善くじ、福引き",
  "phoneticSymbols": "/ˈræf.əl/",
  "wordSynonyms": "lottery, draw, tombola (BrE)",
  "ENG_to_JPN_Answer": "慈善くじ",
  "ENG_to_JPN_Answer_A": "慈善くじ",
  "ENG_to_JPN_Answer_B": "資金清算",
  "ENG_to_JPN_Answer_C": "財務監査",
  "ENG_to_JPN_Answer_D": "保険料徴収"
},
{
  "word": "ventilation",
  "explanation": "「ventilation」は「換気」「通気」を指す名詞で、室内や建物内の空気を外と入れ替えて、空気の質や温度を適切に保つために行う仕組みや行為を表します。エアコンや換気扇、窓の開閉などによって実現され、健康や快適性に大きく影響します。",
  "exampleSentence": "Proper v____________ is crucial for maintaining good indoor air quality.",
  "japaneseTranslation": "適切な換気は、良好な室内空気の質を保つために非常に重要です。",
  "meaningNoun": "換気、通気",
  "phoneticSymbols": "/ˌven.tɪˈleɪ.ʃən/",
  "wordSynonyms": "air circulation, airflow, freshening",
  "ENG_to_JPN_Answer": "換気",
  "ENG_to_JPN_Answer_A": "換気",
  "ENG_to_JPN_Answer_B": "仕分け",
  "ENG_to_JPN_Answer_C": "浄水",
  "ENG_to_JPN_Answer_D": "偏向"
},
{
  "word": "unwavering",
  "explanation": "「unwavering」は「揺るぎない」「断固とした」という意味の形容詞で、信念や態度などがいかなる困難にも動じない、揺らぐことのない様子を示します。リーダーシップや信頼関係などで、高い意志や決意を強調する場合に使われる表現です。",
  "exampleSentence": "Her u_________ dedication to the project inspired the whole team.",
  "japaneseTranslation": "プロジェクトに対する彼女の揺るぎない献身がチーム全体を鼓舞しました。",
  "meaningAdjective": "揺るぎない、断固とした",
  "phoneticSymbols": "/ʌnˈweɪ.vər.ɪŋ/",
  "wordSynonyms": "steady, resolute, unwavering",
  "ENG_to_JPN_Answer": "揺るぎない",
  "ENG_to_JPN_Answer_A": "揺るぎない",
  "ENG_to_JPN_Answer_B": "意図不明な",
  "ENG_to_JPN_Answer_C": "不均衡な",
  "ENG_to_JPN_Answer_D": "放棄された"
},
{
  "word": "exponentially",
  "explanation": "「exponentially」は「指数関数的に」「急速に」という意味の副詞で、数量や成長率が加速度的に増大する様子を示します。テクノロジーやビジネスの分野で、短期間に爆発的な進展を表す際に頻用される表現です。",
  "exampleSentence": "Online sales grew e_____________ after the holiday promotion campaign.",
  "japaneseTranslation": "ホリデーキャンペーンの後、オンライン販売は指数関数的に伸びました。",
  "meaningAdverb": "指数関数的に、急速に",
  "phoneticSymbols": "/ˌek.spəˈnen.ʃəl.i/",
  "wordSynonyms": "dramatically, rapidly, at an accelerating pace",
  "ENG_to_JPN_Answer": "指数関数的に",
  "ENG_to_JPN_Answer_A": "指数関数的に",
  "ENG_to_JPN_Answer_B": "漸進的に",
  "ENG_to_JPN_Answer_C": "極端にゆっくり",
  "ENG_to_JPN_Answer_D": "相対的に"
}
];

  for (var wordData in wordsData) {
    try {
      // コレクション内のドキュメント数を取得し、新しい Word_id を設定
      final snapshot = await firestore.collection(collectionPath).get();
      final newWordId = snapshot.docs.length + 1;

      // データをFirebaseに保存
      await firestore.collection(collectionPath).add({
        'Word_id': newWordId,
        'ENG_to_JPN_Answer': wordData['ENG_to_JPN_Answer'],
        'ENG_to_JPN_Answer_A': wordData['ENG_to_JPN_Answer_A'],
        'ENG_to_JPN_Answer_B': wordData['ENG_to_JPN_Answer_B'],
        'ENG_to_JPN_Answer_C': wordData['ENG_to_JPN_Answer_C'],
        'ENG_to_JPN_Answer_D': wordData['ENG_to_JPN_Answer_D'],
        'Word': wordData['word'] ?? '',
        'Explanation': wordData['explanation'] ?? '',
        'JPN_to_ENG_Answer': wordData['word'] ?? '',
        'JPN_to_ENG_Question_ENG': wordData['exampleSentence'] ?? '',
        'JPN_to_ENG_Question_JPN': wordData['japaneseTranslation'] ?? '',
        'Meaning_Adjective': wordData['meaningAdjective'] ?? '',
        'Meaning_Adverb': wordData['meaningAdverb'] ?? '',
        'Meaning_Noun': wordData['meaningNoun'] ?? '',
        'Meaning_Preposition': wordData['meaningPreposition'] ?? '',
        'Meaning_Verb': wordData['meaningVerb'] ?? '',
        'Phonetic_Symbols': wordData['phoneticSymbols'] ?? '',
        'Word_Preposition': wordData['wordPreposition'] ?? '',
        'Word_Related': wordData['wordRelated'] ?? '',
        'Word_Verb': wordData['wordVerb'] ?? '',
        'Word_Noun': wordData['wordNoun'] ?? '',
        'Word_Adjective': wordData['wordAdjective'] ?? '',
        'Word_Adverb': wordData['wordAdverb'] ?? '',
        'Word_Synonyms': wordData['wordSynonyms'] ?? '',
        'Word_Antonym': wordData['wordAntonym'] ?? '',
      });

      print('単語 "${wordData['word']}" を登録しました (Word_id: $newWordId)');
    } catch (e) {
      print('単語 "${wordData['word']}" の登録中にエラーが発生しました: $e');
    }
  }
}


